// app/links/links-client.tsx
"use client"

import { useCallback, useEffect, useState } from "react"
import Link from "next/link"
import { Check, Copy, ExternalLink, Trash2, X, Compass } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import {
  WorkspaceDataTable,
  WorkspaceDataTableBody,
  WorkspaceDataTableHeader,
  WorkspaceDataTableRow,
  WorkspaceEditButton,
  WorkspacePage,
  WorkspaceTableActions,
  WorkspaceTableCell,
  WorkspaceTableEmpty,
  WorkspaceTableInput,
  WorkspaceTableIconButton,
  WORKSPACE_TABLE_ACTIONS_WIDTH_WIDE,
  useEscapeToCancel,
  type WorkspaceTableColumn,
} from "@/app/components/workspace-ui"
import {
  createSavedLink,
  deleteSavedLink,
  enrichSavedLink,
  fetchSavedLinks,
  updateSavedLink,
  type SavedLinkRow,
} from "@/lib/workspace/client"
import { useInlineRowEdit } from "@/lib/workspace/use-inline-row-edit"
import { useWorkspaceProfile } from "@/lib/workspace/use-workspace-profile"

const emptyAddDraft = { url: "" }

function LoadingCell() {
  return <span className="text-sm text-app-muted animate-pulse">Carregando…</span>
}

function LinkUrlLine({ url }: { url: string }) {
  return (
    <a
      href={url}
      target="_blank"
      rel="noreferrer"
      className="mt-1 block min-w-0 truncate text-xs text-app-muted underline decoration-dotted underline-offset-2 transition-colors hover:text-app-fg"
      title={url}
    >
      {url}
    </a>
  )
}

function LinkCopyButton({
  url,
  disabled,
}: {
  url: string
  disabled?: boolean
}) {
  const [copied, setCopied] = useState(false)

  const handleCopy = async () => {
    const value = url.trim()
    if (!value) return
    try {
      await navigator.clipboard.writeText(value)
      setCopied(true)
      window.setTimeout(() => setCopied(false), 2000)
    } catch {
      // ignore — button stays in default state
    }
  }

  return (
    <WorkspaceTableIconButton
      title={copied ? "Copiado!" : "Copiar link"}
      aria-label={copied ? "Copiado!" : "Copiar link"}
      disabled={disabled || !url.trim()}
      onClick={() => void handleCopy()}
    >
      {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
    </WorkspaceTableIconButton>
  )
}

function LinkTitleBlock({
  title,
  url,
  enriching,
}: {
  title: string
  url: string
  enriching?: boolean
}) {
  if (enriching) {
    return <LoadingCell />
  }

  return (
    <div className="inline-flex max-w-full min-w-0 items-center gap-1">
      <a
        href={url}
        target="_blank"
        rel="noreferrer"
        className="min-w-0 cursor-pointer truncate font-medium leading-snug text-app-fg transition-colors hover:underline"
        title={title}
      >
        {title || "—"}
      </a>
      <a
        href={url}
        target="_blank"
        rel="noreferrer"
        className="shrink-0 text-app-muted transition-colors hover:text-app-fg"
        title="Abrir link"
        aria-label="Abrir link"
      >
        <ExternalLink className="h-3.5 w-3.5" />
      </a>
    </div>
  )
}

function makePendingRow(url: string, pendingId: string): SavedLinkRow {
  const now = new Date().toISOString()
  return {
    id: pendingId,
    userId: null,
    orgId: null,
    title: "",
    url,
    description: null,
    createdAt: now,
    updatedAt: now,
    enriching: true,
  }
}

const linkColumns: WorkspaceTableColumn<SavedLinkRow>[] = [
  {
    id: "title",
    header: "Link",
    width: "42%",
    renderView: (row) => (
      <div className="min-w-0">
        <LinkTitleBlock
          title={row.title}
          url={row.url}
          enriching={row.enriching}
        />
        <LinkUrlLine url={row.url} />
      </div>
    ),
    renderEdit: (row, onChange) => (
      <div className="flex min-w-0 flex-col gap-1.5">
        <WorkspaceTableInput
          placeholder="Título"
          value={row.title}
          onChange={(e) => onChange({ title: e.target.value })}
        />
        <WorkspaceTableInput
          placeholder="https://..."
          value={row.url}
          onChange={(e) => onChange({ url: e.target.value })}
        />
      </div>
    ),
  },
  {
    id: "description",
    header: "Descrição",
    width: "46%",
    renderView: (row) =>
      row.enriching ? (
        <LoadingCell />
      ) : row.enrichError ? (
        <span className="block min-w-0 text-xs text-amber-700 whitespace-pre-wrap break-words">
          {row.enrichError}
        </span>
      ) : (
        <span className="block min-w-0 whitespace-pre-wrap break-words text-app-fg leading-snug">
          {row.description ?? ""}
        </span>
      ),
    renderEdit: (row, onChange) => (
      <WorkspaceTableInput
        placeholder="Descrição"
        value={row.description ?? ""}
        onChange={(e) => onChange({ description: e.target.value })}
      />
    ),
  },
]

export function LinksClient() {
  const { orgId } = useWorkspaceProfile()
  const [links, setLinks] = useState<SavedLinkRow[]>([])
  const [addDraft, setAddDraft] = useState(emptyAddDraft)
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const { editingId, draft, startEdit, cancelEdit, isEditing, updateDraft } =
    useInlineRowEdit<SavedLinkRow>()

  const loadLinks = async () => {
    setLoading(true)
    setError(null)
    try {
      const data = await fetchSavedLinks(orgId)
      setLinks(data.links)
    } catch (err) {
      setError(err instanceof Error ? err.message : "Erro ao carregar links")
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void loadLinks()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [orgId])

  const handleCancelEdit = useCallback(() => cancelEdit(), [cancelEdit])
  useEscapeToCancel(editingId !== null, handleCancelEdit)

  const saveEdit = async () => {
    if (!draft || !editingId) return
    setSaving(true)
    setError(null)
    try {
      const { link } = await updateSavedLink(
        editingId,
        { title: draft.title, url: draft.url, description: draft.description },
        orgId
      )
      cancelEdit()
      setLinks((prev) =>
        prev.map((row) =>
          row.id === editingId
            ? { ...link, enriching: false, enrichError: null }
            : row
        )
      )
    } catch (err) {
      setError(err instanceof Error ? err.message : "Erro ao salvar link")
    } finally {
      setSaving(false)
    }
  }

  const runEnrichment = useCallback(
    async (linkId: string) => {
      try {
        const { link } = await enrichSavedLink(linkId, orgId)
        setLinks((prev) =>
          prev.map((row) =>
            row.id === linkId
              ? { ...link, enriching: false, enrichError: null }
              : row
          )
        )
      } catch (err) {
        const message =
          err instanceof Error && err.name === "AbortError"
            ? "Enriquecimento demorou demais; você pode editar o título e a descrição."
            : err instanceof Error
              ? err.message
              : "Não foi possível enriquecer o link"
        setLinks((prev) =>
          prev.map((row) =>
            row.id === linkId
              ? { ...row, enriching: false, enrichError: message }
              : row
          )
        )
      }
    },
    [orgId]
  )

  const addLink = async (urlOverride?: string) => {
    const url = (urlOverride ?? addDraft.url).trim()
    if (!url) return

    const pendingId = `pending-${crypto.randomUUID()}`
    setLinks((prev) => [makePendingRow(url, pendingId), ...prev])
    setAddDraft(emptyAddDraft)
    setError(null)

    try {
      const { link } = await createSavedLink({ url }, orgId)
      setLinks((prev) =>
        prev.map((row) =>
          row.id === pendingId
            ? { ...link, enriching: true, enrichError: null }
            : row
        )
      )
      void runEnrichment(link.id)
    } catch (err) {
      setLinks((prev) => prev.filter((row) => row.id !== pendingId))
      setError(err instanceof Error ? err.message : "Erro ao salvar link")
    }
  }

  const pasteAndSave = async () => {
    setError(null)
    try {
      const text = await navigator.clipboard.readText()
      const url = text.trim()
      if (!url) {
        setError("Nada na área de transferência para salvar.")
        return
      }
      setAddDraft({ url })
      await addLink(url)
    } catch {
      setError(
        "Não foi possível ler a área de transferência. Permita o acesso ou cole o link manualmente."
      )
    }
  }

  const isRowBusy = (link: SavedLinkRow) =>
    link.enriching || link.id.startsWith("pending-")

  const hasUrl = Boolean(addDraft.url.trim())
  const canUseAddRow = !saving && editingId === null
  const canSaveLink = hasUrl && canUseAddRow
  const canPasteAndSave = !hasUrl && canUseAddRow
  const canSubmitAddRow = canSaveLink || canPasteAndSave

  return (
    <WorkspacePage>
      <div className="-my-4">
        <div className="py-4">
          <div className="flex items-stretch gap-2">
            <Input
              type="text"
              className="h-11 flex-1 bg-white text-base dark:bg-white"
              placeholder="Cole aqui links, buscas com filtros, sites úteis e referências externas."
              value={addDraft.url}
              disabled={saving || editingId !== null}
              onChange={(e) => setAddDraft({ url: e.target.value })}
              onKeyDown={(e) => {
                if (e.key !== "Enter" || !canSubmitAddRow) return
                if (canSaveLink) void addLink()
                else if (canPasteAndSave) void pasteAndSave()
              }}
            />
            <Button
              type="button"
              className="h-11 shrink-0 px-5"
              disabled={!canSubmitAddRow}
              onClick={() =>
                void (hasUrl ? addLink() : pasteAndSave())
              }
            >
              {hasUrl ? "Salvar" : "Colar e salvar"}
            </Button>
          </div>
        </div>

        {error && <p className="text-sm text-red-600">{error}</p>}

        {loading ? (
          <p className="text-sm text-app-muted">Carregando links...</p>
        ) : (
          <WorkspaceDataTable
          columns={linkColumns}
          minWidth="640px"
          actionsWidth={WORKSPACE_TABLE_ACTIONS_WIDTH_WIDE}
        >
          <WorkspaceDataTableHeader columns={linkColumns} />
          {links.length === 0 && (
            <WorkspaceTableEmpty colSpan={linkColumns.length + 1}>
              Nenhum link salvo. Cole um link no campo acima para adicionar.
            </WorkspaceTableEmpty>
          )}
          <WorkspaceDataTableBody>
            {links.map((link) => {
              const editing = isEditing(link.id) && draft
              const row = editing ? draft : link
              return (
                <WorkspaceDataTableRow key={link.id}>
                  {linkColumns.map((col) => (
                    <WorkspaceTableCell
                      key={col.id}
                      inputCell={
                        col.id === "description" || !!(editing && col.renderEdit)
                      }
                    >
                      {editing && col.renderEdit
                        ? col.renderEdit(row, updateDraft)
                        : col.renderView(link)}
                    </WorkspaceTableCell>
                  ))}
                  <WorkspaceTableActions>
                    {editing ? (
                      <>
                        <LinkCopyButton url={row.url} disabled={saving} />
                        <WorkspaceTableIconButton
                          onClick={() => void saveEdit()}
                          disabled={saving}
                          title="Salvar"
                        >
                          <Check className="h-4 w-4" />
                        </WorkspaceTableIconButton>
                        <WorkspaceTableIconButton
                          onClick={cancelEdit}
                          disabled={saving}
                          title="Cancelar"
                        >
                          <X className="h-4 w-4" />
                        </WorkspaceTableIconButton>
                      </>
                    ) : (
                      <>
                        <LinkCopyButton
                          url={link.url}
                          disabled={editingId !== null || isRowBusy(link)}
                        />
                        <Link
                          href={`/explorar?fromLink=${encodeURIComponent(link.url)}`}
                          className="inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-md border border-app-border text-app-muted hover:text-app-fg"
                          title="Abrir no Explorar"
                        >
                          <Compass className="h-4 w-4" />
                        </Link>
                        <WorkspaceEditButton
                          onClick={() => startEdit(link)}
                          disabled={editingId !== null || isRowBusy(link)}
                        />
                        <WorkspaceTableIconButton
                          title="Excluir"
                          disabled={editingId !== null || link.id.startsWith("pending-")}
                          onClick={() => {
                            void deleteSavedLink(link.id, orgId).then(() => {
                              setLinks((prev) => prev.filter((row) => row.id !== link.id))
                            })
                          }}
                        >
                          <Trash2 className="h-4 w-4" />
                        </WorkspaceTableIconButton>
                      </>
                    )}
                  </WorkspaceTableActions>
                </WorkspaceDataTableRow>
              )
            })}
          </WorkspaceDataTableBody>
          </WorkspaceDataTable>
        )}
      </div>
    </WorkspacePage>
  )
}

// apps/web/src/lib/components/links/LinksClient.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { Check, Compass, Trash2, X } from "@lucide/svelte";
  import Button from "$lib/components/ui/Button.svelte";
  import Input from "$lib/components/ui/Input.svelte";
  import LinkCopyButton from "$lib/components/links/LinkCopyButton.svelte";
  import LinkTitleBlock from "$lib/components/links/LinkTitleBlock.svelte";
  import LinkUrlLine from "$lib/components/links/LinkUrlLine.svelte";
  import WorkspacePage from "$lib/components/workspace/WorkspacePage.svelte";
  import WorkspaceDataTable from "$lib/components/workspace/table/WorkspaceDataTable.svelte";
  import WorkspaceDataTableBody from "$lib/components/workspace/table/WorkspaceDataTableBody.svelte";
  import WorkspaceDataTableHeader from "$lib/components/workspace/table/WorkspaceDataTableHeader.svelte";
  import WorkspaceDataTableRow from "$lib/components/workspace/table/WorkspaceDataTableRow.svelte";
  import WorkspaceEditButton from "$lib/components/workspace/table/WorkspaceEditButton.svelte";
  import WorkspaceTableActions from "$lib/components/workspace/table/WorkspaceTableActions.svelte";
  import WorkspaceTableCell from "$lib/components/workspace/table/WorkspaceTableCell.svelte";
  import WorkspaceTableEmpty from "$lib/components/workspace/table/WorkspaceTableEmpty.svelte";
  import WorkspaceTableIconButton from "$lib/components/workspace/table/WorkspaceTableIconButton.svelte";
  import WorkspaceTableInput from "$lib/components/workspace/table/WorkspaceTableInput.svelte";
  import { getActiveOrganizationId } from "$lib/api/client";
  import {
    createSavedLink,
    deleteSavedLink,
    enrichSavedLink,
    fetchSavedLinks,
    updateSavedLink
  } from "$lib/workspace/client";
  import type { SavedLinkRow } from "$lib/workspace/saved-links-types";
  import { useInlineRowEdit } from "$lib/workspace/use-inline-row-edit.svelte";
  import { useEscapeToCancel } from "$lib/workspace/use-escape-to-cancel.svelte";
  import { WORKSPACE_TABLE_ACTIONS_WIDTH_WIDE, type WorkspaceTableColumn } from "$lib/workspace/workspace-table";

  const emptyAddDraft = { url: "" };

  const linkColumns: WorkspaceTableColumn[] = [
    { id: "title", header: "Link", width: "42%" },
    { id: "description", header: "Descrição", width: "46%" }
  ];

  let links = $state<SavedLinkRow[]>([]);
  let addDraft = $state({ ...emptyAddDraft });
  let error = $state<string | null>(null);
  let loading = $state(true);
  let saving = $state(false);
  let orgId = $state<string | null>(null);

  const rowEdit = useInlineRowEdit<SavedLinkRow>();

  const hasUrl = $derived(Boolean(addDraft.url.trim()));
  const canUseAddRow = $derived(!saving && rowEdit.editingId === null);
  const canSaveLink = $derived(hasUrl && canUseAddRow);
  const canPasteAndSave = $derived(!hasUrl && canUseAddRow);
  const canSubmitAddRow = $derived(canSaveLink || canPasteAndSave);

  function makePendingRow(url: string, pendingId: string): SavedLinkRow {
    const now = new Date().toISOString();
    return {
      id: pendingId,
      userId: null,
      orgId: null,
      title: "",
      url,
      description: null,
      createdAt: now,
      updatedAt: now,
      enriching: true
    };
  }

  function isRowBusy(link: SavedLinkRow) {
    return Boolean(link.enriching) || link.id.startsWith("pending-");
  }

  async function loadLinks() {
    loading = true;
    error = null;
    try {
      const data = await fetchSavedLinks(orgId);
      links = data.links;
    } catch (err) {
      error = err instanceof Error ? err.message : "Erro ao carregar links";
    } finally {
      loading = false;
    }
  }

  async function runEnrichment(linkId: string) {
    try {
      const { link } = await enrichSavedLink(linkId, orgId);
      links = links.map((row) =>
        row.id === linkId ? { ...link, enriching: false, enrichError: null } : row
      );
    } catch (err) {
      const message =
        err instanceof Error && err.name === "AbortError"
          ? "Enriquecimento demorou demais; você pode editar o título e a descrição."
          : err instanceof Error
            ? err.message
            : "Não foi possível enriquecer o link";
      links = links.map((row) =>
        row.id === linkId ? { ...row, enriching: false, enrichError: message } : row
      );
    }
  }

  async function saveEdit() {
    const draft = rowEdit.draft;
    const editingId = rowEdit.editingId;
    if (!draft || !editingId) return;
    saving = true;
    error = null;
    try {
      const { link } = await updateSavedLink(
        editingId,
        { title: draft.title, url: draft.url, description: draft.description },
        orgId
      );
      rowEdit.cancelEdit();
      links = links.map((row) =>
        row.id === editingId ? { ...link, enriching: false, enrichError: null } : row
      );
    } catch (err) {
      error = err instanceof Error ? err.message : "Erro ao salvar link";
    } finally {
      saving = false;
    }
  }

  async function addLink(urlOverride?: string) {
    const url = (urlOverride ?? addDraft.url).trim();
    if (!url) return;

    const pendingId = `pending-${crypto.randomUUID()}`;
    links = [makePendingRow(url, pendingId), ...links];
    addDraft = { ...emptyAddDraft };
    error = null;

    try {
      const { link } = await createSavedLink({ url }, orgId);
      links = links.map((row) =>
        row.id === pendingId ? { ...link, enriching: true, enrichError: null } : row
      );
      void runEnrichment(link.id);
    } catch (err) {
      links = links.filter((row) => row.id !== pendingId);
      error = err instanceof Error ? err.message : "Erro ao salvar link";
    }
  }

  async function pasteAndSave() {
    error = null;
    try {
      const text = await navigator.clipboard.readText();
      const url = text.trim();
      if (!url) {
        error = "Nada na área de transferência para salvar.";
        return;
      }
      addDraft = { url };
      await addLink(url);
    } catch {
      error =
        "Não foi possível ler a área de transferência. Permita o acesso ou cole o link manualmente.";
    }
  }

  function handleAddKeydown(event: KeyboardEvent) {
    if (event.key !== "Enter" || !canSubmitAddRow) return;
    if (canSaveLink) void addLink();
    else if (canPasteAndSave) void pasteAndSave();
  }

  function handleAddClick() {
    if (hasUrl) void addLink();
    else void pasteAndSave();
  }

  function handleCancelEdit() {
    rowEdit.cancelEdit();
  }

  useEscapeToCancel(() => rowEdit.editingId !== null, handleCancelEdit);

  onMount(() => {
    orgId = getActiveOrganizationId();
    void loadLinks();
    const onOrgChange = () => {
      orgId = getActiveOrganizationId();
      void loadLinks();
    };
    window.addEventListener("minha-casa:organization-context-change", onOrgChange);
    return () => window.removeEventListener("minha-casa:organization-context-change", onOrgChange);
  });
</script>

<WorkspacePage>
  <div class="-my-4">
    <div class="py-4">
      <div class="flex items-stretch gap-2">
        <Input
          type="text"
          class="h-11 flex-1 bg-white text-base dark:bg-white"
          placeholder="Cole aqui links, buscas com filtros, sites úteis e referências externas."
          bind:value={addDraft.url}
          disabled={saving || rowEdit.editingId !== null}
          onkeydown={handleAddKeydown}
        />
        <Button
          type="button"
          class="h-11 shrink-0 px-5"
          disabled={!canSubmitAddRow}
          onclick={handleAddClick}
        >
          {hasUrl ? "Salvar" : "Colar e salvar"}
        </Button>
      </div>
    </div>

    {#if error}
      <p class="text-sm text-red-600">{error}</p>
    {/if}

    {#if loading}
      <p class="text-sm text-app-muted">Carregando links...</p>
    {:else}
      <WorkspaceDataTable
        columns={linkColumns}
        minWidth="640px"
        actionsWidth={WORKSPACE_TABLE_ACTIONS_WIDTH_WIDE}
      >
        <WorkspaceDataTableHeader columns={linkColumns} />
        {#if links.length === 0}
          <WorkspaceTableEmpty colSpan={linkColumns.length + 1}>
            Nenhum link salvo. Cole um link no campo acima para adicionar.
          </WorkspaceTableEmpty>
        {/if}
        <WorkspaceDataTableBody>
          {#each links as link (link.id)}
            {@const editing = rowEdit.isEditing(link.id) && rowEdit.draft}
            <WorkspaceDataTableRow>
              <WorkspaceTableCell inputCell={Boolean(editing)}>
                {#if editing && rowEdit.draft}
                  <div class="flex min-w-0 flex-col gap-1.5">
                    <WorkspaceTableInput placeholder="Título" bind:value={rowEdit.draft.title} />
                    <WorkspaceTableInput placeholder="https://..." bind:value={rowEdit.draft.url} />
                  </div>
                {:else}
                  <div class="min-w-0">
                    <LinkTitleBlock title={link.title} url={link.url} enriching={link.enriching} />
                    <LinkUrlLine url={link.url} />
                  </div>
                {/if}
              </WorkspaceTableCell>
              <WorkspaceTableCell inputCell={Boolean(editing)}>
                {#if editing && rowEdit.draft}
                  <WorkspaceTableInput
                    placeholder="Descrição"
                    value={rowEdit.draft.description ?? ""}
                    oninput={(event) =>
                      rowEdit.updateDraft({ description: event.currentTarget.value })}
                  />
                {:else if link.enriching}
                  <span class="text-sm text-app-muted animate-pulse">Carregando…</span>
                {:else if link.enrichError}
                  <span class="block min-w-0 text-xs text-amber-700 whitespace-pre-wrap break-words">
                    {link.enrichError}
                  </span>
                {:else}
                  <span class="block min-w-0 whitespace-pre-wrap break-words text-app-fg leading-snug">
                    {link.description ?? ""}
                  </span>
                {/if}
              </WorkspaceTableCell>
              <WorkspaceTableActions>
                {#if editing && rowEdit.draft}
                  <LinkCopyButton url={rowEdit.draft.url} disabled={saving} />
                  <WorkspaceTableIconButton
                    onclick={() => void saveEdit()}
                    disabled={saving}
                    title="Salvar"
                    ariaLabel="Salvar"
                  >
                    <Check class="h-4 w-4" />
                  </WorkspaceTableIconButton>
                  <WorkspaceTableIconButton
                    onclick={handleCancelEdit}
                    disabled={saving}
                    title="Cancelar"
                    ariaLabel="Cancelar"
                  >
                    <X class="h-4 w-4" />
                  </WorkspaceTableIconButton>
                {:else}
                  <LinkCopyButton
                    url={link.url}
                    disabled={rowEdit.editingId !== null || isRowBusy(link)}
                  />
                  <a
                    href="/explorar?fromLink={encodeURIComponent(link.url)}"
                    class="inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-md border border-app-border text-app-muted hover:text-app-fg"
                    title="Abrir no Explorar"
                  >
                    <Compass class="h-4 w-4" />
                  </a>
                  <WorkspaceEditButton
                    onclick={() => rowEdit.startEdit(link)}
                    disabled={rowEdit.editingId !== null || isRowBusy(link)}
                  />
                  <WorkspaceTableIconButton
                    title="Excluir"
                    ariaLabel="Excluir"
                    disabled={rowEdit.editingId !== null || link.id.startsWith("pending-")}
                    onclick={() => {
                      void deleteSavedLink(link.id, orgId).then(() => {
                        links = links.filter((row) => row.id !== link.id);
                      });
                    }}
                  >
                    <Trash2 class="h-4 w-4" />
                  </WorkspaceTableIconButton>
                {/if}
              </WorkspaceTableActions>
            </WorkspaceDataTableRow>
          {/each}
        </WorkspaceDataTableBody>
      </WorkspaceDataTable>
    {/if}
  </div>
</WorkspacePage>
