// app/analise/analise-client.tsx
"use client"

import { Suspense, useMemo } from "react"
import Link from "next/link"
import { useSearchParams } from "next/navigation"
import { useCollections } from "@/app/anuncios/lib/use-collections"
import {
  WORKSPACE_CONTENT_CLASS,
  WORKSPACE_STACK_CLASS,
  WorkspaceLoadingState,
} from "@/app/components/workspace-ui"
import { useWorkspaceProfile } from "@/lib/workspace/use-workspace-profile"
import { AnaliseQuerySync } from "./components/analise-query-sync"
import { DeepAnalysisPanel } from "./components/deep-analysis-panel"
import { PropertyDossier } from "./components/property-dossier"

function AnaliseClientInner() {
  const { orgId } = useWorkspaceProfile()
  const searchParams = useSearchParams()
  const selectedListingId = searchParams.get("listing")
  const { listings, activeCollection, isLoadingListings } = useCollections()

  const sortedListings = useMemo(
    () =>
      [...listings]
        .filter((l) => !l.strikethrough)
        .sort((a, b) => (a.titulo ?? "").localeCompare(b.titulo ?? "", "pt-BR")),
    [listings]
  )

  const selectedListing = useMemo(() => {
    if (isLoadingListings) return null
    return (
      sortedListings.find((listing) => listing.id === selectedListingId) ||
      sortedListings[0] ||
      null
    )
  }, [isLoadingListings, selectedListingId, sortedListings])

  return (
    <div className="min-h-[calc(100vh-var(--nav-height,2.75rem))] bg-app-bg text-app-fg">
      <AnaliseQuerySync />

      <div className={`${WORKSPACE_CONTENT_CLASS} ${WORKSPACE_STACK_CLASS}`}>
        {!activeCollection ? (
          <p className="text-sm text-app-muted">
            Crie uma coleção em{" "}
            <Link href="/anuncios" className="font-medium text-app-fg underline">
              Anúncios
            </Link>{" "}
            para começar.
          </p>
        ) : isLoadingListings ? (
          <p className="text-sm text-app-muted">Carregando imóveis...</p>
        ) : sortedListings.length === 0 ? (
          <p className="text-sm text-app-muted">
            Nenhum imóvel nesta coleção. Adicione anúncios em{" "}
            <Link href="/anuncios" className="underline">
              Anúncios
            </Link>
            .
          </p>
        ) : !selectedListing ? (
          <p className="text-sm text-app-muted">Selecione um imóvel acima.</p>
        ) : (
          <>
            <PropertyDossier
              listing={selectedListing}
              collectionId={activeCollection.id}
              orgId={orgId}
            />
            <DeepAnalysisPanel listing={selectedListing} orgId={orgId} />
          </>
        )}
      </div>
    </div>
  )
}

export function AnaliseClient() {
  return (
    <Suspense fallback={<WorkspaceLoadingState />}>
      <AnaliseClientInner />
    </Suspense>
  )
}

// apps/web/src/lib/components/analise/AnaliseClient.svelte
<script lang="ts">
  import { page } from "$app/state";
  import AnaliseQuerySync from "$lib/components/analise/AnaliseQuerySync.svelte";
  import WorkspaceListingQuerySync from "$lib/components/workspace/WorkspaceListingQuerySync.svelte";
  import AnaliseTabbedDossier from "$lib/components/analise/AnaliseTabbedDossier.svelte";
  import { getCollectionsContext } from "$lib/collections-context.svelte";
  import { getActiveOrganizationId } from "$lib/api/client";
  import { cn } from "$lib/utils";
  import { WORKSPACE_CONTENT_CLASS, WORKSPACE_STACK_CLASS } from "$lib/workspace-chrome";

  const ctx = getCollectionsContext();

  const selectedListingId = $derived(page.url.searchParams.get("listing"));
  const orgId = $derived(getActiveOrganizationId());

  const sortedListings = $derived(
    [...ctx.listings]
      .filter((listing) => !listing.strikethrough)
      .sort((a, b) => (a.titulo ?? "").localeCompare(b.titulo ?? "", "pt-BR"))
  );

  const selectedListing = $derived.by(() => {
    if (ctx.isLoadingListings) return null;
    return (
      sortedListings.find((listing) => listing.id === selectedListingId) ||
      sortedListings[0] ||
      null
    );
  });
</script>

<div class="min-h-[calc(100vh-var(--nav-height,2.75rem))] bg-app-bg text-app-fg">
  <AnaliseQuerySync />
  <WorkspaceListingQuerySync />

  <div class={cn(WORKSPACE_CONTENT_CLASS, WORKSPACE_STACK_CLASS, "min-w-0")}>
    {#if !ctx.activeCollection}
      <p class="text-sm text-app-muted">
        Crie uma coleção em
        <a href="/anuncios" class="font-medium text-app-fg underline">Anúncios</a>
        para começar.
      </p>
    {:else if ctx.isLoadingListings}
      <p class="text-sm text-app-muted">Carregando imóveis...</p>
    {:else if sortedListings.length === 0}
      <p class="text-sm text-app-muted">
        Nenhum imóvel nesta coleção. Adicione anúncios em
        <a href="/anuncios" class="underline">Anúncios</a>.
      </p>
    {:else if !selectedListing}
      <p class="text-sm text-app-muted">Selecione um imóvel acima.</p>
    {:else}
      <AnaliseTabbedDossier
        listing={selectedListing}
        collectionId={ctx.activeCollection.id}
        {orgId}
      />
    {/if}
  </div>
</div>
