// app/analise/components/analise-query-sync.tsx
"use client"

import { useEffect } from "react"
import { useSearchParams } from "next/navigation"
import { useCollections } from "@/app/anuncios/lib/use-collections"

export function AnaliseQuerySync() {
  const searchParams = useSearchParams()
  const collectionId = searchParams.get("collection")
  const { collections, setActiveCollection } = useCollections()

  useEffect(() => {
    if (!collectionId || collections.length === 0) return
    const match = collections.find((c) => c.id === collectionId)
    if (match) setActiveCollection(match)
  }, [collectionId, collections, setActiveCollection])

  return null
}

// apps/web/src/lib/components/analise/AnaliseQuerySync.svelte
<script lang="ts">
  import { page } from "$app/stores";
  import { getCollectionsContext } from "$lib/collections-context.svelte";

  const ctx = getCollectionsContext();

  const collectionId = $derived($page.url.searchParams.get("collection"));

  $effect(() => {
    if (!collectionId || ctx.collections.length === 0) return;
    const match = ctx.collections.find((collection) => collection.id === collectionId);
    if (match) ctx.setActiveCollection(match);
  });
</script>
