// apps/web/src/lib/components/financiamento/ResultsTable.svelte
<script lang="ts">
  import { ArrowDown, ArrowUp, CircleCheck, Info } from "@lucide/svelte";
  import EstrategiaBadge from "$lib/components/financiamento/EstrategiaBadge.svelte";
  import Tooltip from "$lib/components/ui/Tooltip.svelte";
  import {
    toggleSort,
    sortCenarios,
    type ResultsSortKey,
    type ResultsSortState
  } from "$lib/components/financiamento/results-table-sort";
  import {
    TOOLTIPS,
    formatCurrencyCompact,
    formatPercent,
    type CenarioCompleto
  } from "$lib/financiamento/calculations";
  import { cn } from "$lib/utils";

  let {
    cenarios,
    onSelectCenario
  }: {
    cenarios: CenarioCompleto[];
    onSelectCenario?: (cenario: CenarioCompleto) => void;
  } = $props();

  let sort = $state<ResultsSortState>({ key: "custoTotal", direction: "asc" });

  const sortedCenarios = $derived(sortCenarios(cenarios, sort));

  function handleSort(key: ResultsSortKey) {
    sort = toggleSort(sort, key);
  }

  const thClass =
    "sticky top-0 z-20 border-b border-app-border bg-app-surface px-3 py-2 text-left text-xs font-medium text-app-muted";
  const tdClass = "border-b border-app-border px-3 py-2 align-middle";
</script>

{#snippet sortableHeader(label: string, sortKey: ResultsSortKey, tooltip?: string)}
  {@const isActive = sort.key === sortKey}
  {@const isAsc = isActive && sort.direction === "asc"}
  <th class={cn(thClass, "transition-colors hover:bg-app-surface-muted/30")}>
    <div class="flex items-center gap-1">
      <button
        type="button"
        class="flex items-center gap-1 text-left"
        onclick={() => handleSort(sortKey)}
      >
        <span>{label}</span>
        {#if isActive}
          {#if isAsc}
            <ArrowUp class="size-3 text-app-accent" />
          {:else}
            <ArrowDown class="size-3 text-app-accent" />
          {/if}
        {/if}
      </button>
      {#if tooltip}
        <Tooltip side="top">
          {#snippet trigger()}
            <button
              type="button"
              class="inline-flex text-app-subtle hover:text-app-accent"
              aria-label="Mais informações sobre {label}"
            >
              <Info class="size-3" />
            </button>
          {/snippet}
          <p class="text-xs">{tooltip}</p>
        </Tooltip>
      {/if}
    </div>
  </th>
{/snippet}

{#snippet aprovacaoIndicator(dentroDoLimite: boolean)}
  <Tooltip side="top">
    {#snippet trigger()}
      <span
        class={cn(
          "inline-block size-2 rounded-full",
          dentroDoLimite ? "bg-green" : "bg-salmon"
        )}
        role="img"
        aria-label={dentroDoLimite ? "Dentro do limite" : "Acima do limite"}
      ></span>
    {/snippet}
    <p class="text-xs">
      {dentroDoLimite
        ? "Dentro do limite de 30% de comprometimento"
        : "Acima do limite - pode dificultar aprovação"}
    </p>
  </Tooltip>
{/snippet}

<div class="max-h-[min(70vh,32rem)] overflow-auto">
  <table class="w-full min-w-[56rem] border-collapse text-sm">
    <thead>
      <tr class="hover:bg-transparent">
        <th class={cn(thClass, "sticky left-0 z-30 w-8")}></th>
        {@render sortableHeader("Casa", "valorImovel", TOOLTIPS.valorImovel)}
        {@render sortableHeader("Apto", "valorApartamento", TOOLTIPS.valorApartamento)}
        <th class={thClass}>Estratégia</th>
        {@render sortableHeader("Financiado", "valorFinanciado", "Valor total a ser financiado")}
        {@render sortableHeader(
          "Total/mês",
          "parcela",
          "Aporte extra mensal + primeira parcela (maior valor no SAC)"
        )}
        {@render sortableHeader("Compr.", "comprometimento", TOOLTIPS.comprometimento)}
        {@render sortableHeader("Prazo", "prazoReal", "Prazo real com amortização extra")}
        {@render sortableHeader(
          "Juros",
          "jurosOtimizado",
          "Total de juros que você vai pagar (com amortização extra)"
        )}
        {@render sortableHeader(
          "Custo Total",
          "custoTotal",
          "Custo total do imóvel (valor + juros + fechamento)"
        )}
      </tr>
    </thead>
    <tbody>
      {#each sortedCenarios as cenario (cenario.id)}
        <tr
          class={cn(
            "border-app-border transition-colors",
            onSelectCenario && "cursor-pointer",
            cenario.isBest
              ? "bg-app-action/10 hover:bg-app-action-hover/20"
              : "hover:bg-app-surface-muted/30"
          )}
          onclick={onSelectCenario ? () => onSelectCenario(cenario) : undefined}
        >
          <td class={cn(tdClass, "sticky left-0 z-10 w-8 bg-inherit")}>
            {#if cenario.isBest}
              <CircleCheck class="size-4 text-app-accent" aria-label="Melhor cenário" />
            {/if}
          </td>
          <td class={cn(tdClass, "font-mono text-sm text-app-accent")}>
            {formatCurrencyCompact(cenario.valorImovel)}
          </td>
          <td class={cn(tdClass, "font-mono text-sm text-salmon")}>
            {formatCurrencyCompact(
              cenario.estrategia === "permuta"
                ? cenario.financiamento.valorApartamentoUsado
                : cenario.valorApartamento
            )}
          </td>
          <td class={tdClass}>
            <EstrategiaBadge estrategia={cenario.estrategia} variant="inline" />
          </td>
          <td class={cn(tdClass, "font-mono text-sm")}>
            {formatCurrencyCompact(cenario.financiamento.valorFinanciado)}
          </td>
          <td class={cn(tdClass, "font-mono text-sm font-bold text-app-accent")}>
            {formatCurrencyCompact(
              cenario.aporteExtra + cenario.tabelaPadrao.primeiraParcelar
            )}
          </td>
          <td class={tdClass}>
            <div class="flex items-center gap-2">
              {@render aprovacaoIndicator(cenario.comprometimento.dentroDoLimite)}
              <span
                class={cn(
                  "font-mono text-xs",
                  cenario.comprometimento.dentroDoLimite ? "text-green" : "text-salmon"
                )}
              >
                {formatPercent(cenario.comprometimento.percentual)}
              </span>
            </div>
          </td>
          <td class={cn(tdClass, "font-mono text-sm text-app-accent")}>
            {(cenario.cenarioOtimizado.prazoReal / 12).toFixed(1)}a
          </td>
          <td class={cn(tdClass, "font-mono text-sm font-bold text-salmon")}>
            {formatCurrencyCompact(cenario.cenarioOtimizado.totalJuros)}
          </td>
          <td class={cn(tdClass, "font-mono text-sm font-bold")}>
            {formatCurrencyCompact(cenario.custoTotalOtimizado)}
          </td>
        </tr>
      {/each}
    </tbody>
  </table>
</div>

// app/casa/components/results-table.tsx
"use client"

import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip"
import { cn } from "@/lib/utils"
import {
  ArrowDownIcon,
  ArrowUpIcon,
  CheckCircledIcon,
  InfoCircledIcon,
} from "@radix-ui/react-icons"
import { useState } from "react"

import {
  formatCurrency,
  formatCurrencyCompact,
  formatPercent,
  generateTooltips,
  type CenarioCompleto,
  type ParcelaDetalhe,
} from "./utils/calculations"

// Generate default tooltips
const defaultTooltips = generateTooltips()

// ============================================================================
// TYPES
// ============================================================================

type SortKey =
  | "valorImovel"
  | "valorApartamento"
  | "valorFinanciado"
  | "parcela"
  | "comprometimento"
  | "prazoReal"
  | "jurosOtimizado"
  | "custoTotal"

type SortDirection = "asc" | "desc"

interface SortState {
  key: SortKey
  direction: SortDirection
}

interface SortableHeaderProps {
  label: string
  tooltip?: string
  sortKey: SortKey
  currentSort: SortState
  onSort: (key: SortKey) => void
}

interface EstrategiaBadgeInlineProps {
  estrategia: "permuta" | "venda_posterior"
}

interface AprovacaoIndicatorProps {
  dentroDoLimite: boolean
}

interface ResultsTableProps {
  cenarios: CenarioCompleto[]
  onSelectCenario?: (cenario: CenarioCompleto) => void
}

interface AmortizationSampleTableProps {
  parcelas: ParcelaDetalhe[] | null | undefined
}

interface SummaryComparisonProps {
  cenarios: CenarioCompleto[] | null | undefined
}

interface StatCard {
  label: string
  value: string
  icon: string
  highlight?: boolean
  variant?: "salmon"
}

// ============================================================================
// HELPER COMPONENTS
// ============================================================================

/**
 * Header com tooltip e sorting
 */
const SortableHeader = ({
  label,
  tooltip,
  sortKey,
  currentSort,
  onSort,
}: SortableHeaderProps) => {
  const isActive = currentSort?.key === sortKey
  const isAsc = isActive && currentSort?.direction === "asc"

  return (
    <TableHead
      className="cursor-pointer hover:bg-app-surface-muted/30 transition-colors"
      onClick={() => onSort(sortKey)}
    >
      <div className="flex items-center gap-1">
        <span>{label}</span>
        {tooltip && (
          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger asChild>
                <InfoCircledIcon className="h-3 w-3 text-app-subtle" />
              </TooltipTrigger>
              <TooltipContent className="max-w-xs">
                <p className="text-xs">{tooltip}</p>
              </TooltipContent>
            </Tooltip>
          </TooltipProvider>
        )}
        {isActive && (
          isAsc ? (
            <ArrowUpIcon className="h-3 w-3 text-app-accent" />
          ) : (
            <ArrowDownIcon className="h-3 w-3 text-app-accent" />
          )
        )}
      </div>
    </TableHead>
  )
}

/**
 * Badge de estratégia inline
 */
const EstrategiaBadgeInline = ({ estrategia }: EstrategiaBadgeInlineProps) => {
  const config = {
    permuta: {
      label: "Permuta",
      className: "text-salmon",
    },
    venda_posterior: {
      label: "Venda",
      className: "text-green",
    },
  }

  const { label, className } = config[estrategia] || config.permuta

  return <span className={cn("text-xs font-medium", className)}>{label}</span>
}

/**
 * Indicador de status de aprovação
 */
const AprovacaoIndicator = ({ dentroDoLimite }: AprovacaoIndicatorProps) => {
  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <span
            className={cn(
              "inline-block w-2 h-2 rounded-full",
              dentroDoLimite ? "bg-green" : "bg-salmon"
            )}
          />
        </TooltipTrigger>
        <TooltipContent>
          <p className="text-xs">
            {dentroDoLimite
              ? "Dentro do limite de 30% de comprometimento"
              : "Acima do limite - pode dificultar aprovação"}
          </p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  )
}

// ============================================================================
// TABLE COMPONENTS
// ============================================================================

/**
 * Tabela comparativa de cenários
 */
export const ResultsTable = ({ cenarios, onSelectCenario }: ResultsTableProps) => {
  const [sort, setSort] = useState<SortState>({ key: "custoTotal", direction: "asc" })

  const handleSort = (key: SortKey) => {
    setSort((prev) => ({
      key,
      direction: prev.key === key && prev.direction === "desc" ? "asc" : "desc",
    }))
  }

  // Ordenar cenários
  const sortedCenarios = [...cenarios].sort((a, b) => {
    const getValue = (cenario: CenarioCompleto, key: SortKey): number => {
      const paths: Record<SortKey, number> = {
        valorImovel: cenario.valorImovel,
        valorApartamento: cenario.valorApartamento,
        valorFinanciado: cenario.financiamento.valorFinanciado,
        parcela: cenario.tabelaPadrao.primeiraParcelar,
        comprometimento: cenario.comprometimento.percentual,
        prazoReal: cenario.cenarioOtimizado.prazoReal,
        jurosOtimizado: cenario.cenarioOtimizado.totalJuros,
        custoTotal: cenario.custoTotalOtimizado,
      }
      return paths[key] ?? 0
    }

    const aVal = getValue(a, sort.key)
    const bVal = getValue(b, sort.key)

    return sort.direction === "asc" ? aVal - bVal : bVal - aVal
  })

  // Get best cenario for dynamic tooltip (currently using defaultTooltips)
  // const bestCenario = cenarios.find((c) => c.isBest) || cenarios[0]
  // const dynamicTooltips = bestCenario
  //   ? generateTooltips({
  //       aporteExtra: bestCenario.aporteExtra,
  //       economiaJuros: bestCenario.economiaJuros,
  //     })
  //   : defaultTooltips

  return (
    <div className="overflow-x-auto">
      <Table>
        <TableHeader>
          <TableRow className="border-app-border hover:bg-transparent">
            <TableHead className="w-8"></TableHead>
            <SortableHeader
              label="Casa"
              tooltip={defaultTooltips.valorImovel}
              sortKey="valorImovel"
              currentSort={sort}
              onSort={handleSort}
            />
            <SortableHeader
              label="Apto"
              tooltip={defaultTooltips.valorApartamento}
              sortKey="valorApartamento"
              currentSort={sort}
              onSort={handleSort}
            />
            <TableHead>Estratégia</TableHead>
            <SortableHeader
              label="Financiado"
              tooltip="Valor total a ser financiado"
              sortKey="valorFinanciado"
              currentSort={sort}
              onSort={handleSort}
            />
            <SortableHeader
              label="Total/mês"
              tooltip="Aporte extra mensal + primeira parcela (maior valor no SAC)"
              sortKey="parcela"
              currentSort={sort}
              onSort={handleSort}
            />
            <SortableHeader
              label="Compr."
              tooltip={defaultTooltips.comprometimento}
              sortKey="comprometimento"
              currentSort={sort}
              onSort={handleSort}
            />
            <SortableHeader
              label="Prazo"
              tooltip="Prazo real com amortização extra"
              sortKey="prazoReal"
              currentSort={sort}
              onSort={handleSort}
            />
            <SortableHeader
              label="Juros"
              tooltip="Total de juros que você vai pagar (com amortização extra)"
              sortKey="jurosOtimizado"
              currentSort={sort}
              onSort={handleSort}
            />
            <SortableHeader
              label="Custo Total"
              tooltip="Custo total do imóvel (valor + juros + fechamento)"
              sortKey="custoTotal"
              currentSort={sort}
              onSort={handleSort}
            />
          </TableRow>
        </TableHeader>
        <TableBody>
          {sortedCenarios.map((cenario) => (
            <TableRow
              key={cenario.id}
              className={cn(
                "border-app-border cursor-pointer transition-colors",
                cenario.isBest
                  ? "bg-app-action/10 hover:bg-app-action-hover/20"
                  : "hover:bg-app-surface-muted/30"
              )}
              onClick={() => onSelectCenario?.(cenario)}
            >
              <TableCell className="w-8">
                {cenario.isBest && (
                  <CheckCircledIcon className="h-4 w-4 text-app-accent" />
                )}
              </TableCell>
              <TableCell className="font-mono text-sm text-app-accent">
                {formatCurrencyCompact(cenario.valorImovel)}
              </TableCell>
              <TableCell className="font-mono text-sm text-salmon">
                {formatCurrencyCompact(
                  cenario.estrategia === "permuta"
                    ? cenario.financiamento.valorApartamentoUsado
                    : cenario.valorApartamento
                )}
              </TableCell>
              <TableCell>
                <EstrategiaBadgeInline estrategia={cenario.estrategia} />
              </TableCell>
              <TableCell className="font-mono text-sm">
                {formatCurrencyCompact(cenario.financiamento.valorFinanciado)}
              </TableCell>
              <TableCell className="font-mono text-sm text-app-accent font-bold">
                {formatCurrencyCompact(
                  cenario.aporteExtra + cenario.tabelaPadrao.primeiraParcelar
                )}
              </TableCell>
              <TableCell>
                <div className="flex items-center gap-2">
                  <AprovacaoIndicator
                    dentroDoLimite={cenario.comprometimento.dentroDoLimite}
                  />
                  <span
                    className={cn(
                      "font-mono text-xs",
                      cenario.comprometimento.dentroDoLimite
                        ? "text-green"
                        : "text-salmon"
                    )}
                  >
                    {formatPercent(cenario.comprometimento.percentual)}
                  </span>
                </div>
              </TableCell>
              <TableCell className="font-mono text-sm text-app-accent">
                {(cenario.cenarioOtimizado.prazoReal / 12).toFixed(1)}a
              </TableCell>
              <TableCell className="font-mono text-sm text-salmon font-bold">
                {formatCurrencyCompact(cenario.cenarioOtimizado.totalJuros)}
              </TableCell>
              <TableCell className="font-mono text-sm font-bold">
                {formatCurrencyCompact(cenario.custoTotalOtimizado)}
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  )
}

/**
 * Tabela de parcelas amostra
 */
export const AmortizationSampleTable = ({ parcelas }: AmortizationSampleTableProps) => {
  if (!parcelas || parcelas.length === 0) return null

  return (
    <div className="overflow-x-auto">
      <Table>
        <TableHeader>
          <TableRow className="border-app-border">
            <TableHead>Mês</TableHead>
            <TableHead>Saldo Devedor</TableHead>
            <TableHead>Amortização</TableHead>
            <TableHead>Juros</TableHead>
            <TableHead>Prestação</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {parcelas.map((parcela) => (
            <TableRow key={parcela.mes} className="border-app-border">
              <TableCell className="font-mono text-sm">
                {parcela.mes}
              </TableCell>
              <TableCell className="font-mono text-sm">
                {formatCurrency(parcela.saldoDevedor)}
              </TableCell>
              <TableCell className="font-mono text-sm text-app-accent">
                {formatCurrency(parcela.amortizacao)}
              </TableCell>
              <TableCell className="font-mono text-sm text-salmon">
                {formatCurrency(parcela.juros)}
              </TableCell>
              <TableCell className="font-mono text-sm font-bold">
                {formatCurrency(parcela.prestacao)}
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  )
}

/**
 * Resumo comparativo de cenários
 */
export const SummaryComparison = ({ cenarios }: SummaryComparisonProps) => {
  if (!cenarios || cenarios.length === 0) return null

  // Calcular estatísticas
  const stats = {
    menorFinanciamento: Math.min(
      ...cenarios.map((c) => c.financiamento.valorFinanciado)
    ),
    maiorFinanciamento: Math.max(
      ...cenarios.map((c) => c.financiamento.valorFinanciado)
    ),
    menorParcela: Math.min(
      ...cenarios.map((c) => c.tabelaPadrao.primeiraParcelar)
    ),
    maiorParcela: Math.max(
      ...cenarios.map((c) => c.tabelaPadrao.primeiraParcelar)
    ),
    menorJuros: Math.min(
      ...cenarios.map((c) => c.cenarioOtimizado.totalJuros)
    ),
    maiorJuros: Math.max(
      ...cenarios.map((c) => c.cenarioOtimizado.totalJuros)
    ),
    menorPrazo: Math.min(
      ...cenarios.map((c) => c.cenarioOtimizado.prazoReal)
    ),
    maiorPrazo: Math.max(
      ...cenarios.map((c) => c.cenarioOtimizado.prazoReal)
    ),
    maiorEconomia: Math.max(...cenarios.map((c) => c.economiaJuros)),
    cenariosAprovados: cenarios.filter(
      (c) => c.comprometimento.dentroDoLimite
    ).length,
  }

  const statCards: StatCard[] = [
    {
      label: "Range Financiamento",
      value: `${formatCurrencyCompact(stats.menorFinanciamento)} - ${formatCurrencyCompact(stats.maiorFinanciamento)}`,
      icon: "💰",
    },
    {
      label: "Range Parcela",
      value: `${formatCurrencyCompact(stats.menorParcela)} - ${formatCurrencyCompact(stats.maiorParcela)}`,
      icon: "📊",
    },
    {
      label: "💸 Juros a Pagar",
      value: `${formatCurrencyCompact(stats.menorJuros)} - ${formatCurrencyCompact(stats.maiorJuros)}`,
      icon: "",
      variant: "salmon",
    },
    {
      label: "Range Prazo (Otim.)",
      value: `${(stats.menorPrazo / 12).toFixed(1)} - ${(stats.maiorPrazo / 12).toFixed(1)} anos`,
      icon: "⏱️",
    },
    {
      label: "💚 Maior Economia",
      value: formatCurrencyCompact(stats.maiorEconomia),
      icon: "",
      highlight: true,
    },
    {
      label: "Aprovação Crédito",
      value: `${stats.cenariosAprovados}/${cenarios.length} cenários`,
      icon: stats.cenariosAprovados === cenarios.length ? "✅" : "⚠️",
    },
  ]

  return (
    <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
      {statCards.map(({ label, value, icon, highlight, variant }) => (
        <div
          key={label}
          className={cn(
            "bg-app-surface-muted border border-app-border rounded-lg p-3",
            highlight && "border-green bg-green/5",
            variant === "salmon" && "border-salmon bg-salmon/5"
          )}
        >
          <div className="flex items-center gap-2 mb-1">
            {icon && <span className="text-lg">{icon}</span>}
            <span className={cn(
              "text-xs",
              variant === "salmon" ? "text-salmon" : "text-app-muted"
            )}>{label}</span>
          </div>
          <span
            className={cn(
              "text-sm font-mono font-bold",
              highlight && "text-green",
              variant === "salmon" && "text-salmon",
              !highlight && variant !== "salmon" && "text-app-fg"
            )}
          >
            {value}
          </span>
        </div>
      ))}
    </div>
  )
}
