// apps/web/src/lib/components/financiamento/ScenarioCard.svelte
<script lang="ts">
  import { CircleCheck } from "@lucide/svelte";
  import Card from "$lib/components/ui/Card.svelte";
  import ComprometimentoIndicator from "$lib/components/financiamento/ComprometimentoIndicator.svelte";
  import EstrategiaBadge from "$lib/components/financiamento/EstrategiaBadge.svelte";
  import ScenarioDataRow from "$lib/components/financiamento/ScenarioDataRow.svelte";
  import Tooltip from "$lib/components/ui/Tooltip.svelte";
  import {
    formatCurrency,
    formatCurrencyCompact,
    formatPercent,
    generateTooltips,
    type CenarioCompleto
  } from "$lib/financiamento/calculations";
  import { cn } from "$lib/utils";

  let {
    cenario,
    isExpanded = false
  }: {
    cenario: CenarioCompleto;
    isExpanded?: boolean;
  } = $props();

  const tooltips = $derived(
    generateTooltips({
      aporteExtra: cenario.aporteExtra,
      economiaJuros: cenario.economiaJuros
    })
  );
</script>

{#snippet aporteSnippet()}
  <span class="font-bold text-app-accent">+{formatCurrency(cenario.aporteExtra)}</span>
{/snippet}

{#snippet economiaSnippet()}
  <span class="text-green">
    {formatCurrency(cenario.economiaJuros)} ({formatPercent(cenario.economiaPercentual)})
  </span>
{/snippet}

<Card
  class={cn(
    "border-app-border bg-app-surface-muted transition-all hover:border-app-action/50",
    cenario.isBest && "border-app-action ring-1 ring-primary/30"
  )}
>
  <div class="flex flex-col space-y-1.5 p-6 pb-3">
    <div class="flex items-start justify-between gap-2">
      <div class="space-y-1">
        <h3 class="flex items-center gap-2 text-base font-semibold leading-none tracking-tight">
          <span class="text-app-accent">{formatCurrencyCompact(cenario.valorImovel)}</span>
          <span class="text-app-subtle">+</span>
          <span class="text-salmon">
            Seu imóvel {formatCurrencyCompact(cenario.valorApartamento)}
          </span>
        </h3>
        <EstrategiaBadge estrategia={cenario.estrategia} />
      </div>
      {#if cenario.isBest}
        <Tooltip side="top">
          {#snippet trigger()}
            <div
              class="flex items-center gap-1 rounded-md bg-app-action/20 px-2 py-1 text-xs text-app-accent"
            >
              <CircleCheck class="size-4" />
              Melhor
            </div>
          {/snippet}
          <p class="text-xs">Cenário com menor custo total de juros</p>
        </Tooltip>
      {/if}
    </div>
  </div>

  <div class="space-y-4 p-6 pt-0">
    <div class="space-y-1">
      <h4 class="text-xs font-semibold uppercase tracking-wider text-app-muted">Financiamento</h4>
      <ScenarioDataRow
        label="Valor Financiado"
        value={formatCurrency(cenario.financiamento.valorFinanciado)}
        tooltip="Valor total a ser financiado após entrada e/ou permuta."
      />
      <ScenarioDataRow
        label="Entrada sem seu imóvel"
        value={formatCurrency(cenario.financiamento.entradaDinheiro)}
        tooltip="Valor em dinheiro da entrada, sem incluir o seu imóvel."
      />
      {#if cenario.estrategia === "permuta"}
        <ScenarioDataRow
          label="Seu imóvel na Permuta"
          value={formatCurrency(cenario.financiamento.valorApartamentoUsado)}
          tooltip={`Valor aceito do seu imóvel na permuta: ${formatCurrency(cenario.financiamento.valorApartamentoUsado)}.`}
          class="text-salmon"
        />
      {/if}
      <ScenarioDataRow
        label="Entrada Total"
        value={formatCurrency(cenario.financiamento.entradaTotal)}
        tooltip="Soma de dinheiro + valor do apartamento (se permuta)."
      />
    </div>

    <div class="space-y-1 border-t border-app-border pt-2">
      <h4 class="text-xs font-semibold uppercase tracking-wider text-app-muted">Parcelas (SAC)</h4>
      <ScenarioDataRow
        label="Primeira Parcela"
        value={formatCurrency(cenario.tabelaPadrao.primeiraParcelar)}
        tooltip={`Parcela mais alta do financiamento (início do SAC): ${formatCurrency(cenario.tabelaPadrao.primeiraParcelar)}.`}
        highlight
      />
      <ScenarioDataRow
        label="Última Parcela"
        value={formatCurrency(cenario.tabelaPadrao.ultimaParcela)}
        tooltip={`Parcela mais baixa (fim do SAC): ${formatCurrency(cenario.tabelaPadrao.ultimaParcela)}.`}
      />
      <div class="pt-1">
        <span class="text-xs text-app-muted">Comprometimento Renda</span>
        <ComprometimentoIndicator comprometimento={cenario.comprometimento} />
      </div>
    </div>

    <div class="space-y-1 border-t border-app-border pt-2">
      <h4 class="text-xs font-semibold uppercase tracking-wider text-app-accent">
        Com Amortização Extra
      </h4>
      <ScenarioDataRow
        label="📈 Aporte Extra/mês"
        tooltip={tooltips.aporteExtra}
        highlight
        valueContent={aporteSnippet}
      />
      <ScenarioDataRow
        label="1ª Parcela + Amort. Extra"
        value={formatCurrency(
          cenario.tabelaPadrao.primeiraParcelar + cenario.aporteExtra
        )}
        tooltip={`Total da primeira parcela incluindo amortização extra: ${formatCurrency(cenario.tabelaPadrao.primeiraParcelar)} (parcela) + ${formatCurrency(cenario.aporteExtra)} (extra) = ${formatCurrency(cenario.tabelaPadrao.primeiraParcelar + cenario.aporteExtra)}.`}
        highlight
      />
      <ScenarioDataRow
        label="Prazo Real"
        value={`${cenario.cenarioOtimizado.prazoReal} meses (${(cenario.cenarioOtimizado.prazoReal / 12).toFixed(1)} anos)`}
        tooltip={`Tempo real para quitar com aportes de ${formatCurrency(cenario.aporteExtra)}/mês.`}
      />
      <ScenarioDataRow
        label="Economia de Tempo"
        value={`${cenario.cenarioOtimizado.mesesEconomizados} meses (${cenario.cenarioOtimizado.anosEconomizados} anos)`}
        tooltip={`Você economiza ${cenario.cenarioOtimizado.mesesEconomizados} meses (${cenario.cenarioOtimizado.anosEconomizados} anos) com amortização acelerada.`}
      />
    </div>

    <div class="space-y-1 border-t border-app-border pt-2">
      <h4 class="text-xs font-semibold uppercase tracking-wider text-app-muted">Custos de Juros</h4>
      <ScenarioDataRow
        label="Juros (Padrão)"
        value={formatCurrency(cenario.tabelaPadrao.totalJuros)}
        tooltip={`Total de juros sem amortização extra: ${formatCurrency(cenario.tabelaPadrao.totalJuros)}.`}
      />
      <ScenarioDataRow
        label="Juros (Otimizado)"
        value={formatCurrency(cenario.cenarioOtimizado.totalJuros)}
        tooltip={tooltips.economiaJuros}
        highlight
      />
      <ScenarioDataRow
        label="Economia"
        tooltip={`Economia total: ${formatCurrency(cenario.economiaJuros)} (${formatPercent(cenario.economiaPercentual)} dos juros).`}
        valueContent={economiaSnippet}
      />
    </div>

    {#if isExpanded}
      <div class="space-y-1 border-t border-app-border pt-2">
        <h4 class="text-xs font-semibold uppercase tracking-wider text-app-muted">
          Custos de Fechamento
        </h4>
        <ScenarioDataRow
          label="ITBI"
          value={formatCurrency(cenario.custosFechamento.itbi.total)}
          tooltip={tooltips.itbi}
        />
        <ScenarioDataRow
          label="Cartório/Registro"
          value={formatCurrency(cenario.custosFechamento.cartorio.total)}
          tooltip={`Custos de cartório: ${formatCurrency(cenario.custosFechamento.cartorio.total)}.`}
        />
        <ScenarioDataRow
          label="Total Fechamento"
          value={formatCurrency(cenario.custosFechamento.total)}
        />
      </div>
    {/if}

    <div
      class="-mx-4 space-y-1 rounded-b-lg border-t border-app-action/30 bg-app-action/5 px-4 py-2"
    >
      <h4 class="text-xs font-semibold uppercase tracking-wider text-app-accent">
        Custo Total do Imóvel
      </h4>
      <ScenarioDataRow
        label="Sem Amortização Extra"
        value={formatCurrency(cenario.custoTotalPadrao)}
        class="text-app-subtle"
      />
      <ScenarioDataRow
        label="Com Amortização Extra"
        value={formatCurrency(cenario.custoTotalOtimizado)}
        highlight
      />
      <div class="flex items-center justify-between pt-1">
        <span class="text-xs text-app-muted">CET Estimado</span>
        <Tooltip side="top">
          {#snippet trigger()}
            <span class="cursor-help font-mono text-sm text-salmon">
              {formatPercent(cenario.cetEstimado)} a.a.
            </span>
          {/snippet}
          <p class="max-w-xs text-xs">{tooltips.cetEstimado}</p>
        </Tooltip>
      </div>
    </div>
  </div>
</Card>

// app/casa/components/scenario-card.jsx
"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip"
import { cn } from "@/lib/utils"
import { CheckCircledIcon, InfoCircledIcon } from "@radix-ui/react-icons"

import {
  formatCurrency,
  formatCurrencyCompact,
  formatPercent,
  TOOLTIPS,
} from "./utils/calculations"

/**
 * Badge de estratégia
 */
const EstrategiaBadge = ({ estrategia }) => {
  const config = {
    permuta: {
      label: "Permuta",
      className: "bg-salmon/20 text-salmon border-salmon",
      icon: "🔄",
    },
    venda_posterior: {
      label: "Venda Posterior",
      className: "bg-green/20 text-green border-green",
      icon: "⏱️",
    },
  }

  const { label, className, icon } = config[estrategia] || config.permuta

  return (
    <span
      className={cn(
        "px-2 py-1 text-xs rounded-md border inline-flex items-center gap-1",
        className
      )}
    >
      <span>{icon}</span>
      {label}
    </span>
  )
}

/**
 * Indicador de comprometimento de renda
 */
const ComprometimentoIndicator = ({ comprometimento }) => {
  const { percentual, dentroDoLimite } = comprometimento

  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <div className="flex items-center gap-2">
            <div className="flex-1 h-2 bg-middleGray rounded-full overflow-hidden">
              <div
                className={cn(
                  "h-full transition-all",
                  dentroDoLimite ? "bg-green" : "bg-salmon"
                )}
                style={{ width: `${Math.min(percentual * 100, 100)}%` }}
              />
            </div>
            <span
              className={cn(
                "text-xs font-mono",
                dentroDoLimite ? "text-green" : "text-salmon"
              )}
            >
              {formatPercent(percentual)}
            </span>
          </div>
        </TooltipTrigger>
        <TooltipContent>
          <p className="text-xs">{TOOLTIPS.comprometimento}</p>
          {!dentroDoLimite && (
            <p className="text-xs text-salmon mt-1">
              Acima do limite de 30%. Pode dificultar aprovação.
            </p>
          )}
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  )
}

/**
 * Linha de dado com tooltip
 */
const DataRow = ({ label, value, tooltip, highlight, className }) => {
  return (
    <div
      className={cn(
        "flex justify-between items-center py-1",
        highlight && "bg-primary/5 -mx-2 px-2 rounded",
        className
      )}
    >
      <div className="flex items-center gap-1">
        <span className="text-xs text-ashGray">{label}</span>
        {tooltip && (
          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger asChild>
                <InfoCircledIcon className="h-3 w-3 text-dimGray hover:text-primary cursor-help" />
              </TooltipTrigger>
              <TooltipContent className="max-w-xs">
                <p className="text-xs">{tooltip}</p>
              </TooltipContent>
            </Tooltip>
          </TooltipProvider>
        )}
      </div>
      <span
        className={cn(
          "text-sm font-mono",
          highlight ? "text-primary font-bold" : "text-white"
        )}
      >
        {value}
      </span>
    </div>
  )
}

/**
 * Card de cenário individual
 */
export const ScenarioCard = ({ cenario, isExpanded = false }) => {
  const {
    valorImovel,
    valorApartamento,
    estrategia,
    isBest,
    financiamento,
    tabelaPadrao,
    cenarioOtimizado,
    comprometimento,
    economiaJuros,
    economiaPercentual,
    custosFechamento,
    custoTotalPadrao,
    custoTotalOtimizado,
    cetEstimado,
    aporteExtra,
  } = cenario

  return (
    <Card
      className={cn(
        "bg-eerieBlack border-brightGrey transition-all hover:border-primary/50",
        isBest && "border-primary ring-1 ring-primary/30"
      )}
    >
      <CardHeader className="pb-3">
        <div className="flex items-start justify-between gap-2">
          <div className="space-y-1">
            <CardTitle className="text-base flex items-center gap-2">
              <span className="text-primary">
                {formatCurrencyCompact(valorImovel)}
              </span>
              <span className="text-dimGray">+</span>
              <span className="text-salmon">
                Apto {formatCurrencyCompact(valorApartamento)}
              </span>
            </CardTitle>
            <EstrategiaBadge estrategia={estrategia} />
          </div>
          {isBest && (
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <div className="flex items-center gap-1 bg-primary/20 text-primary px-2 py-1 rounded-md text-xs">
                    <CheckCircledIcon className="h-4 w-4" />
                    Melhor
                  </div>
                </TooltipTrigger>
                <TooltipContent>
                  <p className="text-xs">
                    Cenário com menor custo total de juros
                  </p>
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
          )}
        </div>
      </CardHeader>

      <CardContent className="space-y-4">
        {/* Financiamento */}
        <div className="space-y-1">
          <h4 className="text-xs font-semibold text-ashGray uppercase tracking-wider">
            Financiamento
          </h4>
          <DataRow
            label="Valor Financiado"
            value={formatCurrency(financiamento.valorFinanciado)}
            tooltip="Valor total a ser financiado após entrada e/ou permuta."
          />
          <DataRow
            label="Entrada Total"
            value={formatCurrency(financiamento.entradaTotal)}
            tooltip="Soma de dinheiro + valor do apartamento (se permuta)."
          />
          {estrategia === "permuta" && (
            <DataRow
              label="Apto na Permuta"
              value={formatCurrency(financiamento.valorApartamentoUsado)}
              tooltip="Valor aceito do apartamento na permuta (com haircut)."
              className="text-salmon"
            />
          )}
        </div>

        {/* Parcelas */}
        <div className="space-y-1 pt-2 border-t border-brightGrey">
          <h4 className="text-xs font-semibold text-ashGray uppercase tracking-wider">
            Parcelas (SAC)
          </h4>
          <DataRow
            label="Primeira Parcela"
            value={formatCurrency(tabelaPadrao.primeiraParcelar)}
            tooltip="Parcela mais alta do financiamento (início do SAC)."
            highlight
          />
          <DataRow
            label="Última Parcela"
            value={formatCurrency(tabelaPadrao.ultimaParcela)}
            tooltip="Parcela mais baixa (fim do SAC)."
          />
          <div className="pt-1">
            <span className="text-xs text-ashGray">Comprometimento Renda</span>
            <ComprometimentoIndicator comprometimento={comprometimento} />
          </div>
        </div>

        {/* Cenário Otimizado */}
        <div className="space-y-1 pt-2 border-t border-brightGrey">
          <h4 className="text-xs font-semibold text-primary uppercase tracking-wider">
            Com Amortização Extra
          </h4>
          <DataRow
            label="📈 Aporte Extra/mês"
            value={
              <span className="text-primary font-bold">
                +{formatCurrency(aporteExtra)}
              </span>
            }
            tooltip={TOOLTIPS.aporteExtra}
            highlight
          />
          <DataRow
            label="Prazo Real"
            value={`${cenarioOtimizado.prazoReal} meses (${(cenarioOtimizado.prazoReal / 12).toFixed(1)} anos)`}
            tooltip="Tempo real para quitar com aportes extras."
          />
          <DataRow
            label="Economia de Tempo"
            value={`${cenarioOtimizado.mesesEconomizados} meses (${cenarioOtimizado.anosEconomizados} anos)`}
            tooltip="Tempo economizado com amortização acelerada."
          />
        </div>

        {/* Juros */}
        <div className="space-y-1 pt-2 border-t border-brightGrey">
          <h4 className="text-xs font-semibold text-ashGray uppercase tracking-wider">
            Custos de Juros
          </h4>
          <DataRow
            label="Juros (Padrão)"
            value={formatCurrency(tabelaPadrao.totalJuros)}
            tooltip="Total de juros pagos no prazo completo."
          />
          <DataRow
            label="Juros (Otimizado)"
            value={formatCurrency(cenarioOtimizado.totalJuros)}
            tooltip={TOOLTIPS.economiaJuros}
            highlight
          />
          <DataRow
            label="Economia"
            value={
              <span className="text-green">
                {formatCurrency(economiaJuros)} ({formatPercent(economiaPercentual)})
              </span>
            }
            tooltip="Economia total em juros com amortização acelerada."
          />
        </div>

        {/* Custos Adicionais */}
        {isExpanded && (
          <div className="space-y-1 pt-2 border-t border-brightGrey">
            <h4 className="text-xs font-semibold text-ashGray uppercase tracking-wider">
              Custos de Fechamento
            </h4>
            <DataRow
              label="ITBI"
              value={formatCurrency(custosFechamento.itbi.total)}
              tooltip={TOOLTIPS.itbi}
            />
            <DataRow
              label="Cartório/Registro"
              value={formatCurrency(custosFechamento.cartorio.total)}
              tooltip="Custos de registro de imóveis em SC."
            />
            <DataRow
              label="Total Fechamento"
              value={formatCurrency(custosFechamento.total)}
            />
          </div>
        )}

        {/* Custo Total */}
        <div className="space-y-1 pt-2 border-t border-primary/30 bg-primary/5 -mx-4 px-4 py-2 rounded-b-lg">
          <h4 className="text-xs font-semibold text-primary uppercase tracking-wider">
            Custo Total do Imóvel
          </h4>
          <DataRow
            label="Sem Amortização Extra"
            value={formatCurrency(custoTotalPadrao)}
            className="text-dimGray"
          />
          <DataRow
            label="Com Amortização Extra"
            value={formatCurrency(custoTotalOtimizado)}
            highlight
          />
          <div className="flex justify-between items-center pt-1">
            <span className="text-xs text-ashGray">CET Estimado</span>
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <span className="text-sm font-mono text-salmon cursor-help">
                    {formatPercent(cetEstimado)} a.a.
                  </span>
                </TooltipTrigger>
                <TooltipContent className="max-w-xs">
                  <p className="text-xs">{TOOLTIPS.cetEstimado}</p>
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}

/**
 * Card compacto para grid
 */
export const ScenarioCardCompact = ({ cenario, onClick }) => {
  const {
    valorImovel,
    valorApartamento,
    estrategia,
    isBest,
    financiamento,
    tabelaPadrao,
    cenarioOtimizado,
    comprometimento,
    economiaJuros,
    aporteExtra,
  } = cenario

  return (
    <Card
      className={cn(
        "bg-eerieBlack border-brightGrey cursor-pointer transition-all hover:border-primary/50 hover:scale-[1.02]",
        isBest && "border-primary ring-1 ring-primary/30"
      )}
      onClick={onClick}
    >
      <CardContent className="p-4 space-y-3">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="text-sm font-bold text-primary">
              {formatCurrencyCompact(valorImovel)}
            </span>
            <EstrategiaBadge estrategia={estrategia} />
          </div>
          {isBest && (
            <CheckCircledIcon className="h-5 w-5 text-primary" />
          )}
        </div>

        {/* Apto */}
        <div className="text-xs text-ashGray">
          Apto:{" "}
          <span className="text-salmon font-mono">
            {formatCurrencyCompact(valorApartamento)}
          </span>
        </div>

        {/* Métricas principais */}
        <div className="grid grid-cols-2 gap-2 text-xs">
          <div>
            <span className="text-dimGray block">Financiado</span>
            <span className="text-white font-mono">
              {formatCurrencyCompact(financiamento.valorFinanciado)}
            </span>
          </div>
          <div>
            <span className="text-dimGray block">1ª Parcela</span>
            <span className="text-white font-mono">
              {formatCurrencyCompact(tabelaPadrao.primeiraParcelar)}
            </span>
          </div>
          <div>
            <span className="text-dimGray block">Prazo Otim.</span>
            <span className="text-primary font-mono">
              {(cenarioOtimizado.prazoReal / 12).toFixed(1)} anos
            </span>
          </div>
          <div>
            <span className="text-dimGray block">Total Pago</span>
            <span className="text-white font-mono">
              {formatCurrencyCompact(cenarioOtimizado.totalPago)}
            </span>
          </div>
        </div>

        {/* Amortização Extra */}
        <div className="flex justify-between items-center text-xs bg-primary/10 rounded-md px-2 py-1">
          <span className="text-primary">📈 Aporte Extra/mês</span>
          <span className="font-mono font-bold text-primary">
            +{formatCurrencyCompact(aporteExtra)}
          </span>
        </div>

        {/* Juros - seção destacada */}
        <div className="bg-raisinBlack rounded-md p-2 space-y-1">
          <div className="flex justify-between items-center">
            <span className="text-xs text-salmon">💸 Juros a Pagar</span>
            <span className="text-sm font-mono font-bold text-salmon">
              {formatCurrencyCompact(cenarioOtimizado.totalJuros)}
            </span>
          </div>
          <div className="flex justify-between items-center">
            <span className="text-xs text-green">💚 Economia vs 30 anos</span>
            <span className="text-sm font-mono font-bold text-green">
              {formatCurrencyCompact(economiaJuros)}
            </span>
          </div>
        </div>

        {/* Comprometimento */}
        <ComprometimentoIndicator comprometimento={comprometimento} />
      </CardContent>
    </Card>
  )
}

/**
 * Card de destaque para o melhor cenário
 */
export const BestScenarioCard = ({ cenario }) => {
  if (!cenario) return null

  const {
    valorImovel,
    valorApartamento,
    estrategia,
    financiamento,
    cenarioOtimizado,
    economiaJuros,
    custoTotalOtimizado,
    aporteExtra,
  } = cenario

  return (
    <Card className="bg-gradient-to-br from-primary/10 to-green/10 border-primary">
      <CardHeader className="pb-2">
        <CardTitle className="text-lg flex items-center gap-2">
          <span className="text-2xl">🏆</span>
          Melhor Cenário
          <span className="text-sm font-normal text-ashGray ml-2">
            (com aporte de +{formatCurrencyCompact(aporteExtra)}/mês)
          </span>
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex flex-wrap items-center gap-2">
          <span className="text-xl font-bold text-primary">
            {formatCurrencyCompact(valorImovel)}
          </span>
          <span className="text-dimGray">+</span>
          <span className="text-salmon">
            Apto {formatCurrencyCompact(valorApartamento)}
          </span>
          <EstrategiaBadge estrategia={estrategia} />
        </div>

        <div className="grid grid-cols-2 md:grid-cols-6 gap-4">
          <div className="bg-black/30 rounded-lg p-3 border border-primary/30">
            <span className="text-xs text-primary block">📈 Aporte Extra/mês</span>
            <span className="text-lg font-bold text-primary">
              +{formatCurrencyCompact(aporteExtra)}
            </span>
          </div>
          <div className="bg-black/30 rounded-lg p-3">
            <span className="text-xs text-ashGray block">Financiado</span>
            <span className="text-lg font-bold text-white">
              {formatCurrencyCompact(financiamento.valorFinanciado)}
            </span>
          </div>
          <div className="bg-black/30 rounded-lg p-3">
            <span className="text-xs text-ashGray block">Prazo Real</span>
            <span className="text-lg font-bold text-primary">
              {(cenarioOtimizado.prazoReal / 12).toFixed(1)} anos
            </span>
          </div>
          <div className="bg-black/30 rounded-lg p-3 border border-salmon/30">
            <span className="text-xs text-salmon block">💸 Juros a Pagar</span>
            <span className="text-lg font-bold text-salmon">
              {formatCurrencyCompact(cenarioOtimizado.totalJuros)}
            </span>
          </div>
          <div className="bg-black/30 rounded-lg p-3">
            <span className="text-xs text-green block">💚 Economia</span>
            <span className="text-lg font-bold text-green">
              {formatCurrencyCompact(economiaJuros)}
            </span>
          </div>
          <div className="bg-black/30 rounded-lg p-3">
            <span className="text-xs text-ashGray block">Custo Total</span>
            <span className="text-lg font-bold text-white">
              {formatCurrencyCompact(custoTotalOtimizado)}
            </span>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
