// app/anuncios/components/anuncios-client.tsx
"use client"

import { Suspense, useState, useCallback, useEffect } from "react"
import { ListingsTable } from "./listings-table"
import { ListingsMap } from "./listings-map"
import { ParserModal } from "./parser-modal"
import { DataManagement } from "./data-management"
import { CollectionSelector } from "./collection-selector"
import { CollectionModal } from "./collection-modal"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { CollectionsProvider, useCollections } from "../lib/use-collections"
import { getDefaultFirstCollectionName } from "../lib/default-first-collection-name"
import { cn } from "@/lib/utils"
import type { Collection, Imovel } from "../lib/api"
import { syncSubscriptionCookie } from "@/lib/sync-subscription-cookie"
import { PageToolbar } from "@/app/components/page-toolbar"
import { Download, FolderOpen, Link2, Loader2, Plus } from "lucide-react"
import { ModalCloseButton } from "./modal-chrome"
import { AnunciosQuerySync } from "./anuncios-query-sync"

function AnunciosClientInner() {
  const {
    collections,
    listings,
    isLoading,
    isLoadingListings,
    error,
    setActiveCollection,
    createCollection,
    loadListings,
    refreshTrigger,
    triggerRefresh,
    orgContext,
  } = useCollections()

  const [showParser, setShowParser] = useState(false)
  const [showCollectionModal, setShowCollectionModal] = useState(false)
  const [editingCollection, setEditingCollection] = useState<Collection | null>(null)
  const [showShareConfirm, setShowShareConfirm] = useState(false)
  const [shareData, setShareData] = useState<{ collection: Collection; listings: Imovel[] } | null>(null)
  const [isCreatingFirstCollection, setIsCreatingFirstCollection] = useState(false)
  const [createCollectionError, setCreateCollectionError] = useState<string | null>(null)

  useEffect(() => {
    void syncSubscriptionCookie()
  }, [])

  const handleListingsChange = useCallback(() => {
    // Trigger a refresh of the listings
    loadListings()
    triggerRefresh()
  }, [loadListings, triggerRefresh])

  const handleCollectionChange = useCallback(
    (collection: Collection | null) => {
      setActiveCollection(collection)
    },
    [setActiveCollection]
  )

  const handleSwitchToCollection = useCallback(
    (collectionId: string) => {
      const collection = collections.find((c) => c.id === collectionId)
      if (collection) {
        handleCollectionChange(collection)
        triggerRefresh()
      }
    },
    [collections, handleCollectionChange, triggerRefresh]
  )

  const handleCreateCollection = useCallback(async () => {
    if (collections.length === 0) {
      setIsCreatingFirstCollection(true)
      setCreateCollectionError(null)
      try {
        const name = getDefaultFirstCollectionName()
        await createCollection(name, true)
        triggerRefresh()
      } catch (err) {
        setCreateCollectionError(
          err instanceof Error ? err.message : "Erro ao criar coleção"
        )
      } finally {
        setIsCreatingFirstCollection(false)
      }
      return
    }

    setEditingCollection(null)
    setShowCollectionModal(true)
  }, [
    collections.length,
    createCollection,
    triggerRefresh,
  ])

  const handleEditCollection = useCallback((collection: Collection) => {
    setEditingCollection(collection)
    setShowCollectionModal(true)
  }, [])

  const handleDeleteCollection = useCallback((collection: Collection) => {
    setEditingCollection(collection)
    setShowCollectionModal(true)
  }, [])

  const handleCollectionModalClose = useCallback(() => {
    setShowCollectionModal(false)
    setEditingCollection(null)
    triggerRefresh()
  }, [triggerRefresh])

  const handleShareImport = useCallback(() => {
    if (!shareData) return

    // For now, just close the modal - import functionality will be handled separately
    // The legacy URL-based sharing can be deprecated in favor of server-side sharing
    setShowShareConfirm(false)
    setShareData(null)
  }, [shareData])

  const handleShareCancel = useCallback(() => {
    setShowShareConfirm(false)
    setShareData(null)
  }, [])

  // Show loading state until data is loaded
  if (isLoading) {
    return (
      <div className="flex min-h-[calc(100vh-104px)] items-center justify-center bg-app-bg text-app-fg">
        <p className="text-app-muted">Carregando...</p>
      </div>
    )
  }

  // Show error state
  if (error) {
    return (
      <div className="flex min-h-[calc(100vh-104px)] items-center justify-center bg-app-bg text-app-fg">
        <div className="text-center">
          <p className="text-destructive mb-2">Erro ao carregar dados</p>
          <p className="text-sm text-app-muted">{error}</p>
        </div>
      </div>
    )
  }

  // Show empty state when no collections exist
  if (collections.length === 0) {
    const isOrgContext = orgContext.type === "organization"
    const contextName = isOrgContext ? orgContext.organizationName : "pessoal"
    const defaultCollectionName = getDefaultFirstCollectionName()

    return (
      <div className="min-h-[calc(100vh-104px)] bg-app-bg text-app-fg">
        {/* Header */}

        {/* Empty State */}
        <main className="max-w-7xl mx-auto px-4 py-12">
          <Card className="mx-auto max-w-lg border-app-border bg-app-surface">
            <CardContent className="py-12 text-center space-y-6">
              <FolderOpen className="h-16 w-16 mx-auto text-muted-foreground" />
              <div className="space-y-2">
                <h2 className="text-xl font-semibold text-app-fg">
                  {isOrgContext
                    ? `Nenhuma coleção na organização "${contextName}"`
                    : "Nenhuma coleção pessoal"}
                </h2>
                <p className="mx-auto max-w-sm text-sm text-app-muted">
                  {isOrgContext
                    ? `Comece agora — criamos automaticamente a coleção "${defaultCollectionName}" nesta organização.`
                    : `Comece agora — criamos automaticamente a coleção "${defaultCollectionName}" para você salvar imóveis.`}
                </p>
              </div>
              {createCollectionError && (
                <p className="text-sm text-destructive">{createCollectionError}</p>
              )}
              <button
                onClick={() => void handleCreateCollection()}
                disabled={isCreatingFirstCollection}
                className={cn(
                  "px-6 py-3 rounded-lg text-sm font-medium transition-all",
                  "bg-app-action text-app-action-foreground",
                  "hover:bg-app-action-hover",
                  "disabled:opacity-50 disabled:cursor-not-allowed",
                  "flex items-center gap-2 mx-auto"
                )}
              >
                {isCreatingFirstCollection ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    <span>Criando...</span>
                  </>
                ) : (
                  <>
                    <Plus className="h-4 w-4" />
                    <span>Criar Primeira Coleção</span>
                  </>
                )}
              </button>
            </CardContent>
          </Card>
        </main>
      </div>
    )
  }

  return (
    <div className="min-h-[calc(100vh-104px)] bg-app-bg text-app-fg">
      <PageToolbar>
        <div className="flex w-full min-w-0 flex-col gap-1.5 md:flex-row md:items-center md:justify-between md:gap-x-4">
          <div className="flex w-full min-w-0 flex-nowrap items-center gap-1.5 md:order-2 md:w-auto md:shrink-0">
            <CollectionSelector
              onCollectionChange={handleCollectionChange}
              onCreateCollection={handleCreateCollection}
              onEditCollection={handleEditCollection}
              onDeleteCollection={handleDeleteCollection}
              refreshTrigger={refreshTrigger}
            />
          </div>
          <div className="flex w-full min-w-0 flex-nowrap items-center gap-2 md:order-1 md:min-w-0 md:flex-1">
            <DataManagement
              onDataChange={handleListingsChange}
              listingsCount={listings.length}
              onOpenParser={() => setShowParser(true)}
              onImportSuccess={triggerRefresh}
              onSwitchToCollection={handleSwitchToCollection}
            />
          </div>
        </div>
      </PageToolbar>

      {/* Collection Modal */}
      <CollectionModal
        isOpen={showCollectionModal}
        onClose={handleCollectionModalClose}
        collection={editingCollection}
        onCollectionChange={handleListingsChange}
      />

      {/* Parser Modal */}
      <ParserModal
        isOpen={showParser}
        onClose={() => setShowParser(false)}
      />

      {/* Share Import Confirmation Modal */}
      {showShareConfirm && shareData && (
        <div className="fixed inset-0 z-[1000] flex items-center justify-center">
          <div
            className="absolute inset-0 bg-app-fg/40 backdrop-blur-sm"
            onClick={handleShareCancel}
          />
          <Card className="relative z-10 w-full max-w-md mx-4 border-app-border bg-app-surface">
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-lg flex items-center gap-2">
                <Link2 className="h-5 w-5 text-app-accent" />
                <span>Importar Coleção Compartilhada</span>
              </CardTitle>
              <ModalCloseButton onClick={handleShareCancel} />
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <p className="text-sm text-app-muted">
                  Você recebeu um link compartilhado com dados de uma coleção:
                </p>
                <div className="rounded-lg border border-app-border bg-app-bg p-3">
                  <p className="text-sm font-medium text-app-fg">
                    {shareData.collection.label}
                  </p>
                  <p className="text-xs text-muted-foreground mt-1">
                    {shareData.listings.length} imóvel{shareData.listings.length !== 1 ? "eis" : ""}
                  </p>
                </div>
                <p className="text-xs text-muted-foreground">
                  Deseja importar esta coleção? Os dados serão adicionados à sua coleção atual.
                </p>
              </div>
              <div className="flex gap-2">
                <button
                  onClick={handleShareCancel}
                  className={cn(
                    "flex-1 py-2.5 px-4 rounded-lg font-medium transition-all",
                    "border border-app-border bg-app-surface text-app-fg",
                    "hover:border-app-border-strong hover:bg-app-bg hover:text-app-fg"
                  )}
                >
                  Cancelar
                </button>
                <button
                  onClick={handleShareImport}
                  className={cn(
                    "flex-1 py-2.5 px-4 rounded-lg font-medium transition-all",
                    "bg-app-action text-app-action-foreground",
                    "hover:bg-app-action-hover",
                    "flex items-center justify-center gap-2"
                  )}
                >
                  <Download className="h-4 w-4" />
                  Importar
                </button>
              </div>
            </CardContent>
          </Card>
        </div>
      )}

      <main className="max-w-7xl mx-auto space-y-4 px-4 py-4">
        {/* Main Content - Full Width Table */}
        {isLoadingListings && listings.length === 0 ? (
          <Card className="border-app-border bg-app-surface">
            <CardContent className="py-12 text-center">
              <p className="text-app-muted">Carregando imóveis...</p>
            </CardContent>
          </Card>
        ) : (
          <ListingsTable listings={listings} refreshTrigger={refreshTrigger} />
        )}

        {/* Map View */}
        <ListingsMap listings={listings} />
      </main>
    </div>
  )
}

export function AnunciosClient() {
  return (
    <CollectionsProvider>
      <Suspense fallback={null}>
        <AnunciosQuerySync />
      </Suspense>
      <AnunciosClientInner />
    </CollectionsProvider>
  )
}

// apps/web/src/lib/components/anuncios/AnunciosClient.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { page } from "$app/stores";
  import { Download, FolderOpen, Link2, Loader2, Plus } from "@lucide/svelte";
  import Card from "$lib/components/ui/Card.svelte";
  import { getActiveOrganizationId } from "$lib/api/client";
  import { syncSubscriptionCookie } from "$lib/sync-subscription-cookie";
  import { cn } from "$lib/utils";
  import { workspaceApi } from "$lib/workspace/client";
  import { getDefaultFirstCollectionName } from "$lib/anuncios/default-first-collection-name";
  import { LISTINGS_PAGE_CLASS } from "$lib/anuncios/listings-panel-layout";
  import { WORKSPACE_CONTENT_CLASS } from "$lib/workspace-chrome";
  import { getCollectionsContext } from "$lib/collections-context.svelte";
  import { toListingData, type Imovel } from "$lib/anuncios/types";
  import type { ListingData } from "$lib/workspace/client";
  import AnunciosQuerySync from "$lib/components/anuncios/AnunciosQuerySync.svelte";
  import ListingsTable from "$lib/components/anuncios/ListingsTable.svelte";
  import ListingsMap from "$lib/components/anuncios/ListingsMap.svelte";
  import ModalCloseButton from "$lib/components/anuncios/ModalCloseButton.svelte";

  const ctx = getCollectionsContext();

  let isCreatingFirstCollection = $state(false);
  let createCollectionError = $state<string | null>(null);
  let showShareConfirm = $state(false);
  let shareData = $state<{ collection: { id: string; name: string }; listings: ListingData[] } | null>(null);
  let isImportingShare = $state(false);
  let shareImportError = $state<string | null>(null);
  let loadedShareToken = $state<string | null>(null);
  let activeOrgId = $state<string | null>(null);
  let activeOrgName = $state<string | null>(null);

  const shareToken = $derived($page.url.searchParams.get("share") ?? $page.url.searchParams.get("dbshare"));
  const isOrgContext = $derived(Boolean(activeOrgId));
  const contextName = $derived(isOrgContext ? (activeOrgName ?? "organização") : "pessoal");
  const defaultCollectionName = getDefaultFirstCollectionName();

  async function refreshOrganizationContext() {
    activeOrgId = getActiveOrganizationId();
    if (!activeOrgId) {
      activeOrgName = null;
      return;
    }
    try {
      const { organizations } = await workspaceApi.fetchOrganizations();
      activeOrgName = organizations.find((org) => org.id === activeOrgId)?.name ?? null;
    } catch {
      activeOrgName = null;
    }
  }

  onMount(() => {
    void syncSubscriptionCookie();
    void refreshOrganizationContext();
    const onOrgChange = () => void refreshOrganizationContext();
    window.addEventListener("minha-casa:organization-context-change", onOrgChange);
    return () => window.removeEventListener("minha-casa:organization-context-change", onOrgChange);
  });

  $effect(() => {
    const token = shareToken;
    if (!token || ctx.isLoading || loadedShareToken === token) return;
    loadedShareToken = token;
    void (async () => {
      try {
        const loaded = await ctx.loadSharedCollection(token);
        shareData = {
          collection: loaded.collection,
          listings: loaded.listings.map((listing) => toListingData(listing))
        };
        showShareConfirm = true;
      } catch (err) {
        shareImportError = err instanceof Error ? err.message : "Link de compartilhamento inválido";
      }
    })();
  });

  async function handleCreateCollection() {
    if (ctx.collections.length > 0) return;
    isCreatingFirstCollection = true;
    createCollectionError = null;
    try {
      await ctx.createCollection(getDefaultFirstCollectionName(), true);
      ctx.triggerRefresh();
      if (ctx.activeCollection?.id) {
        await ctx.loadListings(ctx.activeCollection.id);
      }
    } catch (err) {
      createCollectionError = err instanceof Error ? err.message : "Erro ao criar coleção";
    } finally {
      isCreatingFirstCollection = false;
    }
  }

  async function handleShareImport() {
    if (!shareData) return;
    isImportingShare = true;
    shareImportError = null;
    try {
      await ctx.importSharedListings(shareData.listings);
      showShareConfirm = false;
      shareData = null;
      if (ctx.activeCollection?.id) {
        await ctx.loadListings(ctx.activeCollection.id);
      }
    } catch (err) {
      shareImportError = err instanceof Error ? err.message : "Erro ao importar coleção";
    } finally {
      isImportingShare = false;
    }
  }

  function handleShareCancel() {
    showShareConfirm = false;
    shareData = null;
    shareImportError = null;
  }
</script>

<svelte:head>
  <title>Anúncios de Imóveis | Parser IA</title>
  <meta
    name="description"
    content="Gerencie anúncios de imóveis com extração automática de dados usando IA."
  />
</svelte:head>

<AnunciosQuerySync />

{#if ctx.isLoading}
  <div class="flex min-h-[calc(100vh-var(--nav-height,2.75rem))] items-center justify-center bg-app-bg text-app-muted">
    <Loader2 class="h-6 w-6 animate-spin" />
    <span class="ml-2 text-sm">Carregando...</span>
  </div>
{:else if ctx.error}
  <div class={cn("min-h-[calc(100vh-var(--nav-height,2.75rem))] bg-app-bg text-app-fg", WORKSPACE_CONTENT_CLASS)}>
    <div class="rounded-md border border-app-border bg-app-surface p-6 text-center">
      <p class="mb-2 font-medium">Erro ao carregar dados</p>
      <p class="text-sm text-app-muted">{ctx.error}</p>
    </div>
  </div>
{:else if ctx.collections.length === 0}
  <div class="min-h-[calc(100vh-var(--nav-height,2.75rem))] bg-app-bg text-app-fg">
    <main class={WORKSPACE_CONTENT_CLASS}>
      <Card class="mx-auto max-w-lg border-app-border bg-app-surface">
        <div class="space-y-6 py-12 text-center">
          <FolderOpen class="mx-auto h-16 w-16 text-muted-foreground" />
          <div class="space-y-2">
            <h2 class="text-xl font-semibold text-app-fg">
              {#if isOrgContext}
                Nenhuma coleção na organização "{contextName}"
              {:else}
                Nenhuma coleção pessoal
              {/if}
            </h2>
            <p class="mx-auto max-w-sm text-sm text-app-muted">
              {#if isOrgContext}
                Comece agora — criamos automaticamente a coleção "{defaultCollectionName}" nesta organização.
              {:else}
                Comece agora — criamos automaticamente a coleção "{defaultCollectionName}" para você salvar imóveis.
              {/if}
            </p>
          </div>
          {#if createCollectionError}
            <p class="text-sm text-destructive">{createCollectionError}</p>
          {/if}
          <button
            type="button"
            onclick={() => void handleCreateCollection()}
            disabled={isCreatingFirstCollection}
            class={cn(
              "mx-auto flex items-center gap-2 rounded-lg px-6 py-3 text-sm font-medium transition-all",
              "bg-app-action text-app-action-foreground hover:bg-app-action-hover",
              "disabled:cursor-not-allowed disabled:opacity-50"
            )}
          >
            {#if isCreatingFirstCollection}
              <Loader2 class="h-4 w-4 animate-spin" />
              <span>Criando...</span>
            {:else}
              <Plus class="h-4 w-4" />
              <span>Criar Primeira Coleção</span>
            {/if}
          </button>
        </div>
      </Card>
    </main>
  </div>
{:else}
  <div class="min-h-[calc(100vh-var(--nav-height,2.75rem))] bg-app-bg text-app-fg">
    {#if showShareConfirm && shareData}
      <div class="fixed inset-0 z-[1000] flex items-center justify-center">
        <button
          type="button"
          class="absolute inset-0 bg-app-fg/40 backdrop-blur-sm"
          aria-label="Fechar"
          onclick={handleShareCancel}
        ></button>
        <Card class="relative z-10 mx-4 w-full max-w-md border-app-border bg-app-surface">
          <div class="flex items-center justify-between border-b border-app-border px-4 py-3">
            <h2 class="flex items-center gap-2 text-lg font-semibold">
              <Link2 class="h-5 w-5 text-app-accent" />
              Importar Coleção Compartilhada
            </h2>
            <ModalCloseButton onclick={handleShareCancel} />
          </div>
          <div class="space-y-4 p-4">
            <p class="text-sm text-app-muted">Você recebeu um link compartilhado com dados de uma coleção:</p>
            <div class="rounded-lg border border-app-border bg-app-bg p-3">
              <p class="text-sm font-medium text-app-fg">{shareData.collection.name}</p>
              <p class="mt-1 text-xs text-muted-foreground">
                {shareData.listings.length} imóvel{shareData.listings.length === 1 ? "" : "eis"}
              </p>
            </div>
            <p class="text-xs text-muted-foreground">
              Deseja importar esta coleção? Os dados serão adicionados à sua coleção atual.
            </p>
            {#if shareImportError}
              <p class="text-sm text-destructive">{shareImportError}</p>
            {/if}
            <div class="flex gap-2">
              <button
                type="button"
                class={cn(
                  "flex-1 rounded-lg border border-app-border bg-app-surface py-2.5 text-sm font-medium text-app-fg transition-all",
                  "hover:border-app-border-strong hover:bg-app-bg"
                )}
                onclick={handleShareCancel}
              >
                Cancelar
              </button>
              <button
                type="button"
                class={cn(
                  "flex flex-1 items-center justify-center gap-2 rounded-lg bg-app-action py-2.5 text-sm font-medium text-app-action-foreground transition-all",
                  "hover:bg-app-action-hover disabled:opacity-50"
                )}
                disabled={isImportingShare}
                onclick={() => void handleShareImport()}
              >
                {#if isImportingShare}
                  <Loader2 class="h-4 w-4 animate-spin" />
                {:else}
                  <Download class="h-4 w-4" />
                {/if}
                Importar
              </button>
            </div>
          </div>
        </Card>
      </div>
    {/if}

    <main class={LISTINGS_PAGE_CLASS}>
      {#if ctx.isLoadingListings && ctx.listings.length === 0}
        <p class="rounded-md border border-app-border bg-app-surface py-8 text-center text-sm text-app-muted">
          Carregando imóveis...
        </p>
      {:else}
        <ListingsTable listings={ctx.listings} refreshTrigger={ctx.refreshTrigger} />
      {/if}
      <ListingsMap listings={ctx.listings} />
    </main>
  </div>
{/if}
