// app/anuncios/components/anuncios-query-sync.tsx
"use client"

import { useEffect } from "react"
import { useSearchParams } from "next/navigation"
import { useCollections } from "../lib/use-collections"

/**
 * Applies ?collection= & ?listing= deep links from channel assistant replies.
 */
export function AnunciosQuerySync() {
  const searchParams = useSearchParams()
  const collectionId = searchParams.get("collection")
  const listingId = searchParams.get("listing")
  const { collections, setActiveCollection, listings, isLoadingListings } = useCollections()

  useEffect(() => {
    if (!collectionId || collections.length === 0) return
    const match = collections.find((c) => c.id === collectionId)
    if (match) {
      setActiveCollection(match)
    }
  }, [collectionId, collections, setActiveCollection])

  useEffect(() => {
    if (!listingId || isLoadingListings) return
    const el = document.getElementById(`listing-${listingId}`)
    if (el) {
      el.scrollIntoView({ behavior: "smooth", block: "center" })
      el.classList.add("ring-2", "ring-primary/60")
      const timer = window.setTimeout(() => {
        el.classList.remove("ring-2", "ring-primary/60")
      }, 3000)
      return () => window.clearTimeout(timer)
    }
  }, [listingId, listings, isLoadingListings])

  return null
}

// apps/web/src/lib/components/anuncios/AnunciosQuerySync.svelte
<script lang="ts">
  import { page } from "$app/stores";
  import { getCollectionsContext } from "$lib/collections-context.svelte";
  import { applyListingDeepLinkHighlight } from "$lib/components/anuncios/listings-table-shared";

  const ctx = getCollectionsContext();

  const collectionId = $derived($page.url.searchParams.get("collection"));
  const listingId = $derived($page.url.searchParams.get("listing"));

  $effect(() => {
    if (!collectionId || ctx.collections.length === 0) return;
    const match = ctx.collections.find((collection) => collection.id === collectionId);
    if (match) ctx.setActiveCollection(match);
  });

  $effect(() => {
    if (!listingId || ctx.isLoadingListings) return;
    const element = document.getElementById(`listing-${listingId}`);
    if (!element) return;
    element.scrollIntoView({ behavior: "smooth", block: "center" });
    const removeHighlight = applyListingDeepLinkHighlight(element);
    const timer = window.setTimeout(() => removeHighlight(), 3000);
    return () => {
      window.clearTimeout(timer);
      removeHighlight();
    };
  });
</script>
