// apps/web/src/lib/components/ui/Button.svelte
<script lang="ts">
  import { cn } from "$lib/utils";

  type Variant = "primary" | "default" | "secondary" | "outline" | "ghost" | "danger" | "destructive" | "link";
  type Size = "sm" | "md" | "lg" | "icon";
  let {
    children,
    class: className = "",
    variant = "primary",
    size = "md",
    type = "button",
    disabled = false,
    title,
    ariaLabel,
    onclick
  } = $props<{
    children?: import("svelte").Snippet;
    class?: string;
    variant?: Variant;
    size?: Size;
    type?: "button" | "submit" | "reset";
    disabled?: boolean;
    title?: string;
    ariaLabel?: string;
    onclick?: (event: MouseEvent) => void;
  }>();

  const variants: Record<Variant, string> = {
    default: "bg-primary text-primary-foreground hover:bg-[#7ec4f8]",
    primary: "bg-primary text-primary-foreground hover:bg-[#7ec4f8]",
    secondary: "border border-border bg-card text-foreground shadow-sm hover:bg-muted",
    outline: "border border-border bg-background text-foreground shadow-sm hover:bg-muted",
    ghost: "text-foreground hover:bg-muted",
    danger: "bg-destructive text-white shadow-sm hover:brightness-95",
    destructive: "bg-destructive text-white shadow-sm hover:brightness-95",
    link: "h-auto px-0 text-app-fg underline-offset-4 hover:underline"
  };

  const sizes: Record<Size, string> = {
    sm: "h-8 rounded-md px-3 text-xs",
    md: "h-10 px-4 text-sm",
    lg: "h-11 rounded-md px-8 text-sm",
    icon: "h-9 w-9 px-0"
  };
</script>

<button
  {type}
  {disabled}
  {title}
  aria-label={ariaLabel}
  class={cn(
    "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md font-medium transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-app-action disabled:pointer-events-none disabled:opacity-60 [&_svg]:pointer-events-none [&_svg]:shrink-0",
    variants[variant as Variant],
    sizes[size as Size],
    className
  )}
  {onclick}
>
  {@render children?.()}
</button>

// components/ui/button.tsx
import * as React from "react"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"

const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0",
  {
    variants: {
      variant: {
        default:
          "bg-primary text-primary-foreground shadow hover:bg-primary/90",
        destructive:
          "bg-destructive text-destructive-foreground shadow-sm hover:bg-destructive/90",
        outline:
          "border border-input bg-background shadow-sm hover:bg-accent hover:text-accent-foreground",
        secondary:
          "bg-secondary text-secondary-foreground shadow-sm hover:bg-secondary/80",
        ghost: "hover:bg-accent hover:text-accent-foreground",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default: "h-9 px-4 py-2",
        sm: "h-8 rounded-md px-3 text-xs",
        lg: "h-10 rounded-md px-8",
        icon: "h-9 w-9",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, ...props }, ref) => {
    return (
      <button
        className={cn(buttonVariants({ variant, size, className }))}
        ref={ref}
        {...props}
      />
    )
  }
)
Button.displayName = "Button"

export { Button, buttonVariants }
