// apps/web/src/lib/components/home/DemoParserModal.svelte
<script lang="ts">
  import { Bot, Check, Loader2, Paperclip, Sparkles, X } from "@lucide/svelte";
  import Card from "$lib/components/ui/Card.svelte";
  import CardContent from "$lib/components/ui/CardContent.svelte";
  import CardHeader from "$lib/components/ui/CardHeader.svelte";
  import Input from "$lib/components/ui/Input.svelte";
  import Label from "$lib/components/ui/Label.svelte";
  import ModalCloseButton from "$lib/components/anuncios/ModalCloseButton.svelte";
  import ModalHeaderTitle from "$lib/components/anuncios/ModalHeaderTitle.svelte";
  import type { Imovel } from "$lib/anuncios/types";
  import type { ListingData } from "$lib/workspace/client";

  let {
    isOpen,
    onClose,
    onListingAdded
  } = $props<{
    isOpen: boolean;
    onClose: () => void;
    onListingAdded: (listing: Imovel) => void;
  }>();

  const SAMPLE_INPUT = `CASA DUPLEX - CAMPECHE
4 quartos (2 suites), 3 banheiros
Area total: 280m² | Area privativa: 180m²
Piscina, churrasqueira, 2 vagas
R$ 1.450.000
Rua dos Surfistas, 456 - Campeche`;

  const SAMPLE_OUTPUT: ListingData = {
    titulo: "Casa Duplex - Campeche",
    endereco: "Rua dos Surfistas, 456 - Campeche",
    quartos: 4,
    suites: 2,
    banheiros: 3,
    m2Totais: 280,
    m2Privado: 180,
    preco: 1450000,
    precoM2: 1450000 / 180,
    piscina: true,
    garagem: 2,
    porteiro24h: false,
    academia: false,
    vistaLivre: true,
    piscinaTermica: false,
    link: undefined,
    addedAt: new Date().toISOString().split("T")[0]
  };

  let rawText = $state(SAMPLE_INPUT);
  let attachedName = $state<string | null>(null);
  let isLoading = $state(false);
  let lastParsed = $state<{ id: string; data: ListingData } | null>(null);
  let linkValue = $state("");
  let addressValue = $state("");

  $effect(() => {
    if (!isOpen) return;
    rawText = SAMPLE_INPUT;
    attachedName = null;
    isLoading = false;
    lastParsed = null;
    linkValue = "";
    addressValue = "";
  });

  async function handleParse() {
    if (!rawText.trim() && !attachedName) return;
    isLoading = true;
    await new Promise((resolve) => setTimeout(resolve, 1200));
    lastParsed = { id: `demo-${Date.now()}`, data: SAMPLE_OUTPUT };
    addressValue = SAMPLE_OUTPUT.endereco || "";
    rawText = "";
    attachedName = null;
    isLoading = false;
  }

  function handleSaveAndClose() {
    if (!lastParsed) return;
    onListingAdded({
      id: lastParsed.id,
      ...lastParsed.data,
      endereco: addressValue || lastParsed.data.endereco || "",
      link: linkValue || null,
      createdAt: new Date().toISOString()
    } as Imovel);
    onClose();
  }
</script>

{#if isOpen}
  <div class="fixed inset-0 z-[1000] flex items-center justify-center">
    <button
      type="button"
      class="absolute inset-0 bg-app-fg/80 backdrop-blur-sm"
      aria-label="Fechar modal"
      onclick={onClose}
    ></button>
    <Card
      class="relative z-10 mx-4 flex max-h-[90vh] w-full max-w-lg flex-col overflow-hidden border-app-border bg-app-surface"
    >
      <CardHeader class="flex flex-row items-center justify-between px-4 py-3">
        <div class="flex items-center gap-2">
          <ModalHeaderTitle icon={Bot} title="Adicionar imóvel" />
          <span
            class="rounded border border-app-action/30 bg-app-action/20 px-1.5 py-0.5 text-[10px] font-medium uppercase text-app-accent"
          >
            Demo
          </span>
        </div>
        <ModalCloseButton onclick={onClose} />
      </CardHeader>
      <CardContent class="flex flex-col gap-3 px-4 pb-4">
        {#if !lastParsed}
          <Input
            disabled
            placeholder="URL do anúncio (em breve)"
            class="h-8 cursor-not-allowed text-sm opacity-60"
          />
          <textarea
            bind:value={rawText}
            class="min-h-[80px] w-full resize-none rounded-lg border border-app-border bg-input/30 px-3 py-2 text-sm"
          ></textarea>
          <p class="text-center text-xs text-muted-foreground">ou</p>
          <div
            class="flex min-h-[72px] items-center justify-center rounded-lg border border-dashed border-app-border bg-app-surface-muted/40 px-3 py-3 text-xs text-muted-foreground"
          >
            {#if attachedName}
              <span class="flex w-full items-center gap-2">
                <Paperclip class="h-4 w-4" />
                <span class="flex-1 truncate">{attachedName}</span>
                <button type="button" onclick={() => (attachedName = null)}>
                  <X class="h-4 w-4" />
                </button>
              </span>
            {:else}
              Arraste um arquivo ou clique para selecionar
            {/if}
          </div>
          <button
            type="button"
            onclick={() => void handleParse()}
            disabled={isLoading || (!rawText.trim() && !attachedName)}
            class="flex w-full items-center justify-center gap-2 rounded-lg bg-app-action py-2.5 text-sm font-medium text-app-action-foreground disabled:opacity-50"
          >
            {#if isLoading}
              <Loader2 class="h-4 w-4 animate-spin" />
              Processando...
            {:else}
              <Sparkles class="h-4 w-4" />
              Extrair Dados
            {/if}
          </button>
        {:else}
          <div class="space-y-3 rounded-lg border border-green/30 bg-green/10 p-3">
            <p class="flex items-center gap-2 text-sm text-green">
              <Check class="h-4 w-4" />
              Dados extraídos
            </p>
            <div>
              <Label class="text-xs">Endereço</Label>
              <Input bind:value={addressValue} class="mt-1 h-8 text-sm" />
            </div>
            <div>
              <Label class="text-xs">Link</Label>
              <Input bind:value={linkValue} class="mt-1 h-8 text-sm" />
            </div>
            <button
              type="button"
              onclick={handleSaveAndClose}
              class="w-full rounded-lg bg-app-action py-2 text-sm font-medium text-app-action-foreground"
            >
              Adicionar à tabela demo
            </button>
          </div>
        {/if}
      </CardContent>
    </Card>
  </div>
{/if}

// app/anuncios/components/demo-parser-modal.tsx
"use client"

import { useState, useEffect, useRef } from "react"
import { Bot, Check, Paperclip, Sparkles, X } from "lucide-react"
import { Card, CardContent, CardHeader } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { ModalCloseButton, ModalHeaderTitle, LoadingLabel } from "./modal-chrome"
import { cn } from "@/lib/utils"
import type { Imovel } from "../lib/api"
import type { ListingData } from "@/lib/db/schema"

interface DemoParserModalProps {
  isOpen: boolean
  onClose: () => void
  onListingAdded: (listing: Imovel) => void
}

const SAMPLE_INPUT = `CASA DUPLEX - CAMPECHE
4 quartos (2 suites), 3 banheiros
Area total: 280m² | Area privativa: 180m²
Piscina, churrasqueira, 2 vagas
R$ 1.450.000
Rua dos Surfistas, 456 - Campeche`

const SAMPLE_OUTPUT: ListingData = {
  titulo: "Casa Duplex - Campeche",
  endereco: "Rua dos Surfistas, 456 - Campeche",
  quartos: 4,
  suites: 2,
  banheiros: 3,
  m2Totais: 280,
  m2Privado: 180,
  preco: 1450000,
  precoM2: 1450000 / 180,
  piscina: true,
  garagem: 2,
  porteiro24h: false,
  academia: false,
  vistaLivre: true,
  piscinaTermica: false,
  link: null,
  addedAt: new Date().toISOString().split("T")[0],
}

export function DemoParserModal({
  isOpen,
  onClose,
  onListingAdded,
}: DemoParserModalProps) {
  const [rawText, setRawText] = useState(SAMPLE_INPUT)
  const [attachedName, setAttachedName] = useState<string | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const [lastParsed, setLastParsed] = useState<{ id: string; data: ListingData } | null>(null)
  const [linkValue, setLinkValue] = useState("")
  const [addressValue, setAddressValue] = useState("")
  const linkInputRef = useRef<HTMLInputElement>(null)

  useEffect(() => {
    if (isOpen) {
      setRawText(SAMPLE_INPUT)
      setAttachedName(null)
      setLastParsed(null)
      setLinkValue("")
      setAddressValue("")
    }
  }, [isOpen])

  useEffect(() => {
    if (lastParsed) setAddressValue(lastParsed.data.endereco || "")
  }, [lastParsed])

  const handleParse = async () => {
    if (!rawText.trim() && !attachedName) return
    setIsLoading(true)
    await new Promise((r) => setTimeout(r, 1200))
    setLastParsed({ id: `demo-${Date.now()}`, data: SAMPLE_OUTPUT })
    setRawText("")
    setAttachedName(null)
    setIsLoading(false)
  }

  const handleSaveAndClose = () => {
    if (!lastParsed) return
    onListingAdded({
      id: lastParsed.id,
      ...lastParsed.data,
      endereco: addressValue || lastParsed.data.endereco,
      link: linkValue || null,
      createdAt: new Date().toISOString(),
    })
    onClose()
  }

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 z-[1000] flex items-center justify-center">
      <div className="absolute inset-0 bg-app-fg/80 backdrop-blur-sm" onClick={onClose} />
      <Card className="relative z-10 w-full max-w-lg mx-4 bg-app-surface border-app-border max-h-[90vh] overflow-hidden flex flex-col">
        <CardHeader className="flex flex-row items-center justify-between py-3 px-4">
          <div className="flex items-center gap-2">
            <ModalHeaderTitle icon={Bot} title="Adicionar imóvel" />
            <span className="text-[10px] px-1.5 py-0.5 rounded bg-app-action/20 text-app-accent border border-app-action/30 font-medium uppercase">
              Demo
            </span>
          </div>
          <ModalCloseButton onClick={onClose} />
        </CardHeader>
        <CardContent className="flex flex-col gap-3 px-4 pb-4">
          {!lastParsed ? (
            <>
              <Input
                disabled
                placeholder="URL do anúncio (em breve)"
                className="h-8 text-sm opacity-60 cursor-not-allowed"
              />
              <textarea
                value={rawText}
                onChange={(e) => setRawText(e.target.value)}
                className="min-h-[80px] w-full rounded-lg border border-app-border bg-input/30 px-3 py-2 text-sm resize-none"
              />
              <p className="text-center text-xs text-muted-foreground">ou</p>
              <div className="flex min-h-[72px] items-center justify-center rounded-lg border border-dashed border-app-border bg-app-surface-muted/40 px-3 py-3 text-xs text-muted-foreground">
                {attachedName ? (
                  <span className="flex items-center gap-2 w-full">
                    <Paperclip className="h-4 w-4" />
                    <span className="truncate flex-1">{attachedName}</span>
                    <button type="button" onClick={() => setAttachedName(null)}>
                      <X className="h-4 w-4" />
                    </button>
                  </span>
                ) : (
                  "Arraste um arquivo ou clique para selecionar"
                )}
              </div>
              <button
                type="button"
                onClick={() => void handleParse()}
                disabled={isLoading || (!rawText.trim() && !attachedName)}
                className="w-full py-2.5 rounded-lg text-sm font-medium bg-app-action text-app-action-foreground disabled:opacity-50 flex items-center justify-center gap-2"
              >
                {isLoading ? (
                  <LoadingLabel label="Processando..." />
                ) : (
                  <>
                    <Sparkles className="h-4 w-4" />
                    Extrair Dados
                  </>
                )}
              </button>
            </>
          ) : (
            <div className="space-y-3 rounded-lg border border-green/30 bg-green/10 p-3">
              <p className="text-sm text-green flex items-center gap-2">
                <Check className="h-4 w-4" />
                Dados extraídos
              </p>
              <div>
                <Label className="text-xs">Endereço</Label>
                <Input
                  value={addressValue}
                  onChange={(e) => setAddressValue(e.target.value)}
                  className="h-8 mt-1 text-sm"
                />
              </div>
              <div>
                <Label className="text-xs">Link</Label>
                <Input
                  ref={linkInputRef}
                  value={linkValue}
                  onChange={(e) => setLinkValue(e.target.value)}
                  className="h-8 mt-1 text-sm"
                />
              </div>
              <button
                type="button"
                onClick={handleSaveAndClose}
                className="w-full py-2 rounded-lg text-sm font-medium bg-app-action text-app-action-foreground"
              >
                Adicionar à tabela demo
              </button>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
