// apps/web/src/lib/components/listings/ExportModal.svelte
<script lang="ts">
  import { Check, ClipboardList, Download, Loader2 } from "@lucide/svelte";
  import Card from "$lib/components/ui/Card.svelte";
  import ModalCloseButton from "$lib/components/listings/ModalCloseButton.svelte";
  import ModalHeaderTitle from "$lib/components/listings/ModalHeaderTitle.svelte";
  import { getCollectionsContext } from "$lib/collections-context.svelte";
  import { getActiveOrganizationId } from "$lib/api/client";
  import { workspaceApi } from "$lib/workspace/client";
  import { toProperty } from "$lib/listings/types";
  import { formatListingForJsonExport } from "$lib/listings/listing-json";
  import { cn } from "$lib/utils";

  const EXPORT_FORMAT_VERSION = "2.0";

  let { isOpen, onClose } = $props<{ isOpen: boolean; onClose: () => void }>();

  const ctx = getCollectionsContext();

  let error = $state<string | null>(null);
  let success = $state<string | null>(null);
  let copySuccess = $state(false);
  let exportMode = $state<"current" | "all">("current");
  let isExporting = $state(false);

  $effect(() => {
    if (!isOpen) return;
    error = null;
    success = null;
    copySuccess = false;
    exportMode = "current";
  });

  async function getExportData() {
    if (exportMode === "current") {
      if (!ctx.activeCollection) throw new Error("Nenhuma coleção ativa");
      return JSON.stringify(
        {
          version: EXPORT_FORMAT_VERSION,
          exportedAt: new Date().toISOString(),
          context: getActiveOrganizationId() ? "organization" : "personal",
          collection: {
            id: ctx.activeCollection.id,
            name: ctx.activeCollection.name,
            createdAt: ctx.activeCollection.createdAt,
            updatedAt: ctx.activeCollection.updatedAt,
            isDefault: ctx.activeCollection.isDefault
          },
          listings: ctx.listings.map(formatListingForJsonExport)
        },
        null,
        2
      );
    }

    if (ctx.collections.length === 0) throw new Error("Nenhuma coleção para exportar");
    const collectionsWithListings = await Promise.all(
      ctx.collections.map(async (collection) => {
        const rows = (await workspaceApi.fetchListings(collection.id)).listings.map((listing) =>
          toProperty(listing)
        );
        return {
          collection: {
            id: collection.id,
            name: collection.name,
            createdAt: collection.createdAt,
            updatedAt: collection.updatedAt,
            isDefault: collection.isDefault
          },
          listings: rows.map(formatListingForJsonExport)
        };
      })
    );

    return JSON.stringify(
      {
        version: EXPORT_FORMAT_VERSION,
        exportedAt: new Date().toISOString(),
        context: getActiveOrganizationId() ? "organization" : "personal",
        collections: collectionsWithListings
      },
      null,
      2
    );
  }

  async function handleExport() {
    isExporting = true;
    error = null;
    success = null;
    try {
      const data = await getExportData();
      const blob = new Blob([data], { type: "application/json" });
      const url = URL.createObjectURL(blob);
      const anchor = document.createElement("a");
      anchor.href = url;
      anchor.download = `minha-casa-export-${new Date().toISOString().slice(0, 10)}.json`;
      anchor.click();
      URL.revokeObjectURL(url);
      success = "Exportação concluída!";
    } catch (err) {
      error = err instanceof Error ? err.message : "Erro ao exportar";
    } finally {
      isExporting = false;
    }
  }

  async function handleCopy() {
    isExporting = true;
    error = null;
    try {
      await navigator.clipboard.writeText(await getExportData());
      copySuccess = true;
      setTimeout(() => (copySuccess = false), 2000);
    } catch (err) {
      error = err instanceof Error ? err.message : "Erro ao copiar";
    } finally {
      isExporting = false;
    }
  }
</script>

{#if isOpen}
  <div class="fixed inset-0 z-[1000] flex items-center justify-center">
    <button type="button" class="absolute inset-0 bg-app-fg/80 backdrop-blur-sm" aria-label="Fechar" onclick={onClose}></button>
    <Card class="relative z-10 mx-4 w-full max-w-lg border-app-border bg-app-surface">
      <div class="flex items-center justify-between border-b border-app-border px-4 py-3">
        <ModalHeaderTitle icon={Download} title="Exportar" />
        <ModalCloseButton onclick={onClose} />
      </div>
      <div class="space-y-4 p-4">
        <div class="flex gap-2">
          <button type="button" class={cn("flex-1 rounded-lg border px-3 py-2 text-sm", exportMode === "current" ? "border-app-action bg-app-action/20 text-app-accent" : "border-app-border")} onclick={() => (exportMode = "current")}>
            Coleção atual
          </button>
          <button type="button" class={cn("flex-1 rounded-lg border px-3 py-2 text-sm", exportMode === "all" ? "border-app-action bg-app-action/20 text-app-accent" : "border-app-border")} onclick={() => (exportMode = "all")}>
            Todas
          </button>
        </div>
        {#if error}<p class="text-sm text-destructive">{error}</p>{/if}
        {#if success}<p class="text-sm text-app-accent">{success}</p>{/if}
        <div class="flex gap-2">
          <button type="button" class="flex flex-1 items-center justify-center gap-2 rounded-lg bg-app-action py-2.5 text-app-action-foreground" disabled={isExporting || (exportMode === "current" && ctx.listings.length === 0)} onclick={() => void handleExport()}>
            {#if isExporting}<Loader2 class="h-4 w-4 animate-spin" />{:else}<Download class="h-4 w-4" />{/if}
            Baixar JSON
          </button>
          <button type="button" class="flex flex-1 items-center justify-center gap-2 rounded-lg border border-app-border py-2.5" disabled={isExporting} onclick={() => void handleCopy()}>
            {#if copySuccess}<Check class="h-4 w-4" />{:else}<ClipboardList class="h-4 w-4" />{/if}
            Copiar
          </button>
        </div>
      </div>
    </Card>
  </div>
{/if}

// app/anuncios/components/export-modal.tsx
"use client"

import { useState, useEffect } from "react"
import { Check, ClipboardList, Download } from "lucide-react"
import { Card, CardContent, CardHeader } from "@/components/ui/card"
import { ModalCloseButton, ModalHeaderTitle, LoadingLabel } from "./modal-chrome"
import { Label } from "@/components/ui/label"
import { useCollections } from "../lib/use-collections"
import { fetchListings, type Imovel } from "../lib/api"
import { cn } from "@/lib/utils"

// Export format version for future compatibility
const EXPORT_FORMAT_VERSION = "1.0"

interface ExportModalProps {
  isOpen: boolean
  onClose: () => void
}

type ExportMode = "current" | "all"

export function ExportModal({
  isOpen,
  onClose,
}: ExportModalProps) {
  const { activeCollection, listings, collections, orgContext } = useCollections()
  
  const [error, setError] = useState<string | null>(null)
  const [success, setSuccess] = useState<string | null>(null)
  const [copySuccess, setCopySuccess] = useState(false)
  const [exportMode, setExportMode] = useState<ExportMode>("current")
  const [isExporting, setIsExporting] = useState(false)

  useEffect(() => {
    if (isOpen) {
      setError(null)
      setSuccess(null)
      setCopySuccess(false)
      setExportMode("current")
    }
  }, [isOpen])

  const formatListingForExport = (listing: Imovel) => ({
    id: listing.id,
    titulo: listing.titulo,
    endereco: listing.endereco,
    m2Totais: listing.m2Totais,
    m2Privado: listing.m2Privado,
    quartos: listing.quartos,
    suites: listing.suites,
    banheiros: listing.banheiros,
    garagem: listing.garagem,
    preco: listing.preco,
    precoM2: listing.precoM2,
    piscina: listing.piscina,
    porteiro24h: listing.porteiro24h,
    academia: listing.academia,
    vistaLivre: listing.vistaLivre,
    piscinaTermica: listing.piscinaTermica,
    andar: listing.andar,
    tipoImovel: listing.tipoImovel,
    link: listing.link,
    imageUrl: listing.imageUrl,
    contactName: listing.contactName,
    contactNumber: listing.contactNumber,
    starred: listing.starred,
    visited: listing.visited,
    strikethrough: listing.strikethrough,
    discardedReason: listing.discardedReason,
    customLat: listing.customLat,
    customLng: listing.customLng,
    createdAt: listing.createdAt,
    addedAt: listing.addedAt,
  })

  const getExportData = async (): Promise<string> => {
    if (exportMode === "current") {
      if (!activeCollection) {
        throw new Error("Nenhuma coleção ativa")
      }

      return JSON.stringify(
        {
          version: EXPORT_FORMAT_VERSION,
          exportedAt: new Date().toISOString(),
          context: orgContext.type,
          collection: {
            id: activeCollection.id,
            label: activeCollection.label,
            name: activeCollection.label,
            createdAt: activeCollection.createdAt,
            updatedAt: activeCollection.updatedAt,
            isDefault: activeCollection.isDefault,
          },
          listings: listings.map(formatListingForExport),
        },
        null,
        2
      )
    } else {
      // Export all collections
      if (collections.length === 0) {
        throw new Error("Nenhuma coleção para exportar")
      }

      const collectionsWithListings = await Promise.all(
        collections.map(async (collection) => {
          const collectionListings = await fetchListings(collection.id)
          return {
            collection: {
              id: collection.id,
              label: collection.label,
              name: collection.label,
              createdAt: collection.createdAt,
              updatedAt: collection.updatedAt,
              isDefault: collection.isDefault,
            },
            listings: collectionListings.map(formatListingForExport),
          }
        })
      )

      return JSON.stringify(
        {
          version: EXPORT_FORMAT_VERSION,
          exportedAt: new Date().toISOString(),
          context: orgContext.type,
          collections: collectionsWithListings,
        },
        null,
        2
      )
    }
  }

  const handleDownloadJson = async () => {
    setIsExporting(true)
    try {
      const json = await getExportData()
      const date = new Date().toISOString().split("T")[0]
      const filename = exportMode === "current"
        ? `anuncios-${activeCollection?.label || "colecao"}-${date}.json`
        : `anuncios-backup-completo-${date}.json`

      const blob = new Blob([json], { type: "application/json" })
      const url = URL.createObjectURL(blob)
      const a = document.createElement("a")
      a.href = url
      a.download = filename
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)

      setSuccess("Arquivo baixado com sucesso!")
      setTimeout(() => setSuccess(null), 3000)
    } catch (err) {
      setError(err instanceof Error ? err.message : "Erro ao exportar")
    } finally {
      setIsExporting(false)
    }
  }

  const handleCopyToClipboard = async () => {
    setIsExporting(true)
    try {
      const json = await getExportData()
      await navigator.clipboard.writeText(json)
      setCopySuccess(true)
      setSuccess("JSON copiado para a área de transferência!")
      setTimeout(() => {
        setCopySuccess(false)
        setSuccess(null)
      }, 3000)
    } catch {
      setError("Erro ao copiar para a área de transferência")
    } finally {
      setIsExporting(false)
    }
  }

  const getTotalListings = () => {
    if (exportMode === "current") {
      return listings.length
    }
    // For "all" mode, we can't know the total without fetching all collections
    return null
  }

  const canExport = exportMode === "current"
    ? activeCollection && listings.length > 0
    : collections.length > 0

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 z-[1000] flex items-center justify-center">
      <div
        className="absolute inset-0 bg-app-fg/80 backdrop-blur-sm"
        onClick={onClose}
      />

      <Card className="relative z-10 w-full max-w-md mx-4 bg-app-surface border-app-border max-h-[90vh] overflow-y-auto">
        <CardHeader className="flex flex-row items-center justify-between pb-2">
          <ModalHeaderTitle icon={Download} title="Exportar" />
          <ModalCloseButton onClick={onClose} />
        </CardHeader>
        <CardContent className="space-y-4">
          {/* Export Mode Selection */}
          <div className="space-y-2">
            <Label className="text-sm text-app-muted">O que exportar</Label>
            <div className="flex gap-2">
              <button
                onClick={() => setExportMode("current")}
                disabled={isExporting}
                className={cn(
                  "flex-1 py-2 px-3 rounded-lg text-sm font-medium transition-all",
                  "border",
                  exportMode === "current"
                    ? "bg-app-action/20 border-app-action text-app-accent"
                    : "bg-app-surface-muted border-app-border hover:border-app-surface"
                )}
              >
                Coleção atual
              </button>
              <button
                onClick={() => setExportMode("all")}
                disabled={isExporting}
                className={cn(
                  "flex-1 py-2 px-3 rounded-lg text-sm font-medium transition-all",
                  "border",
                  exportMode === "all"
                    ? "bg-app-action/20 border-app-action text-app-accent"
                    : "bg-app-surface-muted border-app-border hover:border-app-surface"
                )}
              >
                Todas as coleções
              </button>
            </div>
          </div>

          <div className="space-y-2">
            <p className="text-xs text-muted-foreground">
              {exportMode === "current" ? (
                <>
                  Baixe um arquivo JSON ou copie os dados para a área de transferência.
                  {activeCollection && (
                    <>
                      <br />
                      Coleção: <span className="text-app-fg">{activeCollection.label}</span> ({getTotalListings()} imóveis)
                    </>
                  )}
                </>
              ) : (
                <>
                  Exporta todas as {collections.length} coleções com seus imóveis para backup.
                </>
              )}
            </p>
          </div>

          <div className="flex flex-col sm:flex-row gap-3">
            <button
              onClick={handleDownloadJson}
              disabled={!canExport || isExporting}
              className={cn(
                "flex-1 py-2.5 px-4 rounded-lg font-medium transition-all",
                "bg-app-action text-app-action-foreground",
                "hover:bg-app-action-hover",
                "disabled:opacity-50 disabled:cursor-not-allowed",
                "flex items-center justify-center gap-2"
              )}
            >
              {isExporting ? (
                <LoadingLabel label="Exportando..." />
              ) : (
                <>
                  <Download className="h-4 w-4" />
                  Baixar JSON
                </>
              )}
            </button>
            <button
              onClick={handleCopyToClipboard}
              disabled={!canExport || isExporting}
              className={cn(
                "flex-1 py-2.5 px-4 rounded-lg font-medium transition-all",
                "bg-app-surface-muted border border-app-border",
                "hover:border-app-action hover:text-app-accent",
                "disabled:opacity-50 disabled:cursor-not-allowed",
                "flex items-center justify-center gap-2",
                copySuccess && "border-green text-green"
              )}
            >
              {copySuccess ? (
                <Check className="h-4 w-4" />
              ) : (
                <ClipboardList className="h-4 w-4" />
              )}
              {copySuccess ? "Copiado!" : "Copiar JSON"}
            </button>
          </div>

          {error && (
            <div className="p-3 rounded-lg bg-destructive/10 border border-destructive/30">
              <p className="text-sm text-destructive">{error}</p>
            </div>
          )}
          {success && (
            <div className="p-3 rounded-lg bg-green/10 border border-green/30">
              <p className="text-sm text-green">{success}</p>
            </div>
          )}

          <div className="pt-4 border-t border-app-border">
            <button
              onClick={onClose}
              disabled={isExporting}
              className={cn(
                "w-full py-2.5 px-4 rounded-lg font-medium transition-all",
                "bg-app-surface-muted border border-app-border",
                "hover:border-app-surface",
                "disabled:opacity-50"
              )}
            >
              Fechar
            </button>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
