// apps/web/src/lib/components/listings/ListingsMap.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { Building2, Map as MapIcon, Palette, RotateCw } from "@lucide/svelte";
  import type { Property } from "$lib/listings/types";
  import { geocodeAddresses, clearCacheForAddresses } from "$lib/listings/geocoding";
  import { buildListingGeocodeQuery } from "$lib/listings/listing-location";
  import { ensureGoogleMapsLoaded } from "$lib/listings/google-maps-loader";
  import { cn } from "$lib/utils";
  import {
    calculatePricePerM2,
    getEffectiveMapProvider,
    getStoredColorByPrice,
    setStoredColorByPrice,
    setStoredMapProvider,
    type GeocodedListing
  } from "$lib/listings/map-shared";
  import {
    isGoogleMapsApiKeyConfigured,
    subscribeToGoogleMapsErrors
  } from "$lib/listings/google-maps-config";
  import {
    DEFAULT_MAP_VIEWPORT,
    clearStoredMapViewport,
    getStoredMapViewport,
    hasUserMapViewportFeature,
    viewportFromListingsBounds,
    type MapViewport
  } from "$lib/listings/map-viewport";
  import {
    LISTINGS_MAP_CONTENT_CLASS,
    LISTINGS_MAP_LEGEND_OVERLAY_CLASS,
    LISTINGS_MAP_LEGEND_OVERLAY_GOOGLE_CLASS,
    LISTINGS_MAP_SECTION_CLASS,
    LISTINGS_TOOLBAR_CLASS,
    LISTINGS_TOOLBAR_INNER_CLASS,
    MAP_FLOATING_UI_Z_CLASS,
    MAP_FLOATING_UI_Z_INDEX
  } from "$lib/listings/listings-panel-layout";
  import { mapPriceColors } from "$lib/theme/colors";
  import PageToolbarIconButton from "$lib/components/page-toolbar/PageToolbarIconButton.svelte";
  import Switch from "$lib/components/ui/Switch.svelte";
  import MapLocationPicker from "$lib/components/listings/MapLocationPicker.svelte";
  import ToolbarAnchoredPopover from "$lib/components/listings/ToolbarAnchoredPopover.svelte";
  import LeafletMapView from "$lib/components/listings/LeafletMapView.svelte";
  import GoogleMapsView from "$lib/components/listings/GoogleMapsView.svelte";
  import ListingsThreeMapView from "$lib/components/listings/ListingsThreeMapView.svelte";

  let {
    listings,
    collectionLabel = "Coleção atual",
    getListingTitle = (listing: Property) => listing.title || listing.address || "Imóvel"
  } = $props<{
    listings: Property[];
    collectionLabel?: string;
    getListingTitle?: (listing: Property) => string;
  }>();

  let mounted = $state(false);
  let geocodedListings = $state<GeocodedListing[]>([]);
  let isLoading = $state(false);
  let progress = $state({ completed: 0, total: 0 });
  let geocodeKey = $state(0);
  let mapProvider = $state<"google" | "leaflet">("google");
  let colorByPrice = $state(false);
  let mapViewport = $state(DEFAULT_MAP_VIEWPORT);
  let boundsApplied = $state(false);
  let missingPopoverOpen = $state(false);
  let mapPresentation = $state<"map" | "3d">("map");

  const googleMapsAvailable = $derived(isGoogleMapsApiKeyConfigured());

  onMount(() => {
    mounted = true;
    mapProvider = getEffectiveMapProvider();
    colorByPrice = getStoredColorByPrice();
    const stored = getStoredMapViewport();
    if (stored && (stored.source === "city" || stored.source === "state")) {
      mapViewport = stored;
      boundsApplied = true;
    }
    return subscribeToGoogleMapsErrors(() => {
      mapProvider = "leaflet";
      setStoredMapProvider("leaflet");
    });
  });

  $effect(() => {
    if (!mounted || listings.length === 0) {
      geocodedListings = [];
      return;
    }

    void geocodeKey;
    let cancelled = false;

    void (async () => {
      isLoading = true;
      const withCustom: GeocodedListing[] = [];
      const toGeocode: Property[] = [];

      for (const listing of listings) {
        if (listing.customLat != null && listing.customLng != null) {
          withCustom.push({
            listing,
            location: { lat: listing.customLat, lng: listing.customLng, displayName: listing.address }
          });
        } else {
          toGeocode.push(listing);
        }
      }

      if (toGeocode.length > 0) {
        progress = { completed: withCustom.length, total: listings.length };
        const addressInputs = toGeocode
          .map((l) => {
            const query = buildListingGeocodeQuery(l);
            return query ? { address: query, city: l.city } : null;
          })
          .filter((input): input is { address: string; city: string | null | undefined } => input !== null);

        if (googleMapsAvailable) {
          try {
            await ensureGoogleMapsLoaded();
          } catch {
            // Geocoding falls back to Nominatim when Google is unavailable.
          }
        }

        const results = await geocodeAddresses(addressInputs, (completed) => {
          if (!cancelled) {
            progress = { completed: withCustom.length + completed, total: listings.length };
          }
        });

        if (cancelled) return;

        const geocoded = [...withCustom];
        for (const listing of toGeocode) {
          const query = buildListingGeocodeQuery(listing);
          const location = query ? results.get(query) : null;
          if (location) geocoded.push({ listing, location });
        }
        geocodedListings = geocoded;
      } else {
        geocodedListings = withCustom;
      }
      isLoading = false;
    })();

    return () => {
      cancelled = true;
    };
  });

  $effect(() => {
    if (!mounted || isLoading || geocodedListings.length === 0 || boundsApplied || hasUserMapViewportFeature()) return;
    const boundsViewport = viewportFromListingsBounds(geocodedListings);
    if (!boundsViewport) return;
    boundsApplied = true;
    mapViewport = boundsViewport;
  });

  const minMaxPreco = $derived.by(() => {
    const prices = geocodedListings
      .map((gl) => calculatePricePerM2(gl.listing.price, gl.listing.totalAreaM2))
      .filter((p): p is number => p !== null);
    if (prices.length === 0) return { minPreco: 0, maxPreco: 0 };
    return { minPreco: Math.min(...prices), maxPreco: Math.max(...prices) };
  });

  const missingListings = $derived.by(() => {
    if (isLoading) return [];
    const ids = new Set(geocodedListings.map((gl) => gl.listing.id));
    return listings.filter((listing: Property) => !ids.has(listing.id));
  });

  const countLabel = $derived(
    isLoading
      ? `Geocodificando... ${progress.completed}/${progress.total}`
      : `${geocodedListings.length} de ${listings.length} no mapa`
  );

  const mapViewProps = $derived({
    geocodedListings,
    minPreco: minMaxPreco.minPreco,
    maxPreco: minMaxPreco.maxPreco,
    mapViewport,
    colorByPrice
  });

  function handleColorByPriceToggle() {
    colorByPrice = !colorByPrice;
    setStoredColorByPrice(colorByPrice);
  }

  function handleProviderChange(checked: boolean) {
    const next = checked ? "google" : "leaflet";
    if (next === "google" && !googleMapsAvailable) return;
    mapProvider = next;
    setStoredMapProvider(next);
  }

  function handleRedoGeocoding() {
    const addressInputs: { address: string; city: string | null | undefined }[] = [];
    for (const listing of listings) {
      const query = buildListingGeocodeQuery(listing);
      if (query) addressInputs.push({ address: query, city: listing.city });
    }
    clearCacheForAddresses(addressInputs);
    boundsApplied = false;
    geocodeKey += 1;
  }

  function handleAutomaticView() {
    const boundsViewport = viewportFromListingsBounds(geocodedListings);
    if (!boundsViewport) return;
    clearStoredMapViewport();
    boundsApplied = true;
    mapViewport = boundsViewport;
  }

  function handleViewportChange(next: MapViewport) {
    boundsApplied = true;
    mapViewport = next;
  }
</script>

{#if mounted && listings.length > 0}
  <section class={LISTINGS_MAP_SECTION_CLASS}>
    <div class={cn(LISTINGS_TOOLBAR_CLASS, "relative z-20 shrink-0")}>
      <div class={cn(LISTINGS_TOOLBAR_INNER_CLASS, "justify-between")}>
        <div class="flex min-w-0 flex-1 items-center gap-1.5">
          {#if mapPresentation === "map"}
            <MapLocationPicker
              viewport={mapViewport}
              onViewportChange={handleViewportChange}
              onAutomaticView={handleAutomaticView}
              automaticDisabled={isLoading || geocodedListings.length === 0}
              isAutomaticActive={mapViewport.source === "listings-bounds"}
              disabled={isLoading}
            />
            <PageToolbarIconButton
              variant={colorByPrice ? "active" : "secondary"}
              onclick={handleColorByPriceToggle}
              disabled={isLoading}
              aria-pressed={colorByPrice}
              aria-label="Colorir marcadores por preço/m²"
              title={colorByPrice ? "Ocultar cores por preço/m²" : "Colorir por preço/m²"}
            >
              <Palette />
            </PageToolbarIconButton>
          {/if}
        </div>

        <div class="flex shrink-0 items-center gap-1.5">
          <div class="flex shrink-0 items-center rounded-md border border-app-border bg-app-bg p-0.5" aria-label="Tipo de mapa">
            <button
              type="button"
              class={cn("inline-flex h-6 items-center gap-1 rounded px-2 text-xs font-medium transition-colors", mapPresentation === "map" ? "bg-app-surface text-app-fg shadow-sm" : "text-app-muted hover:text-app-fg")}
              aria-pressed={mapPresentation === "map"}
              onclick={() => (mapPresentation = "map")}
            ><MapIcon class="size-3" /> Mapa</button>
            <button
              type="button"
              class={cn("inline-flex h-6 items-center gap-1 rounded px-2 text-xs font-medium transition-colors", mapPresentation === "3d" ? "bg-app-surface text-app-fg shadow-sm" : "text-app-muted hover:text-app-fg")}
              aria-pressed={mapPresentation === "3d"}
              onclick={() => (mapPresentation = "3d")}
            ><Building2 class="size-3" /> 3D</button>
          </div>

          {#if mapPresentation === "map"}
            <div role="separator" aria-orientation="vertical" class="mx-0.5 h-4 w-px shrink-0 bg-app-border"></div>
            <div class="flex shrink-0 items-center gap-1 text-xs">
              <span class={cn("whitespace-nowrap transition-colors", mapProvider === "leaflet" ? "text-app-fg" : "text-app-muted")}>OSM</span>
              <Switch checked={mapProvider === "google"} disabled={!googleMapsAvailable} class="scale-75" onCheckedChange={handleProviderChange} />
              <span class={cn("whitespace-nowrap transition-colors", mapProvider === "google" ? "text-app-fg" : "text-app-muted")}>Google</span>
            </div>
          {/if}

          <div role="separator" aria-orientation="vertical" class="mx-0.5 h-4 w-px shrink-0 bg-app-border"></div>

          {#if isLoading}
            <span class="hidden shrink-0 whitespace-nowrap text-xs text-muted-foreground sm:inline">
              {countLabel}
            </span>
          {:else if missingListings.length > 0}
            <ToolbarAnchoredPopover
              bind:open={missingPopoverOpen}
              align="auto"
              offsetClass="mt-1"
              panelClass="w-72 max-w-md p-2"
              mapFloating
            >
              {#snippet trigger()}
                <button
                  type="button"
                  class="hidden shrink-0 cursor-help whitespace-nowrap text-xs text-muted-foreground sm:inline"
                  aria-expanded={missingPopoverOpen}
                  onclick={() => (missingPopoverOpen = !missingPopoverOpen)}
                >
                  {countLabel}
                </button>
              {/snippet}
              <p class="mb-2 text-xs font-semibold">
                Endereços não adicionados ao mapa ({missingListings.length}):
              </p>
              <ul class="list-inside list-disc space-y-1 text-xs">
                {#each missingListings as listing (listing.id)}
                  <li>{listing.address || listing.title}</li>
                {/each}
              </ul>
            </ToolbarAnchoredPopover>
          {:else}
            <span class="hidden shrink-0 whitespace-nowrap text-xs text-muted-foreground sm:inline">
              {countLabel}
            </span>
          {/if}

          <PageToolbarIconButton
            variant="secondary"
            onclick={handleRedoGeocoding}
            disabled={isLoading}
            aria-label="Re-geocodificar todos os endereços"
            title="Re-geocodificar endereços"
          >
            <RotateCw class={cn(isLoading && "animate-spin")} />
          </PageToolbarIconButton>
        </div>
      </div>
    </div>

    <div class={LISTINGS_MAP_CONTENT_CLASS}>
      {#if isLoading && geocodedListings.length === 0}
        <div class="flex h-[400px] flex-col items-center justify-center bg-app-bg">
          <div class="mb-4 h-8 w-8 animate-spin rounded-full border-b-2 border-app-action"></div>
          <p class="text-app-muted">
            Geocodificando endereços... {progress.completed}/{progress.total}
          </p>
          <p class="mt-1 text-xs text-muted-foreground">
            {mapProvider === "google"
              ? "(Usando Google Maps para maior precisão)"
              : "(Usando OpenStreetMap)"}
          </p>
        </div>
      {:else if geocodedListings.length === 0}
        <div class="flex h-[400px] items-center justify-center bg-app-bg">
          <p class="text-app-muted">Nenhum endereço pôde ser localizado no mapa.</p>
        </div>
      {:else if mapPresentation === "3d"}
        <ListingsThreeMapView
          {geocodedListings}
          {collectionLabel}
          getTitle={getListingTitle}
        />
      {:else if mapProvider === "google"}
        <GoogleMapsView {...mapViewProps} />
      {:else}
        <LeafletMapView {...mapViewProps} />
      {/if}

      {#if mapPresentation === "map" && geocodedListings.length > 0 && colorByPrice}
        <div
          class={cn(
            LISTINGS_MAP_LEGEND_OVERLAY_CLASS,
            MAP_FLOATING_UI_Z_CLASS,
            mapProvider === "google" && LISTINGS_MAP_LEGEND_OVERLAY_GOOGLE_CLASS
          )}
          style={`z-index: ${MAP_FLOATING_UI_Z_INDEX}`}
        >
          <span class="whitespace-nowrap">Preço/m²:</span>
          {#each [
            { label: "Baixo", color: mapPriceColors.low },
            { label: "Médio", color: mapPriceColors.medium },
            { label: "Alto", color: mapPriceColors.high },
            { label: "Muito Alto", color: mapPriceColors.veryHigh }
          ] as item (item.label)}
            <div class="flex items-center gap-1">
              <div class="h-2.5 w-2.5 rounded-full" style:background-color={item.color}></div>
              <span>{item.label}</span>
            </div>
          {/each}
        </div>
      {/if}
    </div>
  </section>
{/if}

// app/anuncios/components/listings-map.tsx
"use client"

import { useEffect, useState, useMemo, useRef, useSyncExternalStore } from "react"
import { Switch } from "@/components/ui/switch"
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip"
import type { Imovel } from "../lib/api"
import { geocodeAddresses, clearCacheForAddresses } from "../lib/geocoding"
import { buildListingGeocodeQuery } from "../lib/listing-location"
import { Palette, RotateCw } from "lucide-react"
import { cn } from "@/lib/utils"
import {
  type GeocodedListing,
  type MapProvider,
  type MapViewport,
  calculatePrecoM2,
  getEffectiveMapProvider,
  getStoredColorByPrice,
  setStoredColorByPrice,
  setStoredMapProvider,
} from "./map-shared"
import {
  isGoogleMapsApiKeyConfigured,
  subscribeToGoogleMapsErrors,
} from "../lib/google-maps-config"
import {
  DEFAULT_MAP_VIEWPORT,
  clearStoredMapViewport,
  getStoredMapViewport,
  hasUserMapViewportPreference,
  viewportFromListingsBounds,
} from "../lib/map-viewport"
import { LeafletMapView } from "./leaflet-map-view"
import { GoogleMapsView } from "./google-maps-view"
import { MapLocationPicker } from "./map-location-picker"
import {
  LISTINGS_MAP_CONTENT_CLASS,
  LISTINGS_MAP_LEGEND_OVERLAY_CLASS,
  LISTINGS_MAP_LEGEND_OVERLAY_GOOGLE_CLASS,
  LISTINGS_MAP_SECTION_CLASS,
  LISTINGS_TOOLBAR_CLASS,
  LISTINGS_TOOLBAR_INNER_CLASS,
  MAP_FLOATING_UI_Z_CLASS,
  MAP_FLOATING_UI_Z_INDEX,
} from "./listings-panel-layout"
import { PageToolbarIconButton } from "@/app/components/page-toolbar"
import { mapPriceColors } from "@/lib/theme/colors"

interface ListingsMapProps {
  listings: Imovel[]
}

function MapPriceM2Legend() {
  return (
    <>
      <span className="whitespace-nowrap">Preço/m²:</span>
      {(
        [
          ["Baixo", mapPriceColors.low],
          ["Médio", mapPriceColors.medium],
          ["Alto", mapPriceColors.high],
          ["Muito Alto", mapPriceColors.veryHigh],
        ] as const
      ).map(([label, color]) => (
        <div key={label} className="flex items-center gap-1">
          <div
            className="h-2.5 w-2.5 rounded-full"
            style={{ backgroundColor: color }}
          />
          <span>{label}</span>
        </div>
      ))}
    </>
  )
}

export function ListingsMap({ listings }: ListingsMapProps) {
  const [geocodedListings, setGeocodedListings] = useState<GeocodedListing[]>([])
  const [isLoading, setIsLoading] = useState(false)
  const [progress, setProgress] = useState({ completed: 0, total: 0 })
  const mounted = useSyncExternalStore(
    () => () => {},
    () => true,
    () => false
  )
  const [geocodeKey, setGeocodeKey] = useState(0)
  const [mapProvider, setMapProvider] = useState<MapProvider>("google")
  const [colorByPrice, setColorByPrice] = useState(false)
  const [mapViewport, setMapViewport] = useState<MapViewport>(DEFAULT_MAP_VIEWPORT)
  const boundsAppliedRef = useRef(false)
  const prefsHydratedRef = useRef(false)

  useEffect(() => {
    if (!mounted || prefsHydratedRef.current) return
    prefsHydratedRef.current = true

    queueMicrotask(() => {
      setMapProvider(getEffectiveMapProvider())
      setColorByPrice(getStoredColorByPrice())

      const stored = getStoredMapViewport()
      if (stored && (stored.source === "city" || stored.source === "state")) {
        setMapViewport(stored)
        boundsAppliedRef.current = true
      }
    })
  }, [mounted])

  useEffect(() => {
    if (!mounted) return
    return subscribeToGoogleMapsErrors(() => {
      setMapProvider("leaflet")
      setStoredMapProvider("leaflet")
    })
  }, [mounted])

  const handleColorByPriceToggle = () => {
    setColorByPrice((prev) => {
      const next = !prev
      setStoredColorByPrice(next)
      return next
    })
  }

  const handleProviderChange = (checked: boolean) => {
    const newProvider: MapProvider = checked ? "google" : "leaflet"
    if (newProvider === "google" && !isGoogleMapsApiKeyConfigured()) {
      return
    }
    setMapProvider(newProvider)
    setStoredMapProvider(newProvider)
  }

  const googleMapsAvailable = isGoogleMapsApiKeyConfigured()

  useEffect(() => {
    if (!mounted || listings.length === 0) {
      queueMicrotask(() => {
        setGeocodedListings((current) => (current.length === 0 ? current : []))
      })
      return
    }

    const geocodeAll = async () => {
      setIsLoading(true)

      const listingsWithCustom: GeocodedListing[] = []
      const listingsToGeocode: Imovel[] = []

      for (const listing of listings) {
        if (
          listing.customLat !== null &&
          listing.customLat !== undefined &&
          listing.customLng !== null &&
          listing.customLng !== undefined
        ) {
          listingsWithCustom.push({
            listing,
            location: {
              lat: listing.customLat,
              lng: listing.customLng,
              displayName: listing.endereco,
            },
          })
        } else {
          listingsToGeocode.push(listing)
        }
      }

      if (listingsToGeocode.length > 0) {
        setProgress({ completed: listingsWithCustom.length, total: listings.length })

        const addressInputs = listingsToGeocode
          .map((l) => {
            const query = buildListingGeocodeQuery(l)
            return query ? { address: query, cidade: l.cidade } : null
          })
          .filter(
            (input): input is { address: string; cidade: string | null | undefined } =>
              input !== null
          )
        const results = await geocodeAddresses(addressInputs, (completed) => {
          setProgress({
            completed: listingsWithCustom.length + completed,
            total: listings.length,
          })
        })

        const geocoded: GeocodedListing[] = [...listingsWithCustom]
        for (const listing of listingsToGeocode) {
          const query = buildListingGeocodeQuery(listing)
          const location = query ? results.get(query) : null
          if (location) {
            geocoded.push({ listing, location })
          }
        }

        setGeocodedListings(geocoded)
      } else {
        setGeocodedListings(listingsWithCustom)
      }

      setIsLoading(false)
    }

    geocodeAll()
  }, [listings, mounted, geocodeKey])

  useEffect(() => {
    if (
      !mounted ||
      isLoading ||
      geocodedListings.length === 0 ||
      boundsAppliedRef.current ||
      hasUserMapViewportPreference()
    ) {
      return
    }

    const boundsViewport = viewportFromListingsBounds(geocodedListings)
    if (!boundsViewport) return

    boundsAppliedRef.current = true
    queueMicrotask(() => setMapViewport(boundsViewport))
  }, [mounted, isLoading, geocodedListings])

  const { minPreco, maxPreco } = useMemo(() => {
    const prices = geocodedListings
      .map((gl) => calculatePrecoM2(gl.listing.preco, gl.listing.m2Totais))
      .filter((p): p is number => p !== null)

    if (prices.length === 0) return { minPreco: 0, maxPreco: 0 }

    return {
      minPreco: Math.min(...prices),
      maxPreco: Math.max(...prices),
    }
  }, [geocodedListings])

  const missingListings = useMemo(() => {
    if (isLoading) return []
    const geocodedIds = new Set(geocodedListings.map((gl) => gl.listing.id))
    return listings.filter((listing) => !geocodedIds.has(listing.id))
  }, [listings, geocodedListings, isLoading])

  const handleRedoGeocoding = () => {
    const addresses = listings
      .map((listing) => buildListingGeocodeQuery(listing))
      .filter((query): query is string => Boolean(query))
    clearCacheForAddresses(addresses)
    boundsAppliedRef.current = false
    setGeocodeKey((prev) => prev + 1)
  }

  const handleViewportChange = (viewport: MapViewport) => {
    boundsAppliedRef.current = true
    setMapViewport(viewport)
  }

  const handleAutomaticView = () => {
    const boundsViewport = viewportFromListingsBounds(geocodedListings)
    if (!boundsViewport) return
    clearStoredMapViewport()
    boundsAppliedRef.current = true
    setMapViewport(boundsViewport)
  }

  if (!mounted) {
    return null
  }

  if (listings.length === 0) {
    return null
  }

  const mapViewProps = {
    geocodedListings,
    minPreco,
    maxPreco,
    mapViewport,
    colorByPrice,
  }

  const countLabel = isLoading
    ? `Geocodificando... ${progress.completed}/${progress.total}`
    : `${geocodedListings.length} de ${listings.length} no mapa`

  return (
    <section className={LISTINGS_MAP_SECTION_CLASS}>
      <div className={cn(LISTINGS_TOOLBAR_CLASS, "relative z-20 shrink-0")}>
        <div className={cn(LISTINGS_TOOLBAR_INNER_CLASS, "justify-between")}>
          <div className="flex min-w-0 flex-1 items-center gap-1.5">
            <MapLocationPicker
              viewport={mapViewport}
              onViewportChange={handleViewportChange}
              onAutomaticView={handleAutomaticView}
              automaticDisabled={isLoading || geocodedListings.length === 0}
              isAutomaticActive={mapViewport.source === "listings-bounds"}
              disabled={isLoading}
            />

            <Tooltip>
              <TooltipTrigger asChild>
                <PageToolbarIconButton
                  variant={colorByPrice ? "active" : "secondary"}
                  onClick={handleColorByPriceToggle}
                  disabled={isLoading}
                  aria-pressed={colorByPrice}
                  aria-label="Colorir marcadores por preço/m²"
                >
                  <Palette />
                </PageToolbarIconButton>
              </TooltipTrigger>
              <TooltipContent
                side="bottom"
                sideOffset={4}
                style={{ zIndex: MAP_FLOATING_UI_Z_INDEX }}
                className={cn(
                  "border border-app-border bg-app-surface text-app-fg",
                  MAP_FLOATING_UI_Z_CLASS
                )}
              >
                {colorByPrice ? "Ocultar cores por preço/m²" : "Colorir por preço/m²"}
              </TooltipContent>
            </Tooltip>
          </div>

          <div className="flex shrink-0 items-center gap-1.5">
          <div className="flex shrink-0 items-center gap-1 text-xs">
            <span
              className={cn(
                "whitespace-nowrap transition-colors",
                mapProvider === "leaflet" ? "text-app-fg" : "text-app-muted"
              )}
            >
              OSM
            </span>
            <Switch
              checked={mapProvider === "google"}
              onCheckedChange={handleProviderChange}
              disabled={!googleMapsAvailable}
              className="scale-75 data-[state=checked]:bg-app-action"
            />
            <span
              className={cn(
                "whitespace-nowrap transition-colors",
                mapProvider === "google" ? "text-app-fg" : "text-app-muted"
              )}
            >
              Google
            </span>
          </div>

          <div
            role="separator"
            aria-orientation="vertical"
            className="mx-0.5 h-4 w-px shrink-0 bg-app-border"
          />

          {isLoading ? (
            <span className="hidden shrink-0 whitespace-nowrap text-xs text-muted-foreground sm:inline">
              {countLabel}
            </span>
          ) : missingListings.length > 0 ? (
            <Tooltip>
              <TooltipTrigger asChild>
                <span className="hidden shrink-0 cursor-help whitespace-nowrap text-xs text-muted-foreground sm:inline">
                  {countLabel}
                </span>
              </TooltipTrigger>
              <TooltipContent
                side="bottom"
                sideOffset={4}
                style={{ zIndex: MAP_FLOATING_UI_Z_INDEX }}
                className={cn(
                  "max-w-md border border-app-border bg-app-surface text-app-fg",
                  MAP_FLOATING_UI_Z_CLASS
                )}
              >
                <div className="space-y-1">
                  <p className="mb-2 font-semibold">
                    Endereços não adicionados ao mapa ({missingListings.length}):
                  </p>
                  <ul className="list-inside list-disc space-y-1 text-xs">
                    {missingListings.map((listing) => (
                      <li key={listing.id}>
                        {listing.endereco || listing.titulo}
                      </li>
                    ))}
                  </ul>
                </div>
              </TooltipContent>
            </Tooltip>
          ) : (
            <span className="hidden shrink-0 whitespace-nowrap text-xs text-muted-foreground sm:inline">
              {countLabel}
            </span>
          )}

          <Tooltip>
            <TooltipTrigger asChild>
              <PageToolbarIconButton
                variant="secondary"
                onClick={handleRedoGeocoding}
                disabled={isLoading}
                aria-label="Re-geocodificar todos os endereços"
              >
                <RotateCw className={cn(isLoading && "animate-spin")} />
              </PageToolbarIconButton>
            </TooltipTrigger>
            <TooltipContent
              side="bottom"
              sideOffset={4}
              style={{ zIndex: MAP_FLOATING_UI_Z_INDEX }}
              className={cn(
                "border border-app-border bg-app-surface text-app-fg",
                MAP_FLOATING_UI_Z_CLASS
              )}
            >
              Re-geocodificar endereços
            </TooltipContent>
          </Tooltip>
          </div>
        </div>
      </div>

      <div className={LISTINGS_MAP_CONTENT_CLASS}>
        {isLoading && geocodedListings.length === 0 ? (
          <div className="flex h-[400px] flex-col items-center justify-center bg-app-bg">
            <div className="mb-4 h-8 w-8 animate-spin rounded-full border-b-2 border-app-action" />
            <p className="text-app-muted">
              Geocodificando endereços... {progress.completed}/{progress.total}
            </p>
            <p className="mt-1 text-xs text-muted-foreground">
              {mapProvider === "google"
                ? "(Usando Google Maps para maior precisão)"
                : "(Usando OpenStreetMap)"}
            </p>
          </div>
        ) : geocodedListings.length === 0 ? (
          <div className="flex h-[400px] items-center justify-center bg-app-bg">
            <p className="text-app-muted">Nenhum endereço pôde ser localizado no mapa.</p>
          </div>
        ) : mapProvider === "google" ? (
          <GoogleMapsView {...mapViewProps} />
        ) : (
          <LeafletMapView {...mapViewProps} />
        )}

        {geocodedListings.length > 0 && colorByPrice && (
          <div
            className={cn(
              LISTINGS_MAP_LEGEND_OVERLAY_CLASS,
              MAP_FLOATING_UI_Z_CLASS,
              mapProvider === "google" && LISTINGS_MAP_LEGEND_OVERLAY_GOOGLE_CLASS
            )}
          >
            <MapPriceM2Legend />
          </div>
        )}
      </div>
    </section>
  )
}
