// apps/web/src/lib/components/anuncios/ShareCollectionModal.svelte
<script lang="ts">
  import { Check, Link2, Loader2, Lock } from "@lucide/svelte";
  import Card from "$lib/components/ui/Card.svelte";
  import ModalCloseButton from "$lib/components/anuncios/ModalCloseButton.svelte";
  import ModalHeaderTitle from "$lib/components/anuncios/ModalHeaderTitle.svelte";
  import type { Collection } from "$lib/anuncios/types";
  import { getCollectionsContext } from "$lib/collections-context.svelte";
  import { cn } from "$lib/utils";

  let {
    isOpen,
    onClose,
    collection
  } = $props<{
    isOpen: boolean;
    onClose: () => void;
    collection: Collection | null;
  }>();

  const ctx = getCollectionsContext();

  let shareUrl = $state<string | null>(null);
  let isLoading = $state(false);
  let error = $state<string | null>(null);
  let copied = $state(false);
  let showRevokeConfirm = $state(false);

  const isShared = $derived(Boolean(shareUrl));

  $effect(() => {
    if (!isOpen || !collection) return;
    showRevokeConfirm = false;
    copied = false;
    error = null;
    shareUrl =
      collection.shareToken && typeof window !== "undefined"
        ? `${window.location.origin}/anuncios?share=${collection.shareToken}`
        : null;
  });

  async function handleShare() {
    if (!collection) return;
    isLoading = true;
    error = null;
    try {
      shareUrl = await ctx.shareCollection(collection.id);
    } catch (err) {
      error = err instanceof Error ? err.message : "Erro ao compartilhar coleção";
    } finally {
      isLoading = false;
    }
  }

  async function handleRevoke() {
    if (!collection) return;
    isLoading = true;
    error = null;
    try {
      await ctx.unshareCollection(collection.id);
      shareUrl = null;
      showRevokeConfirm = false;
    } catch (err) {
      error = err instanceof Error ? err.message : "Erro ao revogar compartilhamento";
    } finally {
      isLoading = false;
    }
  }

  async function handleCopyLink() {
    if (!shareUrl) return;
    try {
      await navigator.clipboard.writeText(shareUrl);
      copied = true;
      setTimeout(() => (copied = false), 2000);
    } catch {
      error = "Não foi possível copiar o link";
    }
  }
</script>

{#if isOpen && collection}
  <div class="fixed inset-0 z-[1000] flex items-center justify-center">
    <button type="button" class="absolute inset-0 bg-app-fg/80 backdrop-blur-sm" aria-label="Fechar" onclick={onClose}></button>
    <Card class="relative z-10 mx-4 w-full max-w-md border-app-border bg-app-surface">
      <div class="flex items-center justify-between border-b border-app-border px-4 py-3">
        <ModalHeaderTitle icon={Link2} title="Compartilhar Coleção" />
        <ModalCloseButton onclick={onClose} />
      </div>
      <div class="space-y-4 p-4">
        <p class="text-sm font-medium">{collection.label}</p>
        {#if isLoading}
          <div class="flex items-center gap-2 text-sm text-app-muted">
            <Loader2 class="h-4 w-4 animate-spin" />
            Carregando...
          </div>
        {:else if isShared && shareUrl}
          <div class="space-y-2">
            <label class="sr-only" for="share-collection-url">Link de compartilhamento</label>
            <input
              id="share-collection-url"
              readonly
              value={shareUrl}
              aria-label="Link de compartilhamento da coleção"
              class="w-full rounded border border-app-border bg-app-surface-muted px-2 py-2 text-xs"
            />
            <button type="button" class="flex w-full items-center justify-center gap-2 rounded-lg border border-app-border py-2 text-sm" onclick={() => void handleCopyLink()}>
              {#if copied}<Check class="h-4 w-4" /> Copiado!{:else}Copiar link{/if}
            </button>
          </div>
          {#if showRevokeConfirm}
            <div class="space-y-2 rounded-lg border border-destructive/30 bg-destructive/10 p-3">
              <p class="text-sm">Revogar link de compartilhamento?</p>
              <div class="flex gap-2">
                <button type="button" class="flex-1 rounded border border-app-border py-2 text-sm" onclick={() => (showRevokeConfirm = false)}>Cancelar</button>
                <button type="button" class="flex-1 rounded bg-destructive py-2 text-sm text-white" onclick={() => void handleRevoke()}>Revogar</button>
              </div>
            </div>
          {:else}
            <button type="button" class="flex w-full items-center justify-center gap-2 rounded-lg border border-destructive/40 py-2 text-sm text-destructive" onclick={() => (showRevokeConfirm = true)}>
              <Lock class="h-4 w-4" />
              Revogar compartilhamento
            </button>
          {/if}
        {:else}
          <p class="text-sm text-app-muted">Gere um link público somente leitura para esta coleção.</p>
          <button type="button" class={cn("flex w-full items-center justify-center gap-2 rounded-lg bg-app-action py-2.5 text-app-action-foreground")} onclick={() => void handleShare()}>
            <Link2 class="h-4 w-4" />
            Gerar link
          </button>
        {/if}
        {#if error}<p class="text-xs text-destructive">{error}</p>{/if}
      </div>
    </Card>
  </div>
{/if}

// app/anuncios/components/share-collection-modal.tsx
"use client"

import { useState, useEffect, useCallback } from "react"
import { Card, CardContent, CardHeader } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { useCollections } from "../lib/use-collections"
import type { Collection } from "../lib/api"
import { Check, ClipboardList, Link2, Loader2, Lock } from "lucide-react"
import { ModalCloseButton, ModalHeaderTitle } from "./modal-chrome"
import { cn } from "@/lib/utils"

interface ShareCollectionModalProps {
  isOpen: boolean
  onClose: () => void
  collection: Collection | null
}

export function ShareCollectionModal({
  isOpen,
  onClose,
  collection,
}: ShareCollectionModalProps) {
  const { getShareStatus, shareCollection, unshareCollection } = useCollections()

  const [isShared, setIsShared] = useState(false)
  const [shareUrl, setShareUrl] = useState<string | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)
  const [showRevokeConfirm, setShowRevokeConfirm] = useState(false)

  const loadShareStatus = useCallback(async () => {
    if (!collection) return

    setIsLoading(true)
    setError(null)
    try {
      const status = await getShareStatus(collection.id)
      setIsShared(status.isShared)
      setShareUrl(status.shareUrl)
    } catch (err) {
      setError(err instanceof Error ? err.message : "Erro ao carregar status de compartilhamento")
    } finally {
      setIsLoading(false)
    }
  }, [collection, getShareStatus])

  useEffect(() => {
    if (isOpen && collection) {
      loadShareStatus()
      setShowRevokeConfirm(false)
      setCopied(false)
    }
  }, [isOpen, collection, loadShareStatus])

  const handleShare = async () => {
    if (!collection) return

    setIsLoading(true)
    setError(null)
    try {
      const url = await shareCollection(collection.id)
      setIsShared(true)
      setShareUrl(url)
    } catch (err) {
      setError(err instanceof Error ? err.message : "Erro ao compartilhar coleção")
    } finally {
      setIsLoading(false)
    }
  }

  const handleRevoke = async () => {
    if (!collection) return

    setIsLoading(true)
    setError(null)
    try {
      await unshareCollection(collection.id)
      setIsShared(false)
      setShareUrl(null)
      setShowRevokeConfirm(false)
    } catch (err) {
      setError(err instanceof Error ? err.message : "Erro ao revogar compartilhamento")
    } finally {
      setIsLoading(false)
    }
  }

  const handleCopyLink = async () => {
    if (!shareUrl) return

    try {
      await navigator.clipboard.writeText(shareUrl)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      setError("Não foi possível copiar o link")
    }
  }

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 z-[1000] flex items-center justify-center">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-app-fg/80 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Modal */}
      <Card className="relative z-10 w-full max-w-md mx-4 bg-app-surface border-app-border">
        <CardHeader className="flex flex-row items-center justify-between pb-2">
          <ModalHeaderTitle icon={Link2} title="Compartilhar Coleção" />
          <ModalCloseButton onClick={onClose} />
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Collection Name */}
          <div className="space-y-1">
            <Label className="text-sm text-app-muted">Coleção</Label>
            <p className="text-app-fg font-medium">{collection?.label}</p>
          </div>

          {/* Error Message */}
          {error && (
            <div className="p-3 rounded-lg bg-destructive/10 border border-destructive/30">
              <p className="text-sm text-destructive">{error}</p>
            </div>
          )}

          {/* Loading State */}
          {isLoading && (
            <div className="flex items-center justify-center py-4">
              <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
            </div>
          )}

          {/* Share Status */}
          {!isLoading && (
            <>
              {isShared && shareUrl ? (
                <div className="space-y-4">
                  {/* Status Badge */}
                  <div className="flex items-center gap-2">
                    <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-500/10 text-green-500 border border-green-500/30">
                      Compartilhada
                    </span>
                  </div>

                  {/* Share Link */}
                  <div className="space-y-2">
                    <Label htmlFor="share-url" className="text-sm text-app-muted">
                      Link de compartilhamento
                    </Label>
                    <div className="flex gap-2">
                      <Input
                        id="share-url"
                        type="text"
                        value={shareUrl}
                        readOnly
                        className="bg-app-surface-muted border-app-border text-app-fg text-sm"
                      />
                      <button
                        onClick={handleCopyLink}
                        className={cn(
                          "px-4 py-2 rounded-lg font-medium transition-all",
                          "bg-app-action text-app-action-foreground",
                          "hover:bg-app-action-hover",
                          "flex items-center gap-1 whitespace-nowrap"
                        )}
                      >
                        {copied ? (
                          <>
                            <Check className="h-4 w-4" />
                            Copiado!
                          </>
                        ) : (
                          <>
                            <ClipboardList className="h-4 w-4" />
                            Copiar
                          </>
                        )}
                      </button>
                    </div>
                    <p className="text-xs text-muted-foreground">
                      Qualquer pessoa com este link pode visualizar os imóveis desta coleção.
                    </p>
                  </div>

                  {/* Revoke Section */}
                  <div className="pt-4 border-t border-app-border">
                    {!showRevokeConfirm ? (
                      <button
                        onClick={() => setShowRevokeConfirm(true)}
                        className={cn(
                          "w-full py-2 px-4 rounded-lg font-medium transition-all",
                          "bg-destructive/10 border border-destructive/30 text-destructive",
                          "hover:bg-destructive/20 hover:border-destructive/50",
                          "flex items-center justify-center gap-2"
                        )}
                      >
                        <Lock className="h-4 w-4" />
                        Revogar compartilhamento
                      </button>
                    ) : (
                      <div className="space-y-3">
                        <p className="text-sm text-destructive">
                          Tem certeza que deseja revogar o compartilhamento?
                        </p>
                        <p className="text-xs text-muted-foreground">
                          O link atual deixará de funcionar e quem tiver acesso perderá a visualização.
                        </p>
                        <div className="flex gap-2">
                          <button
                            onClick={handleRevoke}
                            disabled={isLoading}
                            className={cn(
                              "flex-1 py-2 px-4 rounded-lg font-medium transition-all",
                              "bg-destructive text-app-fg",
                              "hover:bg-destructive/80",
                              "disabled:opacity-50"
                            )}
                          >
                            Sim, revogar
                          </button>
                          <button
                            onClick={() => setShowRevokeConfirm(false)}
                            className={cn(
                              "flex-1 py-2 px-4 rounded-lg font-medium transition-all",
                              "bg-app-surface-muted border border-app-border",
                              "hover:border-app-surface"
                            )}
                          >
                            Cancelar
                          </button>
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              ) : (
                <div className="space-y-4">
                  {/* Not Shared Status */}
                  <div className="flex items-center gap-2">
                    <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-muted text-muted-foreground border border-app-border">
                      Não compartilhada
                    </span>
                  </div>

                  {/* Info */}
                  <p className="text-sm text-muted-foreground">
                    Ao compartilhar esta coleção, você irá gerar um link que pode ser acessado
                    por qualquer pessoa. O link permite apenas a visualização dos imóveis.
                  </p>

                  {/* Share Button */}
                  <button
                    onClick={handleShare}
                    disabled={isLoading}
                    className={cn(
                      "w-full py-2.5 px-4 rounded-lg font-medium transition-all",
                      "bg-app-action text-app-action-foreground",
                      "hover:bg-app-action-hover",
                      "disabled:opacity-50 disabled:cursor-not-allowed",
                      "flex items-center justify-center gap-2"
                    )}
                  >
                    {isLoading ? (
                      <>
                        <Loader2 className="h-4 w-4 animate-spin" />
                        Gerando link...
                      </>
                    ) : (
                      <>
                        <Link2 className="h-4 w-4" />
                        Gerar link de compartilhamento
                      </>
                    )}
                  </button>
                </div>
              )}
            </>
          )}

          {/* Close Button */}
          <button
            onClick={onClose}
            className={cn(
              "w-full py-2 px-4 rounded-lg font-medium transition-all",
              "bg-app-surface-muted border border-app-border",
              "hover:border-app-surface"
            )}
          >
            Fechar
          </button>
        </CardContent>
      </Card>
    </div>
  )
}
