// components/ui/input.tsx
import * as React from "react"

import { cn } from "@/lib/utils"

const Input = React.forwardRef<HTMLInputElement, React.ComponentProps<"input">>(
  ({ className, type, ...props }, ref) => {
    return (
      <input
        ref={ref}
        type={type}
        data-slot="input"
        className={cn(
          "file:text-foreground placeholder:text-muted-foreground selection:bg-app-action selection:text-app-action-foreground dark:bg-input/30 border-input h-9 w-full min-w-0 rounded-md border bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm",
          "focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]",
          "aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",
          className
        )}
        {...props}
      />
    )
  }
)
Input.displayName = "Input"

export { Input }

// apps/web/src/lib/components/ui/Input.svelte
<script lang="ts">
  import { cn } from "$lib/utils";

  let {
    class: className = "",
    value = $bindable(""),
    type = "text",
    placeholder,
    disabled = false,
    required = false,
    name,
    id,
    min,
    max,
    step,
    inputmode,
    onchange,
    oninput
  } = $props<{
    class?: string;
    value?: string | number | null;
    type?: string;
    placeholder?: string;
    disabled?: boolean;
    required?: boolean;
    name?: string;
    id?: string;
    min?: string | number;
    max?: string | number;
    step?: string | number;
    inputmode?: "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | "search";
    onchange?: (event: Event & { currentTarget: HTMLInputElement }) => void;
    oninput?: (event: Event & { currentTarget: HTMLInputElement }) => void;
  }>();
</script>

<input
  {id}
  {name}
  {type}
  {placeholder}
  {disabled}
  {required}
  {min}
  {max}
  {step}
  {inputmode}
  bind:value
  class={cn(
    "flex h-10 w-full rounded-md border border-app-border bg-white px-3 text-sm text-app-fg shadow-sm transition placeholder:text-app-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-app-action disabled:cursor-not-allowed disabled:opacity-60",
    className
  )}
  {onchange}
  {oninput}
/>
