// apps/web/src/lib/components/property-details/PropertyImageGallery.svelte
<script lang="ts">
  import { Download, Printer, Star } from "@lucide/svelte";
  import type { Property } from "$lib/listings/types";
  import { normalizeCoverIndex } from "$lib/listing-images-core";
  import { getImageEnvironmentLabel, resolveListingGalleryImages } from "$lib/listing-gallery";
  import ImageLightboxOverlay from "$lib/components/property-details/ImageLightboxOverlay.svelte";
  import { useImageLightbox } from "$lib/components/property-details/use-image-lightbox.svelte";
  import ListingImageCarousel from "$lib/carousel/ListingImageCarousel.svelte";
  import { buildListingImagesPrintHref } from "$lib/property-details-url";
  import { cn } from "$lib/utils";

  let {
    listing,
    collectionId: _collectionId = null,
    updateListing
  }: {
    listing: Property;
    collectionId?: string | null;
    updateListing?: (listingId: string, updates: Partial<Property>) => Promise<Property>;
  } = $props();

  const galleryImages = $derived(resolveListingGalleryImages(listing));
  const imageUrls = $derived(galleryImages.map((image) => image.url));
  const coverIndex = $derived(normalizeCoverIndex(listing.coverImageIndex, imageUrls.length));
  const carouselUrls = $derived(galleryImages.map((image) => image.url));
  const printHref = $derived(buildListingImagesPrintHref(listing.id));

  let selectedOriginalIndex = $state(0);
  let heroSlideIndex = $state(0);
  let isSaving = $state(false);
  let lightboxSlideIndex = $state(0);

  const lightbox = useImageLightbox(() =>
    galleryImages.map((image, index) => ({ index, url: image.url }))
  );

  const selectedDisplayIndex = $derived(
    Math.max(
      galleryImages.findIndex((image) => image.originalIndex === selectedOriginalIndex),
      0
    )
  );

  const selectedImage = $derived(galleryImages[selectedDisplayIndex]);
  const selectedEnvironmentLabel = $derived(
    selectedImage ? getImageEnvironmentLabel(listing, selectedImage.originalIndex) : null
  );

  $effect(() => {
    void listing.id;
    void coverIndex;
    selectedOriginalIndex = coverIndex;
    lightbox.close();
  });

  $effect(() => {
    if (!galleryImages.some((image) => image.originalIndex === selectedOriginalIndex)) {
      selectedOriginalIndex = galleryImages[0]?.originalIndex ?? 0;
    }
  });

  $effect(() => {
    heroSlideIndex = selectedDisplayIndex;
  });

  function handleHeroIndexChange(index: number) {
    heroSlideIndex = index;
    const image = galleryImages[index];
    if (image) selectedOriginalIndex = image.originalIndex;
  }

  async function persistListingUpdate(updates: Partial<Property>) {
    if (!updateListing) return;
    isSaving = true;
    try {
      await updateListing(listing.id, updates);
    } finally {
      isSaving = false;
    }
  }

  function handleSetCover() {
    if (!selectedImage || selectedImage.originalIndex === coverIndex) return;
    void persistListingUpdate({ coverImageIndex: selectedImage.originalIndex });
  }

  function openLightbox() {
    lightboxSlideIndex = heroSlideIndex;
    lightbox.open(heroSlideIndex);
  }

  function selectThumb(originalIndex: number) {
    selectedOriginalIndex = originalIndex;
    const displayIndex = galleryImages.findIndex((image) => image.originalIndex === originalIndex);
    if (displayIndex >= 0) heroSlideIndex = displayIndex;
  }
</script>

{#if imageUrls.length === 0}
  <p class="text-sm text-app-muted">Sem imagens para este imóvel.</p>
{:else if selectedImage}
  {@const selectedImageNumber = selectedImage.originalIndex + 1}
  {@const isCover = selectedImage.originalIndex === coverIndex}

  <div class="min-w-0 max-w-full space-y-2">
    <div class="flex justify-end">
      <a
        href={printHref}
        target="_blank"
        rel="noopener noreferrer"
        class="inline-flex h-8 items-center gap-1.5 rounded-md border border-app-border bg-app-surface px-2.5 text-xs font-medium text-app-fg shadow-sm hover:bg-app-bg"
      >
        <Printer class="size-3.5" />
        <Download class="size-3.5" />
        Imprimir / baixar
      </a>
    </div>

    <div
      class="relative h-[min(50vh,16rem)] w-full min-w-0 max-w-full overflow-hidden rounded-md border border-app-border bg-app-bg sm:aspect-[4/3] sm:h-auto"
    >
      <ListingImageCarousel
        urls={carouselUrls}
        preset="card"
        bind:selectedIndex={heroSlideIndex}
        onIndexChange={handleHeroIndexChange}
        onSlideClick={openLightbox}
        viewportClass="h-full min-h-0"
      >
        {#snippet slide({ url })}
          <img
            src={url}
            alt={`Foto do imóvel`}
            class="block h-full min-h-0 w-full max-w-full object-cover"
          />
        {/snippet}
      </ListingImageCarousel>

      <div class="pointer-events-none absolute inset-0">
        <div class="absolute right-2 top-2 flex items-center gap-2 pointer-events-auto">
          <button
            type="button"
            onclick={handleSetCover}
            disabled={isSaving || isCover || !updateListing}
            class={cn(
              "inline-flex h-8 items-center gap-1 rounded-md border px-2 text-xs font-medium shadow-sm backdrop-blur",
              isCover
                ? "border-amber-300 bg-amber-100/90 text-amber-950"
                : "border-white/30 bg-black/55 text-white hover:bg-black/70",
              (isSaving || !updateListing) && "cursor-not-allowed opacity-70"
            )}
            aria-label={
              isCover
                ? `Imagem ${selectedImageNumber} é a capa`
                : `Definir imagem ${selectedImageNumber} como capa`
            }
          >
            <Star class={cn("size-3.5", isCover && "fill-current")} />
            Capa
          </button>

          {#if selectedEnvironmentLabel}
            <span
              class="inline-flex h-8 max-w-40 items-center truncate rounded-md border border-white/30 bg-black/55 px-2 text-xs font-medium text-white shadow-sm backdrop-blur"
              title={selectedEnvironmentLabel}
            >
              {selectedEnvironmentLabel}
            </span>
          {/if}
        </div>
      </div>
    </div>

    <div class="flex gap-2 overflow-x-auto pb-1">
      {#each galleryImages as image, index (image.url + image.originalIndex)}
        <button
          type="button"
          onclick={() => selectThumb(image.originalIndex)}
          class={cn(
            "relative h-16 w-20 shrink-0 overflow-hidden rounded-md border bg-app-surface transition",
            index === selectedDisplayIndex
              ? "border-app-fg ring-2 ring-app-fg/20"
              : "border-app-border hover:border-app-muted"
          )}
          aria-label={`Selecionar imagem ${image.originalIndex + 1}`}
          aria-current={index === selectedDisplayIndex ? "true" : undefined}
        >
          <img src={image.url} alt="" class="h-full w-full object-cover" />
        </button>
      {/each}
    </div>
  </div>

  {#if lightbox.lightboxLocalIndex !== null}
    <ImageLightboxOverlay
      urls={lightbox.urls}
      bind:selectedIndex={lightboxSlideIndex}
      caption={`Foto ${(galleryImages[lightboxSlideIndex]?.originalIndex ?? 0) + 1}`}
      onClose={lightbox.close}
    />
  {/if}
{/if}

// app/analise/components/property-image-gallery.tsx
"use client"

/* eslint-disable @next/next/no-img-element */

import { useCallback, useEffect, useMemo, useState } from "react"
import { ChevronLeft, ChevronRight, Star, X } from "lucide-react"
import type { Imovel } from "@/app/anuncios/lib/api"
import { resolveListingImages } from "@/lib/listing-images"
import type { ListingImageCategoryKey } from "@/lib/db/schema"
import { cn } from "@/lib/utils"

interface PropertyImageGalleryProps {
  listing: Imovel
  updateListing?: (listingId: string, updates: Partial<Imovel>) => Promise<Imovel>
}

interface GalleryImage {
  url: string
  originalIndex: number
}

type CategorySelectValue = ListingImageCategoryKey | "none"

const CATEGORY_ORDER = ["quarto", "banheiro", "sala", "fachada", "areaExterna"] as const

function normalizeCoverIndex(index: number | null | undefined, length: number) {
  return typeof index === "number" &&
    Number.isInteger(index) &&
    index >= 0 &&
    index < length
    ? index
    : 0
}

function positiveCount(value: number | null | undefined) {
  return typeof value === "number" && Number.isFinite(value) && value > 0
    ? Math.trunc(value)
    : 0
}

function buildCategoryOptions(listing: Imovel) {
  const quartos = Array.from({ length: positiveCount(listing.quartos) }, (_, index) => ({
    value: `quarto-${index + 1}` as ListingImageCategoryKey,
    label: `Quarto ${index + 1}`,
  }))
  const banheiros = Array.from({ length: positiveCount(listing.banheiros) }, (_, index) => ({
    value: `banheiro-${index + 1}` as ListingImageCategoryKey,
    label: `Banheiro ${index + 1}`,
  }))

  return [
    { value: "none" as const, label: "Sem categoria" },
    ...quartos,
    ...banheiros,
    { value: "sala" as const, label: "Sala" },
    { value: "fachada" as const, label: "Fachada" },
    { value: "areaExterna" as const, label: "Área externa" },
  ]
}

function categorySortTuple(category: ListingImageCategoryKey | undefined) {
  if (!category) return [CATEGORY_ORDER.length, 0] as const
  if (category.startsWith("quarto-")) {
    return [0, Number(category.slice("quarto-".length)) || 0] as const
  }
  if (category.startsWith("banheiro-")) {
    return [1, Number(category.slice("banheiro-".length)) || 0] as const
  }
  const rank = CATEGORY_ORDER.indexOf(category as (typeof CATEGORY_ORDER)[number])
  return [rank >= 0 ? rank : CATEGORY_ORDER.length, 0] as const
}

function resolveGalleryImages(
  imageUrls: string[],
  coverIndex: number,
  categories: Record<string, ListingImageCategoryKey> | null | undefined
): GalleryImage[] {
  if (imageUrls.length === 0) return []

  const originalOrder = imageUrls.map((_url, index) => index)
  const cover = normalizeCoverIndex(coverIndex, imageUrls.length)
  const rest = originalOrder
    .filter((index) => index !== cover)
    .sort((left, right) => {
      const [leftRank, leftOrdinal] = categorySortTuple(categories?.[String(left)])
      const [rightRank, rightOrdinal] = categorySortTuple(categories?.[String(right)])
      return leftRank - rightRank || leftOrdinal - rightOrdinal || left - right
    })

  return [cover, ...rest].map((originalIndex) => ({
    originalIndex,
    url: imageUrls[originalIndex],
  }))
}

export function PropertyImageGallery({ listing, updateListing }: PropertyImageGalleryProps) {
  const { imageUrls } = useMemo(
    () =>
      resolveListingImages({
        listingId: listing.id,
        imageUrl: listing.imageUrl,
        imageUrls: listing.imageUrls,
        imageStorageKeys: listing.imageStorageKeys,
        imageCoverIndex: listing.imageCoverIndex,
      }),
    [
      listing.id,
      listing.imageCoverIndex,
      listing.imageStorageKeys,
      listing.imageUrl,
      listing.imageUrls,
    ]
  )
  const coverIndex = normalizeCoverIndex(listing.imageCoverIndex, imageUrls.length)
  const galleryImages = useMemo(
    () => resolveGalleryImages(imageUrls, coverIndex, listing.imageCategories),
    [coverIndex, imageUrls, listing.imageCategories]
  )
  const [selectedOriginalIndex, setSelectedOriginalIndex] = useState(coverIndex)
  const [lightboxIndex, setLightboxIndex] = useState<number | null>(null)
  const [isSaving, setIsSaving] = useState(false)

  const close = useCallback(() => setLightboxIndex(null), [])

  useEffect(() => {
    setSelectedOriginalIndex(coverIndex)
    setLightboxIndex(null)
  }, [coverIndex, listing.id])

  useEffect(() => {
    if (!galleryImages.some((image) => image.originalIndex === selectedOriginalIndex)) {
      setSelectedOriginalIndex(galleryImages[0]?.originalIndex ?? 0)
    }
  }, [galleryImages, selectedOriginalIndex])

  useEffect(() => {
    if (lightboxIndex === null) return
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") close()
      if (e.key === "ArrowRight")
        setLightboxIndex((i) =>
          i === null ? null : Math.min(i + 1, galleryImages.length - 1)
        )
      if (e.key === "ArrowLeft")
        setLightboxIndex((i) => (i === null ? null : Math.max(i - 1, 0)))
    }
    window.addEventListener("keydown", onKey)
    return () => window.removeEventListener("keydown", onKey)
  }, [lightboxIndex, galleryImages.length, close])

  const categoryOptions = useMemo(() => buildCategoryOptions(listing), [listing])

  const selectedDisplayIndex = Math.max(
    galleryImages.findIndex((image) => image.originalIndex === selectedOriginalIndex),
    0
  )
  const selectedImage = galleryImages[selectedDisplayIndex]

  const persistListingUpdate = async (updates: Partial<Imovel>) => {
    if (!updateListing) return
    setIsSaving(true)
    try {
      await updateListing(listing.id, updates)
    } finally {
      setIsSaving(false)
    }
  }

  const handleSetCover = () => {
    if (!selectedImage || selectedImage.originalIndex === coverIndex) return
    void persistListingUpdate({ imageCoverIndex: selectedImage.originalIndex })
  }

  const handleCategoryChange = (value: CategorySelectValue) => {
    if (!selectedImage) return
    const next = { ...(listing.imageCategories ?? {}) }
    const key = String(selectedImage.originalIndex)

    if (value === "none") {
      delete next[key]
    } else {
      next[key] = value
    }

    void persistListingUpdate({
      imageCategories: Object.keys(next).length > 0 ? next : null,
    })
  }

  if (imageUrls.length === 0) {
    return (
      <p className="text-sm text-app-muted">Sem imagens para este imóvel.</p>
    )
  }

  const selectedImageNumber = selectedImage.originalIndex + 1
  const selectedCategory = listing.imageCategories?.[String(selectedImage.originalIndex)]
  const selectedCategoryValue: CategorySelectValue = selectedCategory ?? "none"
  const isCover = selectedImage.originalIndex === coverIndex

  return (
    <>
      <div className="min-w-0 max-w-full space-y-2">
        <div className="relative h-[min(50vh,16rem)] w-full min-w-0 max-w-full overflow-hidden rounded-md border border-app-border bg-app-bg sm:h-auto sm:aspect-[4/3]">
          <button
            type="button"
            onClick={() => setLightboxIndex(selectedDisplayIndex)}
            className="block h-full min-h-0 w-full min-w-0"
            aria-label={`Abrir imagem ${selectedImageNumber}`}
          >
            <img
              src={selectedImage.url}
              alt={`Foto ${selectedImageNumber} do imóvel`}
              className="block h-full w-full max-w-full min-h-0 object-cover"
            />
          </button>

          <div className="absolute right-2 top-2 flex items-center gap-2">
            <button
              type="button"
              onClick={handleSetCover}
              disabled={isSaving || isCover || !updateListing}
              className={cn(
                "inline-flex h-8 items-center gap-1 rounded-md border px-2 text-xs font-medium shadow-sm backdrop-blur",
                isCover
                  ? "border-amber-300 bg-amber-100/90 text-amber-950"
                  : "border-white/30 bg-black/55 text-white hover:bg-black/70",
                (isSaving || !updateListing) && "cursor-not-allowed opacity-70"
              )}
              aria-label={
                isCover
                  ? `Imagem ${selectedImageNumber} é a capa`
                  : `Definir imagem ${selectedImageNumber} como capa`
              }
            >
              <Star className={cn("size-3.5", isCover && "fill-current")} />
              {isCover ? "Capa" : "Capa"}
            </button>

            <select
              value={selectedCategoryValue}
              onChange={(event) =>
                handleCategoryChange(event.target.value as CategorySelectValue)
              }
              disabled={isSaving || !updateListing}
              aria-label={`Categoria da imagem ${selectedImageNumber}`}
              className="h-8 max-w-40 rounded-md border border-white/30 bg-black/55 px-2 text-xs font-medium text-white shadow-sm backdrop-blur hover:bg-black/70 disabled:cursor-not-allowed disabled:opacity-70"
            >
              {categoryOptions.map((option) => (
                <option key={option.value} value={option.value} className="bg-app-surface text-app-fg">
                  {option.label}
                </option>
              ))}
            </select>
          </div>
        </div>

        <div className="flex gap-2 overflow-x-auto pb-1">
          {galleryImages.map((image, index) => (
            <button
              key={`${image.url}-${image.originalIndex}`}
              type="button"
              onClick={() => setSelectedOriginalIndex(image.originalIndex)}
              className={cn(
                "relative h-16 w-20 shrink-0 overflow-hidden rounded-md border bg-app-surface transition",
                index === selectedDisplayIndex
                  ? "border-app-fg ring-2 ring-app-fg/20"
                  : "border-app-border hover:border-app-muted"
              )}
              aria-label={`Selecionar imagem ${image.originalIndex + 1}`}
              aria-current={index === selectedDisplayIndex ? "true" : undefined}
            >
              <img src={image.url} alt="" className="h-full w-full object-cover" />
            </button>
          ))}
        </div>
      </div>

      {lightboxIndex !== null && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4"
          role="dialog"
          aria-modal
        >
          <button
            type="button"
            className="absolute right-4 top-4 rounded-full bg-black/50 p-2 text-white"
            onClick={close}
            aria-label="Fechar"
          >
            <X className="size-5" />
          </button>
          {lightboxIndex > 0 && (
            <button
              type="button"
              className="absolute left-4 rounded-full bg-black/50 p-2 text-white"
              onClick={() => setLightboxIndex(lightboxIndex - 1)}
              aria-label="Anterior"
            >
              <ChevronLeft className="size-6" />
            </button>
          )}
          {lightboxIndex < galleryImages.length - 1 && (
            <button
              type="button"
              className="absolute right-14 rounded-full bg-black/50 p-2 text-white"
              onClick={() => setLightboxIndex(lightboxIndex + 1)}
              aria-label="Próxima"
            >
              <ChevronRight className="size-6" />
            </button>
          )}
          <img
            src={galleryImages[lightboxIndex].url}
            alt=""
            className="max-h-[85vh] max-w-full rounded-lg object-contain"
          />
        </div>
      )}
    </>
  )
}
