// apps/web/src/lib/admin/UserDetailsModal.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import ModalCloseButton from "$lib/components/anuncios/ModalCloseButton.svelte";
  import Button from "$lib/components/ui/Button.svelte";
  import Switch from "$lib/components/ui/Switch.svelte";
  import {
    adminApi,
    type AdminAddon,
    type AdminAddonGrant,
    type AdminUser
  } from "$lib/admin/client";

  let {
    user,
    availableAddons,
    onClose,
    onUserUpdated
  } = $props<{
    user: AdminUser;
    availableAddons: AdminAddon[];
    onClose: () => void;
    onUserUpdated: () => void | Promise<void>;
  }>();

  let userAddonGrants = $state<AdminAddonGrant[]>([]);
  let loadingAddons = $state(true);
  let grantModalOpen = $state(false);
  let selectedAddonSlug = $state("");
  let addonExpiresAt = $state("");
  let grantingAddon = $state(false);
  let revokingAddon = $state(false);
  let togglingAddon = $state<string | null>(null);

  const grantableAddons = $derived.by(() =>
    availableAddons.filter(
      (addon: AdminAddon) => !userAddonGrants.some((grant) => grant.addonSlug === addon.slug)
    )
  );

  onMount(() => {
    void fetchUserAddons();
  });

  async function fetchUserAddons() {
    loadingAddons = true;
    try {
      const data = await adminApi.fetchUserAddons(user.id);
      userAddonGrants = data.addons;
    } catch (err) {
      console.error("Error fetching user addons:", err);
      userAddonGrants = [];
    } finally {
      loadingAddons = false;
    }
  }

  async function grantAddon() {
    if (!selectedAddonSlug) return;

    grantingAddon = true;
    try {
      await adminApi.grantUserAddon(user.id, {
        addonSlug: selectedAddonSlug,
        enabled: true,
        expiresAt: addonExpiresAt ? new Date(addonExpiresAt).toISOString() : null
      });
      grantModalOpen = false;
      selectedAddonSlug = "";
      addonExpiresAt = "";
      await fetchUserAddons();
      await onUserUpdated();
    } catch (err) {
      alert(err instanceof Error ? err.message : "Failed to grant addon");
    } finally {
      grantingAddon = false;
    }
  }

  async function revokeAddon(addonSlug: string) {
    if (!confirm("Tem certeza que deseja revogar este addon?")) return;

    revokingAddon = true;
    try {
      await adminApi.revokeUserAddon(user.id, addonSlug);
      await fetchUserAddons();
      await onUserUpdated();
    } catch (err) {
      alert(err instanceof Error ? err.message : "Failed to revoke addon");
    } finally {
      revokingAddon = false;
    }
  }

  async function toggleAddon(addonSlug: string, currentEnabled: boolean) {
    togglingAddon = addonSlug;
    try {
      await adminApi.grantUserAddon(user.id, {
        addonSlug,
        enabled: !currentEnabled
      });
      await fetchUserAddons();
      await onUserUpdated();
    } catch (err) {
      alert(err instanceof Error ? err.message : "Failed to toggle addon");
    } finally {
      togglingAddon = null;
    }
  }

  function isAddonExpired(expiresAt: string | null) {
    if (!expiresAt) return false;
    return new Date(expiresAt) < new Date();
  }

  function getAddonStatusBadgeClass(enabled: boolean, expiresAt: string | null) {
    if (!enabled) return "bg-slate-200 text-slate-700";
    if (isAddonExpired(expiresAt)) return "bg-red-100 text-red-700";
    return "bg-emerald-100 text-emerald-800";
  }

  function getAddonStatusLabel(enabled: boolean, expiresAt: string | null) {
    if (!enabled) return "Desabilitado";
    if (isAddonExpired(expiresAt)) return "Expirado";
    return "Ativo";
  }

  function formatDateTime(dateString: string) {
    return new Date(dateString).toLocaleDateString("pt-BR", {
      day: "2-digit",
      month: "2-digit",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit"
    });
  }

  function formatDate(dateString: string) {
    return new Date(dateString).toLocaleDateString("pt-BR", {
      day: "2-digit",
      month: "2-digit",
      year: "numeric"
    });
  }

  function isExpired(expiresAt: string) {
    return new Date(expiresAt) < new Date();
  }

  function closeGrantModal() {
    grantModalOpen = false;
    selectedAddonSlug = "";
    addonExpiresAt = "";
  }

  function handleKeyDown(event: KeyboardEvent) {
    if (event.key !== "Escape") return;
    event.preventDefault();
    if (grantModalOpen) {
      closeGrantModal();
      return;
    }
    onClose();
  }
</script>

<svelte:window onkeydown={handleKeyDown} />

<div class="fixed inset-0 z-50 flex items-center justify-center p-4">
  <button
    type="button"
    class="absolute inset-0 bg-app-fg/50"
    aria-label="Fechar modal"
    onclick={onClose}
  ></button>

  <div
    class="relative z-10 mx-4 flex max-h-[90vh] w-full max-w-4xl flex-col overflow-hidden rounded-xl border border-app-border bg-app-surface shadow-xl"
    role="dialog"
    aria-modal="true"
    aria-labelledby="user-details-title"
    tabindex="-1"
  >
    <div class="border-b border-app-border px-6 py-5">
      <div class="flex items-start justify-between gap-3">
        <div>
          <h2 id="user-details-title" class="text-lg font-semibold leading-none">Detalhes do Usuário</h2>
          <p class="mt-1.5 text-sm text-app-muted">Visualize e gerencie informações do usuário</p>
        </div>
        <ModalCloseButton onclick={onClose} />
      </div>
    </div>

    <div class="space-y-6 overflow-y-auto px-6 py-5">
      <div class="grid grid-cols-1 gap-4 rounded-lg bg-app-surface-muted/80 p-4 md:grid-cols-2">
        <div>
          <span class="text-sm text-app-muted">Nome</span>
          <p class="font-medium">{user.name}</p>
        </div>
        <div>
          <span class="text-sm text-app-muted">Email</span>
          <p class="font-medium">{user.email}</p>
        </div>
        <div>
          <span class="text-sm text-app-muted">Criado em</span>
          <p class="font-medium">{formatDate(user.createdAt)}</p>
        </div>
        <div>
          <span class="text-sm text-app-muted">Status</span>
          <div class="mt-1 flex flex-wrap items-center gap-2">
            {#if user.isAdmin}
              <span class="rounded px-2 py-0.5 text-xs bg-blue-100 text-blue-700">Admin</span>
            {/if}
            {#if user.emailVerified}
              <span class="rounded px-2 py-0.5 text-xs bg-emerald-100 text-emerald-800">Email Verificado</span>
            {:else}
              <span class="rounded px-2 py-0.5 text-xs bg-yellow-100 text-yellow-700">Email Pendente</span>
            {/if}
          </div>
        </div>
      </div>

      <div>
        <h3 class="mb-3 text-lg font-medium">Assinatura</h3>
        {#if user.subscription?.plan}
          <div class="rounded-lg border border-app-border p-4">
            <div class="mb-2 flex items-center gap-2">
              <span class="font-medium">{user.subscription.plan.name}</span>
              <span
                class={`rounded px-2 py-0.5 text-xs ${
                  isExpired(user.subscription.expiresAt)
                    ? "bg-red-100 text-red-700"
                    : "bg-emerald-100 text-emerald-800"
                }`}
              >
                {isExpired(user.subscription.expiresAt) ? "Expirada" : "Ativa"}
              </span>
            </div>
            <p class="text-sm text-app-muted">Expira em: {formatDate(user.subscription.expiresAt)}</p>
          </div>
        {:else}
          <p class="rounded-lg border border-app-border p-4 text-app-muted">Nenhuma assinatura ativa</p>
        {/if}
      </div>

      <div>
        <div class="mb-3 flex items-center justify-between gap-3">
          <h3 class="text-lg font-medium">Addons Pessoais</h3>
          <Button size="sm" onclick={() => (grantModalOpen = true)} disabled={grantableAddons.length === 0}>
            Conceder Addon
          </Button>
        </div>

        {#if loadingAddons}
          <div class="py-8 text-center text-app-muted">Carregando addons...</div>
        {:else if userAddonGrants.length === 0}
          <div class="rounded-lg border border-app-border py-8 text-center text-app-muted">
            Nenhum addon concedido para este usuário.
          </div>
        {:else}
          <div class="space-y-3">
            {#each userAddonGrants as grant (grant.id)}
              <div
                class="flex flex-col justify-between gap-4 rounded-lg border border-app-border p-4 md:flex-row md:items-center"
              >
                <div class="flex-1 space-y-1">
                  <div class="flex flex-wrap items-center gap-2">
                    <span class="font-medium">{grant.addon?.name ?? grant.addonSlug}</span>
                    <span
                      class={`rounded px-2 py-0.5 text-xs ${getAddonStatusBadgeClass(grant.enabled, grant.expiresAt)}`}
                    >
                      {getAddonStatusLabel(grant.enabled, grant.expiresAt)}
                    </span>
                  </div>
                  {#if grant.addon?.description}
                    <p class="text-sm text-app-muted">{grant.addon.description}</p>
                  {/if}
                  <div class="space-y-0.5 text-xs text-app-muted">
                    <p>Concedido em: {formatDateTime(grant.grantedAt)}</p>
                    {#if grant.expiresAt}
                      <p>
                        Expira em: {formatDateTime(grant.expiresAt)}
                        {#if isAddonExpired(grant.expiresAt)}
                          <span class="ml-1 text-red-600">(expirado)</span>
                        {/if}
                      </p>
                    {/if}
                    {#if grant.grantedByUser}
                      <p>Por: {grant.grantedByUser.name}</p>
                    {/if}
                  </div>
                </div>
                <div class="flex flex-wrap items-center gap-3">
                  <div class="flex items-center gap-2">
                    <span class="text-sm text-app-muted">{grant.enabled ? "Habilitado" : "Desabilitado"}</span>
                    <Switch
                      checked={grant.enabled}
                      disabled={togglingAddon === grant.addonSlug}
                      aria-label={`Toggle ${grant.addon?.name ?? grant.addonSlug}`}
                      onCheckedChange={() => void toggleAddon(grant.addonSlug, grant.enabled)}
                    />
                  </div>
                  <Button
                    variant="outline"
                    size="sm"
                    class="text-red-600 hover:text-red-700"
                    onclick={() => void revokeAddon(grant.addonSlug)}
                    disabled={revokingAddon}
                  >
                    Revogar
                  </Button>
                </div>
              </div>
            {/each}
          </div>
        {/if}
      </div>

      <div class="flex justify-end border-t border-app-border pt-4">
        <Button variant="outline" onclick={onClose}>Fechar</Button>
      </div>
    </div>
  </div>
</div>

{#if grantModalOpen}
  <div class="fixed inset-0 z-[60] flex items-center justify-center p-4">
    <button
      type="button"
      class="absolute inset-0 bg-app-fg/50"
      aria-label="Fechar concessão de addon"
      onclick={closeGrantModal}
    ></button>

    <div
      class="relative z-10 mx-4 w-full max-w-md rounded-xl border border-app-border bg-app-surface shadow-xl"
      role="dialog"
      aria-modal="true"
      aria-labelledby="grant-addon-title"
      tabindex="-1"
    >
      <div class="border-b border-app-border px-6 py-5">
        <h2 id="grant-addon-title" class="text-lg font-semibold">Conceder Addon</h2>
        <p class="mt-1.5 text-sm text-app-muted">
          Conceder addon para {user.name} ({user.email})
        </p>
      </div>

      <div class="space-y-4 px-6 py-5">
        <label class="block space-y-2 text-sm">
          <span>Addon</span>
          <select
            class="h-10 w-full rounded-md border border-app-border bg-white px-3"
            bind:value={selectedAddonSlug}
          >
            <option value="">Selecione um addon</option>
            {#each grantableAddons as addon (addon.id)}
              <option value={addon.slug}>{addon.name}</option>
            {/each}
          </select>
          {#if grantableAddons.length === 0}
            <p class="text-sm text-app-muted">Todos os addons disponíveis já foram concedidos.</p>
          {/if}
        </label>

        <label class="block space-y-2 text-sm">
          <span>Data de Expiração (opcional)</span>
          <input
            class="h-10 w-full rounded-md border border-app-border bg-white px-3"
            type="date"
            bind:value={addonExpiresAt}
          />
          <p class="text-xs text-app-muted">Deixe vazio para concessão sem expiração.</p>
        </label>

        <div class="flex justify-end gap-2 pt-2">
          <Button variant="outline" onclick={closeGrantModal}>Cancelar</Button>
          <Button onclick={() => void grantAddon()} disabled={!selectedAddonSlug || grantingAddon}>
            {grantingAddon ? "Concedendo..." : "Conceder"}
          </Button>
        </div>
      </div>
    </div>
  </div>
{/if}

// app/admin/components/user-details-modal.tsx
"use client"

import { useEffect, useState, useCallback } from "react"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"

interface Addon {
  id: string
  name: string
  slug: string
  description: string | null
  createdAt: string
}

interface UserAddonGrant {
  id: string
  userId: string
  addonSlug: string
  grantedAt: string
  grantedBy: string | null
  enabled: boolean
  expiresAt: string | null
  addon: Addon | null
  grantedByUser: { id: string; name: string; email: string } | null
}

interface Plan {
  id: string
  name: string
  slug: string
}

interface Subscription {
  id: string
  status: string
  expiresAt: string
  plan: Plan | null
}

interface User {
  id: string
  email: string
  name: string
  isAdmin: boolean
  emailVerified: boolean
  createdAt: string
  subscription: Subscription | null
}

interface UserDetailsModalProps {
  user: User
  availableAddons: Addon[]
  onClose: () => void
  onUserUpdated: () => void
}

export function UserDetailsModal({
  user,
  availableAddons,
  onClose,
  onUserUpdated,
}: UserDetailsModalProps) {
  const [userAddonGrants, setUserAddonGrants] = useState<UserAddonGrant[]>([])
  const [loadingAddons, setLoadingAddons] = useState(true)
  const [grantModalOpen, setGrantModalOpen] = useState(false)
  const [selectedAddonSlug, setSelectedAddonSlug] = useState("")
  const [addonExpiresAt, setAddonExpiresAt] = useState("")
  const [grantingAddon, setGrantingAddon] = useState(false)
  const [revokingAddon, setRevokingAddon] = useState(false)
  const [togglingAddon, setTogglingAddon] = useState<string | null>(null)

  const fetchUserAddons = useCallback(async () => {
    setLoadingAddons(true)
    try {
      const res = await fetch(`/api/admin/users/${user.id}/addons`)
      if (!res.ok) {
        throw new Error("Failed to fetch user addons")
      }
      const data = await res.json()
      setUserAddonGrants(data.addons || [])
    } catch (err) {
      console.error("Error fetching user addons:", err)
      setUserAddonGrants([])
    } finally {
      setLoadingAddons(false)
    }
  }, [user.id])

  useEffect(() => {
    fetchUserAddons()
  }, [fetchUserAddons])

  async function grantAddon() {
    if (!selectedAddonSlug) return

    setGrantingAddon(true)

    try {
      const body: { addonSlug: string; expiresAt?: string; enabled: boolean } = {
        addonSlug: selectedAddonSlug,
        enabled: true,
      }

      if (addonExpiresAt) {
        body.expiresAt = new Date(addonExpiresAt).toISOString()
      }

      const res = await fetch(`/api/admin/users/${user.id}/addons`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      })

      if (!res.ok) {
        const data = await res.json()
        throw new Error(data.error || "Failed to grant addon")
      }

      setGrantModalOpen(false)
      setSelectedAddonSlug("")
      setAddonExpiresAt("")
      fetchUserAddons()
      onUserUpdated()
    } catch (err) {
      alert(err instanceof Error ? err.message : "Failed to grant addon")
    } finally {
      setGrantingAddon(false)
    }
  }

  async function revokeAddon(addonSlug: string) {
    if (!confirm("Tem certeza que deseja revogar este addon?")) return

    setRevokingAddon(true)

    try {
      const res = await fetch(`/api/admin/users/${user.id}/addons/${addonSlug}`, {
        method: "DELETE",
      })

      if (!res.ok) {
        const data = await res.json()
        throw new Error(data.error || "Failed to revoke addon")
      }

      fetchUserAddons()
      onUserUpdated()
    } catch (err) {
      alert(err instanceof Error ? err.message : "Failed to revoke addon")
    } finally {
      setRevokingAddon(false)
    }
  }

  async function toggleAddon(addonSlug: string, currentEnabled: boolean) {
    setTogglingAddon(addonSlug)

    try {
      const res = await fetch(`/api/admin/users/${user.id}/addons`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          addonSlug,
          enabled: !currentEnabled,
        }),
      })

      if (!res.ok) {
        const data = await res.json()
        throw new Error(data.error || "Failed to toggle addon")
      }

      fetchUserAddons()
      onUserUpdated()
    } catch (err) {
      alert(err instanceof Error ? err.message : "Failed to toggle addon")
    } finally {
      setTogglingAddon(null)
    }
  }

  function isAddonExpired(expiresAt: string | null) {
    if (!expiresAt) return false
    return new Date(expiresAt) < new Date()
  }

  function getAddonStatusBadgeClass(enabled: boolean, expiresAt: string | null) {
    if (!enabled) return "bg-gray-200 text-gray-700"
    if (isAddonExpired(expiresAt)) return "bg-destructive/20 text-destructive"
    return "bg-green-100 text-green-700"
  }

  function getAddonStatusLabel(enabled: boolean, expiresAt: string | null) {
    if (!enabled) return "Desabilitado"
    if (isAddonExpired(expiresAt)) return "Expirado"
    return "Ativo"
  }

  function formatDateTime(dateString: string) {
    return new Date(dateString).toLocaleDateString("pt-BR", {
      day: "2-digit",
      month: "2-digit",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    })
  }

  function formatDate(dateString: string) {
    return new Date(dateString).toLocaleDateString("pt-BR", {
      day: "2-digit",
      month: "2-digit",
      year: "numeric",
    })
  }

  function isExpired(expiresAt: string) {
    return new Date(expiresAt) < new Date()
  }

  // Filter available addons that aren't already granted to the user
  const grantableAddons = availableAddons.filter(
    (addon) => !userAddonGrants.some((grant) => grant.addonSlug === addon.slug)
  )

  return (
    <div className="fixed inset-0 bg-app-fg/50 flex items-center justify-center z-50">
      <Card className="w-full max-w-4xl mx-4 max-h-[90vh] overflow-y-auto">
        <CardHeader>
          <CardTitle>Detalhes do Usuário</CardTitle>
          <CardDescription>
            Visualize e gerencie informações do usuário
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* User Basic Info */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 p-4 bg-muted/50 rounded-lg">
            <div>
              <Label className="text-muted-foreground text-sm">Nome</Label>
              <p className="font-medium">{user.name}</p>
            </div>
            <div>
              <Label className="text-muted-foreground text-sm">Email</Label>
              <p className="font-medium">{user.email}</p>
            </div>
            <div>
              <Label className="text-muted-foreground text-sm">Criado em</Label>
              <p className="font-medium">{formatDate(user.createdAt)}</p>
            </div>
            <div>
              <Label className="text-muted-foreground text-sm">Status</Label>
              <div className="flex items-center gap-2 mt-1">
                {user.isAdmin && (
                  <span className="px-2 py-0.5 rounded text-xs bg-blue-100 text-blue-700">
                    Admin
                  </span>
                )}
                {user.emailVerified ? (
                  <span className="px-2 py-0.5 rounded text-xs bg-green-100 text-green-700">
                    Email Verificado
                  </span>
                ) : (
                  <span className="px-2 py-0.5 rounded text-xs bg-yellow-100 text-yellow-700">
                    Email Pendente
                  </span>
                )}
              </div>
            </div>
          </div>

          {/* Subscription Info */}
          <div>
            <h3 className="text-lg font-medium mb-3">Assinatura</h3>
            {user.subscription?.plan ? (
              <div className="p-4 border rounded-lg">
                <div className="flex items-center gap-2 mb-2">
                  <span className="font-medium">{user.subscription.plan.name}</span>
                  <span
                    className={`px-2 py-0.5 rounded text-xs ${
                      isExpired(user.subscription.expiresAt)
                        ? "bg-destructive/20 text-destructive"
                        : "bg-green-100 text-green-700"
                    }`}
                  >
                    {isExpired(user.subscription.expiresAt) ? "Expirada" : "Ativa"}
                  </span>
                </div>
                <p className="text-sm text-muted-foreground">
                  Expira em: {formatDate(user.subscription.expiresAt)}
                </p>
              </div>
            ) : (
              <p className="text-muted-foreground p-4 border rounded-lg">
                Nenhuma assinatura ativa
              </p>
            )}
          </div>

          {/* User Addons Section */}
          <div>
            <div className="flex justify-between items-center mb-3">
              <h3 className="text-lg font-medium">Addons Pessoais</h3>
              <Button
                onClick={() => setGrantModalOpen(true)}
                disabled={grantableAddons.length === 0}
                size="sm"
              >
                Conceder Addon
              </Button>
            </div>

            {loadingAddons ? (
              <div className="text-center py-8 text-muted-foreground">
                Carregando addons...
              </div>
            ) : userAddonGrants.length === 0 ? (
              <div className="text-center py-8 text-muted-foreground border rounded-lg">
                Nenhum addon concedido para este usuário.
              </div>
            ) : (
              <div className="space-y-3">
                {userAddonGrants.map((grant) => (
                  <div
                    key={grant.id}
                    className="flex flex-col md:flex-row md:items-center justify-between gap-4 p-4 border rounded-lg"
                  >
                    <div className="flex-1 space-y-1">
                      <div className="flex items-center gap-2">
                        <span className="font-medium">
                          {grant.addon?.name || grant.addonSlug}
                        </span>
                        <span
                          className={`px-2 py-0.5 rounded text-xs ${getAddonStatusBadgeClass(
                            grant.enabled,
                            grant.expiresAt
                          )}`}
                        >
                          {getAddonStatusLabel(grant.enabled, grant.expiresAt)}
                        </span>
                      </div>
                      {grant.addon?.description && (
                        <p className="text-sm text-muted-foreground">
                          {grant.addon.description}
                        </p>
                      )}
                      <div className="text-xs text-muted-foreground space-y-0.5">
                        <p>Concedido em: {formatDateTime(grant.grantedAt)}</p>
                        {grant.expiresAt && (
                          <p>
                            Expira em: {formatDateTime(grant.expiresAt)}
                            {isAddonExpired(grant.expiresAt) && (
                              <span className="text-destructive ml-1">(expirado)</span>
                            )}
                          </p>
                        )}
                        {grant.grantedByUser && (
                          <p>Por: {grant.grantedByUser.name}</p>
                        )}
                      </div>
                    </div>
                    <div className="flex items-center gap-3">
                      <div className="flex items-center gap-2">
                        <Label
                          htmlFor={`toggle-${grant.id}`}
                          className="text-sm text-muted-foreground"
                        >
                          {grant.enabled ? "Habilitado" : "Desabilitado"}
                        </Label>
                        <Switch
                          id={`toggle-${grant.id}`}
                          checked={grant.enabled}
                          disabled={togglingAddon === grant.addonSlug}
                          onCheckedChange={() =>
                            toggleAddon(grant.addonSlug, grant.enabled)
                          }
                          aria-label={`Toggle ${grant.addon?.name || grant.addonSlug}`}
                        />
                      </div>
                      <Button
                        variant="outline"
                        size="sm"
                        className="text-destructive hover:text-destructive"
                        onClick={() => revokeAddon(grant.addonSlug)}
                        disabled={revokingAddon}
                      >
                        Revogar
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Footer */}
          <div className="flex justify-end pt-4 border-t">
            <Button variant="outline" onClick={onClose}>
              Fechar
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Grant Addon Modal */}
      {grantModalOpen && (
        <div className="fixed inset-0 bg-app-fg/50 flex items-center justify-center z-[60]">
          <Card className="w-full max-w-md mx-4">
            <CardHeader>
              <CardTitle>Conceder Addon</CardTitle>
              <CardDescription>
                Conceder addon para {user.name} ({user.email})
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="addon-select">Addon</Label>
                <Select
                  value={selectedAddonSlug}
                  onValueChange={setSelectedAddonSlug}
                >
                  <SelectTrigger id="addon-select">
                    <SelectValue placeholder="Selecione um addon" />
                  </SelectTrigger>
                  <SelectContent>
                    {grantableAddons.map((addon) => (
                      <SelectItem key={addon.id} value={addon.slug}>
                        {addon.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                {grantableAddons.length === 0 && (
                  <p className="text-sm text-muted-foreground">
                    Todos os addons disponíveis já foram concedidos.
                  </p>
                )}
              </div>
              <div className="space-y-2">
                <Label htmlFor="addon-expires-at">Data de Expiração (opcional)</Label>
                <Input
                  id="addon-expires-at"
                  type="date"
                  value={addonExpiresAt}
                  onChange={(e) => setAddonExpiresAt(e.target.value)}
                />
                <p className="text-xs text-muted-foreground">
                  Deixe vazio para concessão sem expiração.
                </p>
              </div>
              <div className="flex gap-2 justify-end pt-4">
                <Button
                  variant="outline"
                  onClick={() => {
                    setGrantModalOpen(false)
                    setSelectedAddonSlug("")
                    setAddonExpiresAt("")
                  }}
                >
                  Cancelar
                </Button>
                <Button
                  onClick={grantAddon}
                  disabled={!selectedAddonSlug || grantingAddon}
                >
                  {grantingAddon ? "Concedendo..." : "Conceder"}
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      )}
    </div>
  )
}
