// app/anuncios/components/image-modal.tsx
"use client"

/* eslint-disable @next/next/no-img-element */

import { useState, useEffect, useCallback } from "react"
import {
  Home,
  ImageIcon,
  Save,
  ChevronLeft,
  ChevronRight,
  Plus,
  Trash2,
  Download,
  Loader2,
} from "lucide-react"
import { ListingLocationMiniMap } from "./listing-location-mini-map"
import { Card, CardContent, CardHeader } from "@/components/ui/card"
import { ModalCloseButton, ModalHeaderTitle } from "./modal-chrome"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { useCollections } from "../lib/use-collections"
import type { Imovel } from "../lib/api"
import { enqueueListingImageIngestion } from "../lib/api"
import {
  resolveListingImages,
  syncListingImageFields,
  isListingImageIngesting,
  isExternalListingImageUrl,
} from "@/lib/listing-images"
import { cn } from "@/lib/utils"

interface ImageModalProps {
  isOpen: boolean
  onClose: () => void
  listing: Imovel | null
  onListingUpdated?: () => void
}

export function ImageModal({
  isOpen,
  onClose,
  listing,
  onListingUpdated,
}: ImageModalProps) {
  const { updateListing: apiUpdateListing, refreshListing } = useCollections()
  const [imageUrls, setImageUrls] = useState<string[]>([])
  const [currentIndex, setCurrentIndex] = useState(0)
  const [error, setError] = useState<string | null>(null)
  const [imageError, setImageError] = useState(false)
  const [isSaving, setIsSaving] = useState(false)
  const [isPulling, setIsPulling] = useState(false)
  const [confirmPullOpen, setConfirmPullOpen] = useState(false)

  const isIngesting = listing
    ? isListingImageIngesting(listing.imageIngestionStatus)
    : false

  useEffect(() => {
    if (isOpen && listing) {
      const resolved = resolveListingImages({
        listingId: listing.id,
        imageUrl: listing.imageUrl,
        imageUrls: listing.imageUrls,
        imageStorageKeys: listing.imageStorageKeys,
      })
      setImageUrls(resolved.imageUrls)
      setCurrentIndex(0)
      setError(null)
      setImageError(false)
      setConfirmPullOpen(false)
    }
  }, [isOpen, listing])

  const currentUrl = imageUrls[currentIndex] ?? ""
  const hasLink = Boolean(listing?.link?.trim())

  useEffect(() => {
    setImageError(false)
  }, [currentUrl, currentIndex])

  const handleSave = async () => {
    if (!listing) return

    const hasExternal = imageUrls.some((url) => isExternalListingImageUrl(url))
    if (hasExternal) {
      setError(
        "URLs externas não são suportadas. Use Buscar do anúncio para importar imagens hospedadas."
      )
      return
    }

    setIsSaving(true)
    setError(null)
    try {
      const synced = syncListingImageFields(imageUrls)
      await apiUpdateListing(listing.id, {
        imageUrls: synced.imageUrls,
        imageUrl: synced.imageUrl,
      })
      onListingUpdated?.()
      onClose()
    } catch (err) {
      setError(err instanceof Error ? err.message : "Erro ao salvar alterações")
    } finally {
      setIsSaving(false)
    }
  }

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Escape") {
      if (confirmPullOpen) {
        setConfirmPullOpen(false)
      } else {
        onClose()
      }
    } else if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) {
      handleSave()
    } else if (e.key === "ArrowLeft" && imageUrls.length > 1) {
      setCurrentIndex((i) => (i - 1 + imageUrls.length) % imageUrls.length)
    } else if (e.key === "ArrowRight" && imageUrls.length > 1) {
      setCurrentIndex((i) => (i + 1) % imageUrls.length)
    }
  }

  const updateCurrentUrl = (value: string) => {
    setImageUrls((prev) => {
      const next = [...prev]
      if (currentIndex < next.length) {
        next[currentIndex] = value
      } else if (value.trim()) {
        next.push(value)
      }
      return next
    })
    setError(null)
  }

  const handleDeleteCurrent = () => {
    setImageUrls((prev) => {
      const next = prev.filter((_, i) => i !== currentIndex)
      setCurrentIndex((idx) => Math.min(idx, Math.max(0, next.length - 1)))
      return next
    })
  }

  const handleAddUrl = () => {
    setImageUrls((prev) => [...prev, ""])
    setCurrentIndex(imageUrls.length)
  }

  const handlePullFromLink = () => {
    if (!listing?.link?.trim()) return
    setConfirmPullOpen(true)
  }

  const applyPullOverwrite = useCallback(async () => {
    if (!listing?.link?.trim()) return
    setIsPulling(true)
    setError(null)
    setConfirmPullOpen(false)
    try {
      await enqueueListingImageIngestion(listing.id)
      await refreshListing(listing.id)
      onListingUpdated?.()
    } catch (err) {
      setError(err instanceof Error ? err.message : "Erro ao buscar imagens")
    } finally {
      setIsPulling(false)
    }
  }, [listing, onListingUpdated, refreshListing])

  if (!isOpen || !listing) return null

  return (
    <div className="fixed inset-0 z-[1000] flex items-center justify-center">
      <div
        className="absolute inset-0 bg-app-fg/80 backdrop-blur-sm"
        onClick={onClose}
      />

      <Card
        className="relative z-10 w-full max-w-3xl mx-4 bg-app-surface border-app-border max-h-[90vh] overflow-hidden flex flex-col"
        onKeyDown={handleKeyDown}
      >
        <CardHeader className="flex flex-row items-center justify-between pb-2 gap-2">
          <ModalHeaderTitle icon={ImageIcon} title="Imagens do Imóvel" />
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handlePullFromLink}
              disabled={!hasLink || isPulling || isIngesting}
              title={
                hasLink
                  ? "Buscar imagens do link do anúncio"
                  : "Adicione o link do anúncio para buscar imagens"
              }
              className={cn(
                "flex items-center gap-1.5 py-1.5 px-3 rounded-lg text-sm font-medium transition-all",
                "bg-app-surface-muted border border-app-border text-app-fg",
                "hover:border-app-action hover:text-app-accent",
                "disabled:opacity-50 disabled:cursor-not-allowed"
              )}
            >
              {isPulling || isIngesting ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Download className="h-4 w-4" />
              )}
              Buscar do anúncio
            </button>
            <ModalCloseButton onClick={onClose} />
          </div>
        </CardHeader>
        <CardContent className="flex-1 flex flex-col gap-4 overflow-y-auto">
          {error && (
            <div className="bg-destructive/10 border border-destructive/30 rounded-lg p-3">
              <p className="text-sm text-destructive">{error}</p>
            </div>
          )}

          {listing.imageIngestionStatus === "failed" && listing.imageIngestionError && (
            <div className="bg-amber-500/10 border border-amber-500/30 rounded-lg p-3">
              <p className="text-sm text-amber-800 dark:text-amber-200">
                {listing.imageIngestionError}
              </p>
            </div>
          )}

          <div className="flex items-center justify-center min-h-[200px] max-h-[70vh] bg-app-surface-muted rounded-lg border border-app-border overflow-hidden relative">
            {imageUrls.length > 1 && !isIngesting && (
              <>
                <button
                  type="button"
                  onClick={() =>
                    setCurrentIndex(
                      (i) => (i - 1 + imageUrls.length) % imageUrls.length
                    )
                  }
                  className="absolute left-2 z-10 p-2 rounded-full bg-app-fg/60 text-app-surface hover:bg-app-fg/80"
                  aria-label="Imagem anterior"
                >
                  <ChevronLeft className="h-5 w-5" />
                </button>
                <button
                  type="button"
                  onClick={() =>
                    setCurrentIndex((i) => (i + 1) % imageUrls.length)
                  }
                  className="absolute right-2 z-10 p-2 rounded-full bg-app-fg/60 text-app-surface hover:bg-app-fg/80"
                  aria-label="Próxima imagem"
                >
                  <ChevronRight className="h-5 w-5" />
                </button>
              </>
            )}

            {isIngesting ? (
              <div className="flex flex-col items-center justify-center gap-3 text-muted-foreground">
                <Loader2 className="h-10 w-10 animate-spin text-app-accent" />
                <span className="text-sm">Baixando imagens do anúncio…</span>
              </div>
            ) : currentUrl && !imageError ? (
              <img
                key={currentUrl}
                src={currentUrl}
                alt={listing.titulo}
                className="max-w-full max-h-[70vh] object-contain"
                onError={() => setImageError(true)}
                onLoad={() => setImageError(false)}
              />
            ) : currentUrl && imageError ? (
              <div className="flex flex-col items-center justify-center h-full w-full text-muted-foreground">
                <ImageIcon className="h-12 w-12 mb-2 text-muted-foreground" />
                <span className="text-sm">Erro ao carregar imagem</span>
              </div>
            ) : (
              <ListingLocationMiniMap
                listing={listing}
                variant="preview"
                className="w-full min-h-[200px] max-h-[70vh] border-0"
                fallback={
                  <div className="flex flex-col items-center justify-center h-full w-full text-muted-foreground">
                    <Home className="h-12 w-12 mb-2 text-muted-foreground" />
                    <span className="text-sm">Nenhuma imagem</span>
                  </div>
                }
              />
            )}
          </div>

          {imageUrls.length > 0 && !isIngesting && (
            <p className="text-xs text-center text-muted-foreground">
              Imagem {currentIndex + 1} de {imageUrls.length}
            </p>
          )}

          <div className="space-y-2">
            <Label htmlFor="imageUrlCurrent" className="text-sm text-app-muted">
              URL da imagem atual
            </Label>
            <Input
              id="imageUrlCurrent"
              type="url"
              value={currentUrl}
              onChange={(e) => updateCurrentUrl(e.target.value)}
              placeholder="/api/listings/…/images/0"
              disabled={isIngesting}
              className="bg-app-surface-muted border-app-border text-app-fg placeholder:text-muted-foreground"
            />
            <div className="flex gap-2 pt-1">
              <button
                type="button"
                onClick={handleAddUrl}
                disabled={isIngesting}
                className={cn(
                  "flex items-center gap-1.5 py-1.5 px-3 rounded-lg text-sm",
                  "bg-app-surface-muted border border-app-border text-app-fg",
                  "hover:border-app-action"
                )}
              >
                <Plus className="h-4 w-4" />
                Adicionar URL
              </button>
              {imageUrls.length > 0 && (
                <button
                  type="button"
                  onClick={handleDeleteCurrent}
                  disabled={isIngesting}
                  className={cn(
                    "flex items-center gap-1.5 py-1.5 px-3 rounded-lg text-sm",
                    "border border-destructive/40 text-destructive",
                    "hover:bg-destructive/10"
                  )}
                >
                  <Trash2 className="h-4 w-4" />
                  Remover
                </button>
              )}
            </div>
            <p className="text-xs text-muted-foreground">
              Use Buscar do anúncio para importar fotos hospedadas. A primeira imagem
              é a miniatura na tabela.
            </p>
          </div>

          <div className="flex gap-3 pt-4 border-t border-app-border">
            <button
              onClick={onClose}
              disabled={isSaving}
              className={cn(
                "flex-1 py-2.5 px-4 rounded-lg font-medium transition-all",
                "bg-app-surface-muted border border-app-border text-app-fg",
                "hover:border-app-action hover:text-app-accent"
              )}
            >
              Cancelar
            </button>
            <button
              onClick={handleSave}
              disabled={isSaving || isIngesting}
              className={cn(
                "flex-1 py-2.5 px-4 rounded-lg font-medium transition-all",
                "bg-app-action text-app-action-foreground",
                "hover:bg-app-action-hover",
                "flex items-center justify-center gap-2",
                "disabled:opacity-60"
              )}
            >
              {isSaving ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Save className="h-4 w-4" />
              )}
              Salvar
            </button>
          </div>
        </CardContent>
      </Card>

      {confirmPullOpen && (
        <div className="fixed inset-0 z-[1010] flex items-center justify-center">
          <div
            className="absolute inset-0 bg-app-fg/60"
            onClick={() => setConfirmPullOpen(false)}
          />
          <Card className="relative z-10 w-full max-w-md mx-4 bg-app-surface border-app-border p-4">
            <h3 className="text-lg font-semibold text-app-fg mb-2">
              Substituir imagens?
            </h3>
            <p className="text-sm text-muted-foreground mb-4">
              O sistema vai buscar as fotos no link do anúncio, baixá-las e substituir
              a galeria atual. Isso pode levar alguns minutos.
            </p>
            <div className="flex gap-3">
              <button
                type="button"
                onClick={() => setConfirmPullOpen(false)}
                className={cn(
                  "flex-1 py-2 px-4 rounded-lg text-sm font-medium",
                  "bg-app-surface-muted border border-app-border"
                )}
              >
                Cancelar
              </button>
              <button
                type="button"
                onClick={applyPullOverwrite}
                disabled={isPulling}
                className={cn(
                  "flex-1 py-2 px-4 rounded-lg text-sm font-medium",
                  "bg-app-action text-app-action-foreground flex items-center justify-center gap-2"
                )}
              >
                {isPulling ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : null}
                Substituir
              </button>
            </div>
          </Card>
        </div>
      )}
    </div>
  )
}

// apps/web/src/lib/components/listings/ImageModal.svelte
<script lang="ts">
  import {
    Home,
    Image as ImageIcon,
    Save,
    ChevronLeft,
    ChevronRight,
    Plus,
    Trash2,
    Download,
    Loader2
  } from "@lucide/svelte";
  import Card from "$lib/components/ui/Card.svelte";
  import Input from "$lib/components/ui/Input.svelte";
  import ModalCloseButton from "$lib/components/listings/ModalCloseButton.svelte";
  import ListingLocationMiniMap from "$lib/components/listings/ListingLocationMiniMap.svelte";
  import FloatingTooltip from "$lib/components/ui/FloatingTooltip.svelte";
  import type { Property } from "$lib/listings/types";
  import { getCollectionsContext } from "$lib/collections-context.svelte";
  import { workspaceApi } from "$lib/workspace/client";
  import { resolveListingGalleryImages } from "$lib/listing-gallery";
  import {
    syncListingImageFields,
    isListingImageIngesting,
    isExternalListingImageUrl
  } from "$lib/listing-images";
  import { cn } from "$lib/utils";
  import ListingImageCarousel from "$lib/carousel/ListingImageCarousel.svelte";

  let {
    isOpen,
    onClose,
    listing,
    onListingUpdated
  } = $props<{
    isOpen: boolean;
    onClose: () => void;
    listing: Property | null;
    onListingUpdated?: () => void;
  }>();

  const ctx = getCollectionsContext();

  let imageUrls = $state<string[]>([]);
  let currentIndex = $state(0);
  let error = $state<string | null>(null);
  let imageError = $state(false);
  let isSaving = $state(false);
  let isPulling = $state(false);
  let confirmPullOpen = $state(false);
  let modalCarouselRef = $state<ReturnType<typeof ListingImageCarousel> | undefined>();
  const canNavigateImages = $derived(imageUrls.length > 1);

  const isIngesting = $derived(listing ? isListingImageIngesting(listing.imageIngestionStatus) : false);
  const currentUrl = $derived(imageUrls[currentIndex] ?? "");
  const hasLink = $derived(Boolean(listing?.sourceUrl?.trim()));

  $effect(() => {
    if (isOpen && listing) {
      imageUrls = resolveListingGalleryImages(listing).map((image) => image.url);
      currentIndex = 0;
      error = null;
      imageError = false;
      confirmPullOpen = false;
    }
  });

  $effect(() => {
    void currentUrl;
    void currentIndex;
    imageError = false;
  });

  function updateCurrentUrl(value: string) {
    imageUrls = imageUrls.map((url, index) => (index === currentIndex ? value : url));
    if (currentIndex >= imageUrls.length && value.trim()) {
      imageUrls = [...imageUrls, value];
    }
    error = null;
  }

  function handleDeleteCurrent() {
    imageUrls = imageUrls.filter((_, index) => index !== currentIndex);
    currentIndex = Math.min(currentIndex, Math.max(0, imageUrls.length - 1));
  }

  function handleAddUrl() {
    imageUrls = [...imageUrls, ""];
    currentIndex = imageUrls.length - 1;
  }

  async function handleSave() {
    if (!listing) return;
    if (imageUrls.some((url) => isExternalListingImageUrl(url))) {
      error =
        "URLs externas não são suportadas. Use Buscar do anúncio para importar imagens hospedadas.";
      return;
    }
    isSaving = true;
    error = null;
    try {
      const synced = syncListingImageFields(imageUrls);
      await ctx.updateListing(listing.id, {
        imageUrls: synced.imageUrls,
        imageUrl: synced.imageUrl
      });
      onListingUpdated?.();
      onClose();
    } catch (err) {
      error = err instanceof Error ? err.message : "Erro ao salvar alterações";
    } finally {
      isSaving = false;
    }
  }

  async function applyPullOverwrite() {
    if (!listing?.sourceUrl?.trim()) return;
    isPulling = true;
    error = null;
    confirmPullOpen = false;
    try {
      await workspaceApi.ingestListingImages(listing.id);
      await ctx.refreshListing(listing.id);
      onListingUpdated?.();
    } catch (err) {
      error = err instanceof Error ? err.message : "Erro ao buscar imagens";
    } finally {
      isPulling = false;
    }
  }

  function handleKeyDown(event: KeyboardEvent) {
    if (event.key === "Escape") {
      if (confirmPullOpen) confirmPullOpen = false;
      else onClose();
    } else if (event.key === "Enter" && (event.metaKey || event.ctrlKey)) {
      void handleSave();
    } else if (event.key === "ArrowLeft" && imageUrls.length > 1) {
      modalCarouselRef?.scrollPrev();
    } else if (event.key === "ArrowRight" && imageUrls.length > 1) {
      modalCarouselRef?.scrollNext();
    }
  }
</script>

{#if isOpen && listing}
  <div class="fixed inset-0 z-[1000] flex items-center justify-center">
    <button type="button" class="absolute inset-0 bg-app-fg/80 backdrop-blur-sm" aria-label="Fechar" onclick={onClose}></button>

    <div
      class="relative z-10 mx-4 flex max-h-[90vh] w-full max-w-3xl flex-col overflow-hidden rounded-md border border-app-border bg-app-surface shadow-sm"
      role="dialog"
      aria-modal="true"
      tabindex="-1"
      onkeydown={handleKeyDown}
    >
      <div class="flex flex-row items-center justify-between gap-2 border-b border-app-border p-4 pb-2">
        <h2 class="flex items-center gap-2 text-lg font-semibold text-app-fg">
          <ImageIcon class="h-5 w-5" />
          Imagens do Imóvel
        </h2>
        <div class="flex items-center gap-2">
          <FloatingTooltip label={hasLink ? "Buscar imagens do link do anúncio" : "Adicione o link do anúncio para buscar imagens"} side="bottom">
            <button
              type="button"
              onclick={() => (confirmPullOpen = true)}
              disabled={!hasLink || isPulling || isIngesting}
              class={cn(
                "flex items-center gap-1.5 rounded-lg border border-app-border bg-app-surface-muted px-3 py-1.5 text-sm font-medium text-app-fg transition-all hover:border-app-action hover:text-app-accent disabled:cursor-not-allowed disabled:opacity-50"
              )}
            >
              {#if isPulling || isIngesting}
                <Loader2 class="h-4 w-4 animate-spin" />
              {:else}
                <Download class="h-4 w-4" />
              {/if}
              Buscar do anúncio
            </button>
          </FloatingTooltip>
          <ModalCloseButton onclick={onClose} />
        </div>
      </div>

      <div class="flex flex-1 flex-col gap-4 overflow-y-auto p-4">
        {#if error}
          <div class="rounded-lg border border-destructive/30 bg-destructive/10 p-3">
            <p class="text-sm text-destructive">{error}</p>
          </div>
        {/if}

        {#if listing.imageIngestionStatus === "failed" && listing.imageIngestionError}
          <div class="rounded-lg border border-amber-500/30 bg-amber-500/10 p-3">
            <p class="text-sm text-amber-800 dark:text-amber-200">{listing.imageIngestionError}</p>
          </div>
        {/if}

        <div class="relative flex min-h-[200px] max-h-[70vh] items-center justify-center overflow-hidden rounded-lg border border-app-border bg-app-surface-muted">
          {#if imageUrls.length > 1 && !isIngesting}
            <button
              type="button"
              class="absolute left-2 z-10 rounded-full bg-app-fg/60 p-2 text-app-surface hover:bg-app-fg/80 disabled:opacity-40"
              aria-label="Imagem anterior"
              disabled={!canNavigateImages}
              onclick={() => modalCarouselRef?.scrollPrev()}
            >
              <ChevronLeft class="h-5 w-5" />
            </button>
            <button
              type="button"
              class="absolute right-2 z-10 rounded-full bg-app-fg/60 p-2 text-app-surface hover:bg-app-fg/80 disabled:opacity-40"
              aria-label="Próxima imagem"
              disabled={!canNavigateImages}
              onclick={() => modalCarouselRef?.scrollNext()}
            >
              <ChevronRight class="h-5 w-5" />
            </button>
          {/if}

          {#if isIngesting}
            <div class="flex flex-col items-center justify-center gap-3 text-muted-foreground">
              <Loader2 class="h-10 w-10 animate-spin text-app-accent" />
              <span class="text-sm">Baixando imagens do anúncio…</span>
            </div>
          {:else if imageUrls.length > 0}
            <ListingImageCarousel
              bind:this={modalCarouselRef}
              urls={imageUrls}
              preset="modal"
              bind:selectedIndex={currentIndex}
              imageAlt={listing.title}
              objectFit="contain"
              viewportClass="flex min-h-[200px] max-h-[70vh] w-full items-center justify-center"
            >
              {#snippet slide({ url, isSelected })}
                {#if isSelected && imageError}
                  <div class="flex h-full min-h-[200px] w-full flex-col items-center justify-center text-muted-foreground">
                    <ImageIcon class="mb-2 h-12 w-12" />
                    <span class="text-sm">Erro ao carregar imagem</span>
                  </div>
                {:else}
                  <img
                    src={url}
                    alt={listing.title}
                    class="mx-auto max-h-[70vh] max-w-full object-contain"
                    onerror={() => {
                      if (isSelected) imageError = true;
                    }}
                    onload={() => {
                      if (isSelected) imageError = false;
                    }}
                  />
                {/if}
              {/snippet}
            </ListingImageCarousel>
          {:else}
            <ListingLocationMiniMap listing={listing} variant="preview" class="min-h-[200px] w-full max-h-[70vh] border-0">
              {#snippet fallback()}
                <div class="flex h-full w-full flex-col items-center justify-center text-muted-foreground">
                  <Home class="mb-2 h-12 w-12" />
                  <span class="text-sm">Nenhuma imagem</span>
                </div>
              {/snippet}
            </ListingLocationMiniMap>
          {/if}
        </div>

        {#if imageUrls.length > 0 && !isIngesting}
          <p class="text-center text-xs text-muted-foreground">
            Imagem {currentIndex + 1} de {imageUrls.length}
          </p>
        {/if}

        <div class="space-y-2">
          <label for="imageUrlCurrent" class="text-sm text-app-muted">URL da imagem atual</label>
          <Input
            id="imageUrlCurrent"
            type="url"
            value={currentUrl}
            oninput={(e) => updateCurrentUrl(e.currentTarget.value)}
            placeholder="/api/listings/…/images/0"
            disabled={isIngesting}
            class="border-app-border bg-app-surface-muted text-app-fg"
          />
          <div class="flex gap-2 pt-1">
            <button type="button" onclick={handleAddUrl} disabled={isIngesting} class="flex items-center gap-1.5 rounded-lg border border-app-border bg-app-surface-muted px-3 py-1.5 text-sm hover:border-app-action">
              <Plus class="h-4 w-4" />
              Adicionar URL
            </button>
            {#if imageUrls.length > 0}
              <button type="button" onclick={handleDeleteCurrent} disabled={isIngesting} class="flex items-center gap-1.5 rounded-lg border border-destructive/40 px-3 py-1.5 text-sm text-destructive hover:bg-destructive/10">
                <Trash2 class="h-4 w-4" />
                Remover
              </button>
            {/if}
          </div>
          <p class="text-xs text-muted-foreground">
            Use Buscar do anúncio para importar fotos hospedadas. A primeira imagem é a miniatura na tabela.
          </p>
        </div>

        <div class="flex gap-3 border-t border-app-border pt-4">
          <button type="button" onclick={onClose} disabled={isSaving} class="flex-1 rounded-lg border border-app-border bg-app-surface-muted px-4 py-2.5 font-medium text-app-fg hover:border-app-action hover:text-app-accent">
            Cancelar
          </button>
          <button type="button" onclick={() => void handleSave()} disabled={isSaving || isIngesting} class="flex flex-1 items-center justify-center gap-2 rounded-lg bg-app-action px-4 py-2.5 font-medium text-app-action-foreground hover:bg-app-action-hover disabled:opacity-60">
            {#if isSaving}
              <Loader2 class="h-4 w-4 animate-spin" />
            {:else}
              <Save class="h-4 w-4" />
            {/if}
            Salvar
          </button>
        </div>
      </div>
    </div>

    {#if confirmPullOpen}
      <div class="fixed inset-0 z-[1010] flex items-center justify-center">
        <button type="button" class="absolute inset-0 bg-app-fg/60" aria-label="Fechar" onclick={() => (confirmPullOpen = false)}></button>
        <Card class="relative z-10 mx-4 w-full max-w-md border-app-border bg-app-surface p-4">
          <h3 class="mb-2 text-lg font-semibold text-app-fg">Substituir imagens?</h3>
          <p class="mb-4 text-sm text-muted-foreground">
            O sistema vai buscar as fotos no link do anúncio, baixá-las e substituir a galeria atual. Isso pode levar alguns minutos.
          </p>
          <div class="flex gap-3">
            <button type="button" onclick={() => (confirmPullOpen = false)} class="flex-1 rounded-lg border border-app-border bg-app-surface-muted px-4 py-2 text-sm font-medium">
              Cancelar
            </button>
            <button type="button" onclick={() => void applyPullOverwrite()} disabled={isPulling} class="flex flex-1 items-center justify-center gap-2 rounded-lg bg-app-action px-4 py-2 text-sm font-medium text-app-action-foreground">
              {#if isPulling}<Loader2 class="h-4 w-4 animate-spin" />{/if}
              Substituir
            </button>
          </div>
        </Card>
      </div>
    {/if}
  </div>
{/if}
