// app/anuncios/components/listing-mobile-card.tsx
"use client"

import { memo, useMemo } from "react"
import { ListingTitleLinks, truncateListingTitle } from "@/components/listing-title-links"
import { FaWhatsapp } from "react-icons/fa"
import { cn } from "@/lib/utils"
import { mobileCompactListingDisplayTitle } from "@/lib/listing-display-title"
import { ClickablePrice } from "./clickable-price"
import { ListingMobileMetricRow } from "./listings-metric-stacks"
import { buildWhatsAppUrl } from "@/app/anuncios/lib/listings-contact"
import { buildGoogleMapsUrl, calculatePrecoM2, calculatePrecoM2Privado } from "./listing-row-urls"
import { useListingRowInteractions } from "./use-listing-row-interactions"
import { ListingStarButton } from "./listing-star-button"
import { ListingPropertyIconToolbar } from "./listing-property-icon-toolbar"
import { ListingRowStatusActions } from "./listing-row-status-actions"
import { ListingMobileCardBackdrop } from "./listing-mobile-card-backdrop"
import type { ListingTableRowProps } from "./listing-table-row"
import {
  LISTING_MOBILE_EDGE_INSET_CLASS,
  LISTING_MOBILE_ROW_GAP_CLASS,
} from "./listings-table-shared"

const MOBILE_IMAGE_COLUMN_CLASS = "relative w-[11.5rem] shrink-0 self-stretch"
const MOBILE_TOOLBAR_DENSITY = "mobile" as const

const MOBILE_TITLE_OVERLAY_SCRIM =
  "bg-gradient-to-b from-black/75 via-black/45 to-transparent"

const MOBILE_OVERLAY_SCRIM_BOTTOM =
  "pointer-events-none absolute inset-x-0 bottom-0 z-[1] h-10 bg-gradient-to-t from-black/75 via-black/35 to-transparent"

function ListingMobileCardInner({
  imovel,
  visibleColumns,
  imageColumnView,
  enabledMetricVariants,
  propertyDisplay,
  activeMetricVariant,
  uniqueContacts,
  hasOtherCollections,
  collections,
  activeCollectionId,
  updateListing,
  removeListing,
  openImageModal,
  openEditListing,
  onQuickReparseRequest,
  onQuickReparseDetected,
  displayTitle,
}: ListingTableRowProps) {
  const interactions = useListingRowInteractions({
    imovel,
    updateListing,
    removeListing,
    onQuickReparseRequest,
    onQuickReparseDetected,
  })

  const mobileCompactTitle = useMemo(
    () => mobileCompactListingDisplayTitle(displayTitle),
    [displayTitle]
  )

  const mobileTitleTruncated = useMemo(
    () => truncateListingTitle(mobileCompactTitle, 48),
    [mobileCompactTitle]
  )

  const showPropertyIcons =
    propertyDisplay.showPropertyIcons && visibleColumns.property
  const showAddress = propertyDisplay.showAddress
  const showPrice = visibleColumns.price
  const showMetrics = visibleColumns.area || visibleColumns.value
  const showImage = visibleColumns.image
  const showStatus = visibleColumns.status
  const showContact =
    propertyDisplay.showContact && Boolean(imovel.contactNumber)

  const showUnifiedRight =
    showStatus ||
    showPropertyIcons ||
    showPrice ||
    showMetrics ||
    showContact
  const showAsideRows = showPrice || showMetrics || showContact
  const showUnifiedRow = showImage
  const showFallbackHeader = !showImage
  const showFallbackBottom = !showImage && (showAddress || showContact || showStatus)

  const rowActionsProps = {
    imovel,
    interactions,
    uniqueContacts,
    hasOtherCollections,
    collections,
    activeCollectionId,
    openEditListing,
  }

  const mobileContactLink =
    showContact &&
    (() => {
      const whatsappUrl = buildWhatsAppUrl(imovel.contactNumber)
      if (!whatsappUrl) return null
      return (
        <a
          data-testid="listing-mobile-contact"
          href={whatsappUrl}
          target="_blank"
          rel="noopener noreferrer"
          className={cn(
            "flex min-w-0 max-w-full items-center gap-1 truncate text-[10px] text-green-600 transition-colors hover:text-green-500",
            imovel.strikethrough && "line-through opacity-50"
          )}
          title={
            imovel.contactName
              ? `WhatsApp — ${imovel.contactName}`
              : "Abrir WhatsApp"
          }
        >
          <FaWhatsapp className="h-3 w-3 shrink-0" />
          <span className="truncate">
            {imovel.contactName ?? imovel.contactNumber}
          </span>
        </a>
      )
    })()

  const mobileToolbarProps = { density: MOBILE_TOOLBAR_DENSITY }

  const unifiedRightTopRows = (
    <>
      {showStatus && (
        <div
          data-testid="listing-mobile-status-row"
          className="flex min-w-0 items-center leading-none"
        >
          <ListingRowStatusActions
            {...rowActionsProps}
            {...mobileToolbarProps}
            part="status"
          />
        </div>
      )}

      {showPropertyIcons && (
        <div
          data-testid="listing-mobile-property-row"
          className="flex min-w-0 items-center leading-none"
        >
          <ListingPropertyIconToolbar
            imovel={imovel}
            interactions={interactions}
            {...mobileToolbarProps}
            className="justify-start"
          />
        </div>
      )}

      {showPrice && (
        <div
          data-testid="listing-mobile-price"
          className="flex items-center leading-none"
        >
          <ClickablePrice
            price={imovel.preco}
            strikethrough={imovel.strikethrough}
          />
        </div>
      )}

      {showMetrics && enabledMetricVariants.has("total") && (
        <ListingMobileMetricRow
          data-testid="listing-mobile-metrics-total"
          area={imovel.m2Totais}
          pricePerM2={calculatePrecoM2(imovel.preco, imovel.m2Totais)}
          variant="total"
          activeVariant={activeMetricVariant}
          emphasizeWhenSorted={activeMetricVariant !== null}
          className={imovel.strikethrough ? "line-through opacity-50" : undefined}
        />
      )}

      {showMetrics && enabledMetricVariants.has("privado") && (
        <ListingMobileMetricRow
          data-testid="listing-mobile-metrics-privado"
          area={imovel.m2Privado}
          pricePerM2={calculatePrecoM2Privado(imovel.preco, imovel.m2Privado)}
          variant="privado"
          activeVariant={activeMetricVariant}
          emphasizeWhenSorted={activeMetricVariant !== null}
          className={imovel.strikethrough ? "line-through opacity-50" : undefined}
        />
      )}
    </>
  )

  const unifiedRightBottomRows =
    (showStatus || mobileContactLink) && (
      <div
        data-testid="listing-mobile-actions-row"
        className={cn(
          "mt-auto flex min-w-0 flex-col leading-none",
          LISTING_MOBILE_ROW_GAP_CLASS
        )}
      >
        {showStatus && (
          <ListingRowStatusActions
            {...rowActionsProps}
            {...mobileToolbarProps}
            part="actions"
          />
        )}
        {mobileContactLink}
      </div>
    )

  const fallbackAsideRows = (
    <>
      {showPrice && (
        <div
          data-testid="listing-mobile-price"
          className="flex items-center leading-none"
        >
          <ClickablePrice
            price={imovel.preco}
            strikethrough={imovel.strikethrough}
          />
        </div>
      )}

      {showMetrics && enabledMetricVariants.has("total") && (
        <ListingMobileMetricRow
          data-testid="listing-mobile-metrics-total"
          area={imovel.m2Totais}
          pricePerM2={calculatePrecoM2(imovel.preco, imovel.m2Totais)}
          variant="total"
          activeVariant={activeMetricVariant}
          emphasizeWhenSorted={activeMetricVariant !== null}
          className={imovel.strikethrough ? "line-through opacity-50" : undefined}
        />
      )}

      {showMetrics && enabledMetricVariants.has("privado") && (
        <ListingMobileMetricRow
          data-testid="listing-mobile-metrics-privado"
          area={imovel.m2Privado}
          pricePerM2={calculatePrecoM2Privado(imovel.preco, imovel.m2Privado)}
          variant="privado"
          activeVariant={activeMetricVariant}
          emphasizeWhenSorted={activeMetricVariant !== null}
          className={imovel.strikethrough ? "line-through opacity-50" : undefined}
        />
      )}

      {(showContact || showStatus) && (
        <div className="flex min-w-0 flex-col gap-0.5 leading-none">
          {mobileContactLink}
          {showStatus && (
            <ListingRowStatusActions {...rowActionsProps} part="actions" />
          )}
        </div>
      )}
    </>
  )

  const fallbackAsideColumn = (includeStar: boolean) => (
    <div
      data-testid="listing-mobile-aside"
      className="flex min-w-0 flex-1 flex-col gap-1"
    >
      {includeStar && (
        <ListingStarButton
          starred={imovel.starred}
          onToggle={() => void interactions.handleToggleStar()}
        />
      )}
      {showPropertyIcons && (
        <div className="flex items-center leading-none">
          <ListingPropertyIconToolbar
            imovel={imovel}
            interactions={interactions}
            density={MOBILE_TOOLBAR_DENSITY}
            className="justify-start"
          />
        </div>
      )}
      {fallbackAsideRows}
    </div>
  )

  const titleOverlay = (
    <ListingTitleLinks
      listing={imovel}
      displayTitle={mobileCompactTitle}
      collectionId={activeCollectionId}
      truncateTitle={false}
      overlayOnMedia
      className="min-w-0 flex-1"
      titleClassName="text-[11px] drop-shadow-sm"
    />
  )

  const addressOverlay = showAddress && (
    <a
      data-testid="listing-mobile-address"
      href={buildGoogleMapsUrl(imovel.endereco)}
      target="_blank"
      rel="noopener noreferrer"
      className={cn(
        "block truncate text-[10px] leading-tight text-white/95 underline decoration-white/40 decoration-dotted underline-offset-2 drop-shadow-sm transition-colors hover:text-white",
        imovel.strikethrough && "line-through opacity-50"
      )}
      title={`Abrir ${imovel.endereco} no Google Maps`}
      onClick={(event) => event.stopPropagation()}
    >
      {imovel.endereco}
    </a>
  )

  return (
    <article
      id={`listing-${imovel.id}`}
      data-testid={`listing-mobile-card-${imovel.id}`}
      className={cn(
        "overflow-hidden",
        showUnifiedRow ? "flex min-h-20" : "px-3 py-3",
        imovel.starred
          ? "border-app-action/50 bg-app-action/20"
          : "bg-app-surface"
      )}
    >
      {showFallbackHeader && (
        <div
          data-testid="listing-mobile-top"
          className="flex min-w-0 items-center gap-1"
        >
          <ListingStarButton
            starred={imovel.starred}
            onToggle={() => void interactions.handleToggleStar()}
          />
          <ListingTitleLinks
            listing={imovel}
            displayTitle={mobileTitleTruncated}
            collectionId={activeCollectionId}
            maxTitleLength={48}
            className="min-w-0 flex-1"
          />
          {showStatus && (
            <ListingRowStatusActions {...rowActionsProps} part="status" />
          )}
        </div>
      )}

      {showUnifiedRow && (
        <>
          <div
            data-testid="listing-mobile-backdrop"
            className={cn(MOBILE_IMAGE_COLUMN_CLASS, "min-h-0 overflow-hidden")}
          >
            <ListingMobileCardBackdrop
              imovel={imovel}
              view={imageColumnView}
              onOpenImageModal={() => openImageModal(imovel)}
            />
            <div aria-hidden className={MOBILE_OVERLAY_SCRIM_BOTTOM} />

            <div
              data-testid="listing-mobile-overlay-top"
              className={cn(
                "absolute inset-x-0 top-0 z-20 flex min-w-0 items-center gap-0 overflow-visible",
                LISTING_MOBILE_EDGE_INSET_CLASS,
                MOBILE_TITLE_OVERLAY_SCRIM
              )}
            >
              <ListingStarButton
                variant="on-media"
                starred={imovel.starred}
                onToggle={() => void interactions.handleToggleStar()}
              />
              {titleOverlay}
            </div>

            {showAddress && (
              <div
                data-testid="listing-mobile-overlay-bottom"
                className={cn(
                  "absolute inset-x-0 bottom-0 z-10",
                  LISTING_MOBILE_EDGE_INSET_CLASS
                )}
              >
                {addressOverlay}
              </div>
            )}
          </div>

          {showUnifiedRight && (
            <div
              data-testid="listing-mobile-body"
              className={cn(
                "flex min-h-0 min-w-0 flex-1 flex-col",
                LISTING_MOBILE_EDGE_INSET_CLASS,
                "pl-1.5"
              )}
            >
              <div
                data-testid="listing-mobile-aside"
                className="flex min-h-0 flex-1 flex-col"
              >
                <div
                  className={cn(
                    "flex min-h-0 flex-col",
                    LISTING_MOBILE_ROW_GAP_CLASS
                  )}
                >
                  {unifiedRightTopRows}
                </div>
                {unifiedRightBottomRows}
              </div>
            </div>
          )}
        </>
      )}

      {!showUnifiedRow && (showAsideRows || showPropertyIcons) && (
        <div data-testid="listing-mobile-body" className="mt-2">
          {fallbackAsideColumn(false)}
        </div>
      )}

      {showFallbackBottom && (
        <div
          data-testid="listing-mobile-bottom"
          className="mt-2 flex min-w-0 items-center justify-between gap-2"
        >
          <div className="min-w-0 flex-1">
            {showAddress && (
              <a
                data-testid="listing-mobile-address"
                href={buildGoogleMapsUrl(imovel.endereco)}
                target="_blank"
                rel="noopener noreferrer"
                className={cn(
                  "block truncate text-xs text-app-muted underline decoration-dotted underline-offset-2 transition-colors hover:text-app-fg",
                  imovel.strikethrough && "line-through opacity-50"
                )}
                title={`Abrir ${imovel.endereco} no Google Maps`}
              >
                {imovel.endereco}
              </a>
            )}
            {showContact &&
              (() => {
                const whatsappUrl = buildWhatsAppUrl(imovel.contactNumber)
                if (!whatsappUrl) return null
                return (
                  <a
                    data-testid="listing-mobile-contact"
                    href={whatsappUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className={cn(
                      "mt-0.5 flex min-w-0 items-center gap-1 truncate text-xs text-green-600 transition-colors hover:text-green-500",
                      imovel.strikethrough && "line-through opacity-50"
                    )}
                    title={
                      imovel.contactName
                        ? `WhatsApp — ${imovel.contactName}`
                        : "Abrir WhatsApp"
                    }
                  >
                    <FaWhatsapp className="h-3 w-3 shrink-0" />
                    <span className="truncate">
                      {imovel.contactName ?? imovel.contactNumber}
                    </span>
                  </a>
                )
              })()}
          </div>

          {showStatus && (
            <ListingRowStatusActions {...rowActionsProps} part="actions" />
          )}
        </div>
      )}
    </article>
  )
}

function listingMobileCardPropsAreEqual(
  prev: ListingTableRowProps,
  next: ListingTableRowProps
) {
  return (
    prev.imovel === next.imovel &&
    prev.visibleColumns === next.visibleColumns &&
    prev.imageColumnView === next.imageColumnView &&
    prev.enabledMetricVariants === next.enabledMetricVariants &&
    prev.propertyDisplay === next.propertyDisplay &&
    prev.activeMetricVariant === next.activeMetricVariant &&
    prev.uniqueContacts === next.uniqueContacts &&
    prev.hasOtherCollections === next.hasOtherCollections &&
    prev.collections === next.collections &&
    prev.activeCollectionId === next.activeCollectionId &&
    prev.updateListing === next.updateListing &&
    prev.removeListing === next.removeListing &&
    prev.openImageModal === next.openImageModal &&
    prev.openEditListing === next.openEditListing &&
    prev.onQuickReparseRequest === next.onQuickReparseRequest &&
    prev.onQuickReparseDetected === next.onQuickReparseDetected &&
    prev.displayTitle === next.displayTitle
  )
}

export const ListingMobileCard = memo(ListingMobileCardInner, listingMobileCardPropsAreEqual)

// apps/web/src/lib/components/listings/ListingMobileCard.svelte
<script lang="ts">
  import ClickablePrice from "$lib/components/listings/ClickablePrice.svelte";
  import ListingMobileMetricRow from "$lib/components/listings/ListingMobileMetricRow.svelte";
  import ListingMobileImageGallery from "$lib/components/listings/ListingMobileImageGallery.svelte";
  import ListingMobileCountFeatures from "$lib/components/listings/ListingMobileCountFeatures.svelte";
  import ListingMobileFeatureButton from "$lib/components/listings/ListingMobileFeatureButton.svelte";
  import ListingTitleStageRow from "$lib/components/listings/ListingTitleStageRow.svelte";
  import ListingRowStageSelect from "$lib/components/listings/ListingRowStageSelect.svelte";
  import {
    getListingMobileFeatures,
    layoutListingMobileFeatureRows
  } from "$lib/components/listings/listing-mobile-features";
  import { calculatePricePerM2, calculatePrivateAreaPricePerM2 } from "$lib/components/listings/listing-row-urls";
  import {
    LISTING_MOBILE_CARD_BODY_CLASS,
    LISTING_MOBILE_SUMMARY_GRID_CLASS
  } from "$lib/components/listings/listings-table-shared";
  import type { ListingTableRowProps } from "$lib/components/listings/listing-table-row-types";
  import { cn } from "$lib/utils";

  export type ListingMobileCardDensity = "default" | "compact";

  let {
    property,
    visibleColumns,
    imageColumnView,
    enabledMetricVariants,
    propertyDisplay,
    featureCatalog,
    activeMetricVariant,
    activeCollectionId,
    openImageModal,
    openEditListing,
    getRowInteractions,
    displayTitle,
    density = "default"
  }: ListingTableRowProps & { density?: ListingMobileCardDensity } = $props();

  const isCompact = $derived(density === "compact");

  const interactions = $derived(getRowInteractions(property));

  const showCountFeatures = $derived(propertyDisplay.showCountFeatures && visibleColumns.property);
  const showAmenities = $derived(visibleColumns.property);
  const showTitle = $derived(visibleColumns.property);
  const showPrice = $derived(visibleColumns.price);
  const showArea = $derived(visibleColumns.area);
  const showValue = $derived(visibleColumns.value);
  const showImage = $derived(visibleColumns.image);
  const showEtapa = $derived(visibleColumns.stage);
  const showMetrics = $derived(
    (showArea || showValue) &&
      (enabledMetricVariants.has("total") || enabledMetricVariants.has("privado"))
  );
  const titleOnHero = $derived(showImage && showTitle);
  const showSummaryRow = $derived(showPrice || showCountFeatures || showEtapa);
  const featureRows = $derived(
    showAmenities
      ? layoutListingMobileFeatureRows(
          getListingMobileFeatures(property, featureCatalog)
        )
      : []
  );

  const metricSegments = $derived([
    ...(enabledMetricVariants.has("total")
      ? [
          {
            variant: "total" as const,
            area: property.totalAreaM2,
            pricePerM2: calculatePricePerM2(property.price, property.totalAreaM2)
          }
        ]
      : []),
    ...(enabledMetricVariants.has("privado")
      ? [
          {
            variant: "privado" as const,
            area: property.privateAreaM2,
            pricePerM2: calculatePrivateAreaPricePerM2(property.price, property.privateAreaM2)
          }
        ]
      : [])
  ]);

  const detailRowCount = $derived(
    Math.max(showMetrics ? metricSegments.length : 0, featureRows.length)
  );
  const showSummaryGrid = $derived(showSummaryRow || detailRowCount > 0);

  const titleEtapaProps = $derived({
    listing: property,
    collectionId: activeCollectionId,
    interactions,
    openEditListing,
    showMap: propertyDisplay.showAddress,
    showContact: propertyDisplay.showContact,
    showEtapa
  });

  const strikethroughClass = $derived(
    property.strikethrough ? "line-through opacity-50" : undefined
  );
</script>

<article
  id="listing-{property.id}"
  data-testid="listing-mobile-card-{property.id}"
  class={cn(
    "relative overflow-hidden border",
    isCompact ? "rounded-xl" : "rounded-2xl",
    property.starred
      ? "border-app-action/50 bg-app-action/20"
      : "border-app-border bg-app-surface"
  )}
>
  {#if showImage}
    <ListingMobileImageGallery
      {property}
      view={imageColumnView}
      layout="hero"
      showAddress={propertyDisplay.showAddress}
      onOpenImageModal={() => openImageModal(property)}
      class={isCompact ? "aspect-[2/1] rounded-t-xl" : "rounded-t-2xl"}
    >
      {#snippet overlays()}
        {#if titleOnHero}
          <div
            class={cn(
              "pointer-events-none absolute inset-x-0 top-0 z-10 bg-gradient-to-b from-black/80 via-black/50 to-transparent",
              isCompact ? "px-3 pb-4 pt-2.5" : "px-3.5 pb-5 pt-3"
            )}
          >
            <div class="pointer-events-auto min-w-0">
              <ListingTitleStageRow
                {...titleEtapaProps}
                {displayTitle}
                overlayOnMedia
                class="min-w-0"
              />
            </div>
          </div>
        {/if}
      {/snippet}
    </ListingMobileImageGallery>
  {/if}

  <div
    data-testid="listing-mobile-body"
    class={cn(
      LISTING_MOBILE_CARD_BODY_CLASS,
      isCompact && "gap-1 px-3 pb-3",
      showImage ? (isCompact ? "pt-2" : "pt-2.5") : (isCompact ? "pt-3" : "pt-3.5")
    )}
  >
    {#if showTitle && !titleOnHero}
      <ListingTitleStageRow {...titleEtapaProps} {displayTitle} class="min-w-0" />
    {/if}

    {#if showSummaryGrid}
      <div
        data-testid="listing-mobile-summary-grid"
        class={cn(LISTING_MOBILE_SUMMARY_GRID_CLASS, isCompact && "gap-x-2 gap-y-1")}
      >
        {#if showSummaryRow}
          <div class="flex min-w-0 items-center gap-1.5 overflow-hidden">
            {#if showPrice}
              <div data-testid="listing-mobile-price" class="shrink-0 text-app-muted">
                <ClickablePrice
                  price={property.price}
                  listingId={property.id}
                  collectionId={activeCollectionId}
                  strikethrough={property.strikethrough}
                />
              </div>
            {/if}
            {#if showCountFeatures}
              <ListingMobileCountFeatures {property} {interactions} class="min-w-0" />
            {/if}
          </div>

          {#if showEtapa}
            <div class="flex justify-end">
              <ListingRowStageSelect {property} {interactions} class="shrink-0" />
            </div>
          {:else}
            <span aria-hidden="true"></span>
          {/if}
        {/if}

        {#each Array.from({ length: detailRowCount }, (_, rowIndex) => rowIndex) as rowIndex (rowIndex)}
          {@const metricSegment = showMetrics ? metricSegments[rowIndex] : undefined}
          {@const featurePair = featureRows[rowIndex]}

          {#if metricSegment}
            <ListingMobileMetricRow
              data-testid={rowIndex === 0 ? "listing-mobile-metrics" : undefined}
              segments={[metricSegment]}
              propertyType={property.propertyType}
              {showArea}
              showValue={showValue}
              activeVariant={activeMetricVariant}
              emphasizeWhenSorted={activeMetricVariant !== null}
              class={cn("min-w-0", strikethroughClass)}
            />
          {:else}
            <span aria-hidden="true"></span>
          {/if}

          {#if featurePair?.[0] || featurePair?.[1]}
            <div class="grid grid-cols-[auto_auto] justify-items-end justify-end gap-x-3">
              {#if featurePair[0]}
                <ListingMobileFeatureButton
                  feature={featurePair[0]}
                  strikethrough={property.strikethrough}
                />
              {:else}
                <span aria-hidden="true"></span>
              {/if}
              {#if featurePair[1]}
                <ListingMobileFeatureButton
                  feature={featurePair[1]}
                  strikethrough={property.strikethrough}
                />
              {:else}
                <span aria-hidden="true"></span>
              {/if}
            </div>
          {:else}
            <span aria-hidden="true"></span>
          {/if}
        {/each}
      </div>
    {/if}
  </div>
</article>
