// app/casa/components/settings-panel.tsx
"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { cn } from "@/lib/utils"
import { PageToolbarIconButton } from "@/app/components/page-toolbar"
import { Cross2Icon, GearIcon, ResetIcon } from "@radix-ui/react-icons"
import { useState } from "react"

import {
  DEFAULT_SETTINGS,
  useSettings,
  type SimulatorSettings,
  type SliderRange,
} from "./utils/settings"

// ============================================================================
// HELPER COMPONENTS
// ============================================================================

interface NumberInputProps {
  value: number
  onChange: (value: number) => void
  min?: number
  max?: number
  step?: number
  className?: string
}

const NumberInput = ({ value, onChange, min, max, step, className }: NumberInputProps) => {
  return (
    <Input
      type="number"
      value={value}
      onChange={(e) => onChange(parseFloat(e.target.value) || 0)}
      min={min}
      max={max}
      step={step}
      className={cn("font-mono w-24", className)}
    />
  )
}

interface CurrencyInputProps {
  value: number
  onChange: (value: number) => void
  className?: string
}

const CurrencyInput = ({ value, onChange, className }: CurrencyInputProps) => {
  return (
    <Input
      type="number"
      value={value}
      onChange={(e) => onChange(parseInt(e.target.value, 10) || 0)}
      step={10000}
      className={cn("font-mono w-32", className)}
    />
  )
}

interface SliderRangeInputProps {
  label: string
  range: SliderRange
  onChange: (range: SliderRange) => void
  isPercent?: boolean
  isCurrency?: boolean
}

const SliderRangeInput = ({
  label,
  range,
  onChange,
  isPercent = false,
  isCurrency = false,
}: SliderRangeInputProps) => {
  return (
    <div className="space-y-2">
      <Label className="text-sm text-app-muted">{label}</Label>
      <div className="flex items-center gap-2 flex-wrap">
        <div className="flex items-center gap-1">
          <span className="text-xs text-app-subtle w-8">Min:</span>
          <NumberInput
            value={range.min}
            onChange={(v) => onChange({ ...range, min: v })}
            step={range.step}
          />
          {isPercent && <span className="text-xs text-app-subtle">%</span>}
          {isCurrency && <span className="text-xs text-app-subtle">R$</span>}
        </div>
        <div className="flex items-center gap-1">
          <span className="text-xs text-app-subtle w-8">Max:</span>
          <NumberInput
            value={range.max}
            onChange={(v) => onChange({ ...range, max: v })}
            step={range.step}
          />
          {isPercent && <span className="text-xs text-app-subtle">%</span>}
          {isCurrency && <span className="text-xs text-app-subtle">R$</span>}
        </div>
        <div className="flex items-center gap-1">
          <span className="text-xs text-app-subtle w-8">Step:</span>
          <NumberInput
            value={range.step}
            onChange={(v) => onChange({ ...range, step: v })}
            step={0.01}
            className="w-20"
          />
        </div>
      </div>
    </div>
  )
}

interface ValueListInputProps {
  label: string
  values: number[]
  onChange: (values: number[]) => void
  isCurrency?: boolean
}

const ValueListInput = ({
  label,
  values,
  onChange,
  isCurrency = false,
}: ValueListInputProps) => {
  const addValue = () => {
    const lastValue = values[values.length - 1] || 0
    onChange([...values, lastValue])
  }

  const removeValue = (index: number) => {
    if (values.length > 1) {
      onChange(values.filter((_, i) => i !== index))
    }
  }

  const updateValue = (index: number, value: number) => {
    const newValues = [...values]
    newValues[index] = value
    onChange(newValues)
  }

  return (
    <div className="space-y-2">
      <Label className="text-sm text-app-muted">{label}</Label>
      <div className="space-y-2">
        {values.map((value, index) => (
          <div key={index} className="flex items-center gap-2">
            {isCurrency ? (
              <div className="flex items-center gap-1">
                <span className="text-xs text-app-subtle">R$</span>
                <CurrencyInput
                  value={value}
                  onChange={(v) => updateValue(index, v)}
                />
              </div>
            ) : (
              <NumberInput
                value={value}
                onChange={(v) => updateValue(index, v)}
              />
            )}
            <button
              onClick={() => removeValue(index)}
              disabled={values.length === 1}
              className="p-1 rounded hover:bg-brightGrey disabled:opacity-30 disabled:cursor-not-allowed transition-colors"
            >
              <Cross2Icon className="h-4 w-4 text-app-subtle hover:text-salmon" />
            </button>
          </div>
        ))}
        <button
          onClick={addValue}
          className="text-xs text-app-accent hover:text-app-accent/80 transition-colors"
        >
          + Adicionar valor
        </button>
      </div>
    </div>
  )
}

// ============================================================================
// MAIN COMPONENT
// ============================================================================

interface SettingsPanelProps {
  isOpen: boolean
  onClose: () => void
}

export const SettingsPanel = ({ isOpen, onClose }: SettingsPanelProps) => {
  const { settings, updateSettings, resetSettings } = useSettings()
  const [localSettings, setLocalSettings] = useState<SimulatorSettings>(settings)

  // Note: handleOpen callback was removed as unused. If panel needs to sync on open,
  // consider using useEffect with isOpen dependency.

  if (!isOpen) return null

  const handleSave = () => {
    updateSettings(localSettings)
    onClose()
  }

  const handleReset = () => {
    setLocalSettings(DEFAULT_SETTINGS)
    resetSettings()
  }

  const handleCancel = () => {
    setLocalSettings(settings)
    onClose()
  }

  return (
    <div
      className="fixed inset-0 z-50 bg-app-fg/80 flex items-start justify-center overflow-y-auto py-8"
      onClick={handleCancel}
    >
      <div
        className="w-full max-w-2xl mx-4"
        onClick={(e) => e.stopPropagation()}
      >
        <Card className="bg-app-surface border-app-border">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-4">
            <CardTitle className="text-xl flex items-center gap-2">
              <GearIcon className="h-5 w-5" />
              Configurações do Simulador
            </CardTitle>
            <button
              onClick={handleCancel}
              className="p-2 rounded hover:bg-brightGrey transition-colors"
            >
              <Cross2Icon className="h-5 w-5 text-app-muted" />
            </button>
          </CardHeader>
          <CardContent className="space-y-6">
            {/* CET */}
            <div className="space-y-2">
              <Label className="text-sm font-semibold text-app-accent">
                CET - Custo Efetivo Total
              </Label>
              <p className="text-xs text-app-subtle mb-2">
                Custo adicional estimado (seguros, taxas) a ser adicionado ao cálculo do CET.
              </p>
              <div className="flex items-center gap-2">
                <NumberInput
                  value={localSettings.cetAdditionalCost * 100}
                  onChange={(v) =>
                    setLocalSettings({ ...localSettings, cetAdditionalCost: v / 100 })
                  }
                  step={0.1}
                  min={0}
                  max={10}
                />
                <span className="text-sm text-app-subtle">% a.a.</span>
              </div>
            </div>

            {/* Prazos */}
            <div className="space-y-2">
              <Label className="text-sm font-semibold text-app-accent">
                Opções de Prazo (meses)
              </Label>
              <p className="text-xs text-app-subtle mb-2">
                Prazos disponíveis para seleção rápida no simulador.
              </p>
              <ValueListInput
                label=""
                values={localSettings.prazoOptions}
                onChange={(values) =>
                  setLocalSettings({ ...localSettings, prazoOptions: values.sort((a, b) => a - b) })
                }
              />
            </div>

            {/* Slider Ranges */}
            <div className="space-y-4">
              <Label className="text-sm font-semibold text-app-accent">
                Limites dos Sliders
              </Label>
              <p className="text-xs text-app-subtle mb-2">
                Configure os valores mínimos, máximos e incrementos de cada slider.
              </p>

              <SliderRangeInput
                label="Taxa de Juros Anual"
                range={localSettings.sliders.taxaAnual}
                onChange={(range) =>
                  setLocalSettings({
                    ...localSettings,
                    sliders: { ...localSettings.sliders, taxaAnual: range },
                  })
                }
                isPercent
              />

              <SliderRangeInput
                label="TR Mensal"
                range={localSettings.sliders.trMensal}
                onChange={(range) =>
                  setLocalSettings({
                    ...localSettings,
                    sliders: { ...localSettings.sliders, trMensal: range },
                  })
                }
                isPercent
              />

              <SliderRangeInput
                label="Haircut (Deságio Permuta)"
                range={localSettings.sliders.haircut}
                onChange={(range) =>
                  setLocalSettings({
                    ...localSettings,
                    sliders: { ...localSettings.sliders, haircut: range },
                  })
                }
                isPercent
              />

              <SliderRangeInput
                label="Aporte Extra Mensal"
                range={localSettings.sliders.aporteExtra}
                onChange={(range) =>
                  setLocalSettings({
                    ...localSettings,
                    sliders: { ...localSettings.sliders, aporteExtra: range },
                  })
                }
                isCurrency
              />

              <SliderRangeInput
                label="Renda Mensal"
                range={localSettings.sliders.rendaMensal}
                onChange={(range) =>
                  setLocalSettings({
                    ...localSettings,
                    sliders: { ...localSettings.sliders, rendaMensal: range },
                  })
                }
                isCurrency
              />
            </div>

            {/* Actions */}
            <div className="flex items-center justify-between pt-4 border-t border-app-border">
              <button
                onClick={handleReset}
                className="flex items-center gap-2 px-4 py-2 text-sm text-salmon hover:text-salmon/80 transition-colors"
              >
                <ResetIcon className="h-4 w-4" />
                Restaurar Padrões
              </button>
              <div className="flex gap-2">
                <button
                  onClick={handleCancel}
                  className="px-4 py-2 text-sm text-app-muted hover:text-app-fg border border-app-border rounded-md transition-colors"
                >
                  Cancelar
                </button>
                <button
                  onClick={handleSave}
                  className="px-4 py-2 text-sm bg-app-action text-app-action-foreground font-semibold rounded-md hover:bg-app-action-hover transition-colors"
                >
                  Salvar
                </button>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

// ============================================================================
// SETTINGS BUTTON
// ============================================================================

interface SettingsButtonProps {
  onClick: () => void
}

export const SettingsButton = ({ onClick }: SettingsButtonProps) => {
  return (
    <PageToolbarIconButton onClick={onClick} title="Configurações">
      <GearIcon className="text-app-muted" />
    </PageToolbarIconButton>
  )
}

// apps/web/src/lib/components/financiamento/SettingsPanel.svelte
<script lang="ts">
  import { Plus, RotateCcw, X } from "@lucide/svelte";
  import Card from "$lib/components/ui/Card.svelte";
  import CardContent from "$lib/components/ui/CardContent.svelte";
  import CardHeader from "$lib/components/ui/CardHeader.svelte";
  import CardTitle from "$lib/components/ui/CardTitle.svelte";
  import Input from "$lib/components/ui/Input.svelte";
  import Label from "$lib/components/ui/Label.svelte";
  import { getSettingsContext } from "$lib/financiamento/settings-context.svelte";
  import {
    DEFAULT_SETTINGS,
    type SimulatorSettings,
    type SliderRange
  } from "$lib/financiamento/settings";
  import { cn } from "$lib/utils";

  let {
    isOpen = false,
    onClose
  }: {
    isOpen?: boolean;
    onClose: () => void;
  } = $props();

  const { settings, updateSettings, resetSettings } = getSettingsContext();
  let localSettings = $state<SimulatorSettings>(settings);

  $effect(() => {
    if (isOpen) {
      localSettings = structuredClone(settings);
    }
  });

  function handleSave() {
    updateSettings(localSettings);
    onClose();
  }

  function handleReset() {
    localSettings = structuredClone(DEFAULT_SETTINGS);
    resetSettings();
  }

  function handleCancel() {
    localSettings = structuredClone(settings);
    onClose();
  }
</script>

{#if isOpen}
  <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
  <div
    class="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-app-fg/80 py-8"
    onclick={handleCancel}
    role="presentation"
  >
    <div
      class="mx-4 w-full max-w-2xl"
      role="dialog"
      aria-modal="true"
      aria-label="Configurações do simulador"
      onclick={(e) => e.stopPropagation()}
      onkeydown={(e) => e.stopPropagation()}
    >
      <Card class="border-app-border bg-app-surface">
        <CardHeader class="flex flex-row items-center justify-between space-y-0 pb-4">
          <CardTitle class="flex items-center gap-2 text-xl">⚙️ Configurações do Simulador</CardTitle>
          <button
            type="button"
            class="rounded p-2 transition-colors hover:bg-brightGrey"
            onclick={handleCancel}
            aria-label="Fechar"
          >
            <X class="size-5 text-app-muted" />
          </button>
        </CardHeader>
        <CardContent class="space-y-6">
          <div class="space-y-2">
            <Label class="text-sm font-semibold text-app-accent">CET - Custo Efetivo Total</Label>
            <p class="mb-2 text-xs text-app-subtle">
              Custo adicional estimado (seguros, taxas) a ser adicionado ao cálculo do CET.
            </p>
            <div class="flex items-center gap-2">
              <Input
                type="number"
                class="w-24 font-mono"
                value={localSettings.cetAdditionalCost * 100}
                oninput={(e) => {
                  const v = parseFloat(e.currentTarget.value) || 0;
                  localSettings = { ...localSettings, cetAdditionalCost: v / 100 };
                }}
                step={0.1}
                min={0}
                max={10}
              />
              <span class="text-sm text-app-subtle">% a.a.</span>
            </div>
          </div>

          <div class="space-y-2">
            <Label class="text-sm font-semibold text-app-accent">Opções de Prazo (meses)</Label>
            <p class="mb-2 text-xs text-app-subtle">
              Prazos disponíveis para seleção rápida no simulador.
            </p>
            <div class="space-y-2">
              {#each localSettings.prazoOptions as value, index (index)}
                <div class="flex items-center gap-2">
                  <Input
                    type="number"
                    class="w-24 font-mono"
                    {value}
                    oninput={(e) => {
                      const v = parseInt(e.currentTarget.value, 10) || 0;
                      const next = [...localSettings.prazoOptions];
                      next[index] = v;
                      localSettings = {
                        ...localSettings,
                        prazoOptions: [...next].sort((a, b) => a - b)
                      };
                    }}
                  />
                  <button
                    type="button"
                    class="rounded p-1 transition-colors hover:bg-brightGrey disabled:cursor-not-allowed disabled:opacity-30"
                    disabled={localSettings.prazoOptions.length <= 1}
                    onclick={() => {
                      localSettings = {
                        ...localSettings,
                        prazoOptions: localSettings.prazoOptions.filter((_, i) => i !== index)
                      };
                    }}
                    aria-label="Remover prazo"
                  >
                    <X class="size-4 text-app-subtle hover:text-salmon" />
                  </button>
                </div>
              {/each}
              <button
                type="button"
                class="text-xs text-app-accent transition-colors hover:text-app-accent/80"
                onclick={() => {
                  const last = localSettings.prazoOptions.at(-1) ?? 0;
                  localSettings = {
                    ...localSettings,
                    prazoOptions: [...localSettings.prazoOptions, last]
                  };
                }}
              >
                <Plus class="mr-1 inline size-3" />
                Adicionar valor
              </button>
            </div>
          </div>

          <div class="space-y-4">
            <Label class="text-sm font-semibold text-app-accent">Limites dos Sliders</Label>
            <p class="mb-2 text-xs text-app-subtle">
              Configure os valores mínimos, máximos e incrementos de cada slider.
            </p>

            {#each [
              { key: "taxaAnual" as const, label: "Taxa de Juros Anual", isPercent: true },
              { key: "trMensal" as const, label: "TR Mensal", isPercent: true },
              { key: "haircut" as const, label: "Haircut (Deságio Permuta)", isPercent: true },
              { key: "aporteExtra" as const, label: "Aporte Extra Mensal", isCurrency: true },
              { key: "rendaMensal" as const, label: "Renda Mensal", isCurrency: true }
            ] as row (row.key)}
              {@const range = localSettings.sliders[row.key]}
              <div class="space-y-2">
                <Label class="text-sm text-app-muted">{row.label}</Label>
                <div class="flex flex-wrap items-center gap-2">
                  {#each [
                    { label: "Min:", field: "min" as const },
                    { label: "Max:", field: "max" as const },
                    { label: "Step:", field: "step" as const, className: "w-20", step: 0.01 }
                  ] as part (part.field)}
                    <div class="flex items-center gap-1">
                      <span class="w-8 text-xs text-app-subtle">{part.label}</span>
                      <Input
                        type="number"
                        class={cn("w-24 font-mono", part.className)}
                        value={range[part.field]}
                        step={part.step ?? range.step}
                        oninput={(e) => {
                          const v = parseFloat(e.currentTarget.value) || 0;
                          const next: SliderRange = { ...range, [part.field]: v };
                          localSettings = {
                            ...localSettings,
                            sliders: { ...localSettings.sliders, [row.key]: next }
                          };
                        }}
                      />
                      {#if row.isPercent}
                        <span class="text-xs text-app-subtle">%</span>
                      {:else if row.isCurrency}
                        <span class="text-xs text-app-subtle">R$</span>
                      {/if}
                    </div>
                  {/each}
                </div>
              </div>
            {/each}
          </div>

          <div class="flex items-center justify-between border-t border-app-border pt-4">
            <button
              type="button"
              class="flex items-center gap-2 px-4 py-2 text-sm text-salmon transition-colors hover:text-salmon/80"
              onclick={handleReset}
            >
              <RotateCcw class="size-4" />
              Restaurar Padrões
            </button>
            <div class="flex gap-2">
              <button
                type="button"
                class="rounded-md border border-app-border px-4 py-2 text-sm text-app-muted transition-colors hover:text-app-fg"
                onclick={handleCancel}
              >
                Cancelar
              </button>
              <button
                type="button"
                class="rounded-md bg-app-action px-4 py-2 text-sm font-semibold text-app-action-foreground transition-colors hover:bg-app-action-hover"
                onclick={handleSave}
              >
                Salvar
              </button>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  </div>
{/if}
